### PR TITLE
Py3 compatibility

### PR DESCRIPTION
**Pull request by yeganer**
As a small spare time project I wanted to see how much work it would be to add python 3 support to tardis.
With the help of the `futurize` tool this task was surprisingly easy.

Just to be clear, I don't expect a merge soon.

### CODE REVIEW

**Comment by ftsamis** [comment]
I am wondering if there is any point to target both python2 and python3 instead of only python3.

**Comment by wkerzendorf** [comment]
@ftsamis this was just a test - there is no plans to make tardis python 3 compatible in the next year or so.

**Comment by ftsamis** [comment]
@wkerzendorf I understand, but I believe my question is still relevant. Unless the answer is that there is no answer yet.

**Comment by wkerzendorf** [comment]
The forseeable future will not see any python 3 support @ftsamis

**Pull request closed without merging**
