### PR TITLE
Improved numba_montecarlo

### PR DESCRIPTION
**Pull request by Phantsure**
Improved numba_montecarlo
## Description

I have worked over the changes proposed in #929 and added a few my changes. `prange` is used
provide parallelism to the code. Some import statements are worked on.

## How Has This Been Tested?

Ran the tests and they were running fine.
## Screenshots (if appropriate):

Screenshot_2020-03-24 Screenshot from 2020-03-24 00-46-54 png (PNG Image, 1920 × 1080 pixels) - Scaled (85%)

### CODE REVIEW

**Comment by wkerzendorf** [comment]
is it faster than before?

**Comment by Phantsure** [comment]
I was not able to check as simulation failed to run.

**Comment by Phantsure** [comment]
I could use time function but I don't have the appropriate data to test.

**Comment by wkerzendorf** [comment]
the tests are failing as well.

**Comment by Phantsure** [comment]
TARDIS pytest for linux are working fine. I don't understand why it is showing failing. All seems fine in local pytest. I have also put a screenshot of the same

**Comment by Phantsure** [comment]
`File "tardis/montecarlo/montecarlo_numba/vpacket.py", line 68:` is the file with error and error is `TypeError: missing a required argument: 'montecarlo_configuration'`. I don't know with what configurations settings should i generate the montecarlo_config file. If you could give me some idea.
BTW this is the same error, i DMed you.

**Pull request closed without merging**
