### PR TITLE
Move RPacketTracker class to a new file packet_trackers.py

### PR DESCRIPTION
**Pull request by Sumit112192**
### :pencil: Description

**Type:** :roller_coaster: `restructure`
This pull request is going to handle the following task
- [x] Move the Existing RPacketTracker class to a new file packet_trackers.py

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [x] Other method (describe)
- [ ] My changes can't be tested (explain why)

`pytest tardis`

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
is this in a state that it should be reviewed?

**Comment by wkerzendorf** [comment]
This PR should only move the `RPacketTracker` class to packet_trackers. It also introduces a LastInteractionTracker which should be a different PR.

**Comment by Sumit112192** [comment]
> This PR should only move the `RPacketTracker` class to packet_trackers. It also introduces a LastInteractionTracker which should be a different PR. 

I will do that. Thanks.

**Comment by wkerzendorf** [comment]
looks - good. you can now do a PR on this PR.

**Comment by Sumit112192** [comment]
@wkerzendorf This PR only moves the RPacketTracker Class to a new file packet_trackers.py and is ready for review.

**Review by andrewfullard — APPROVED** [review]
Good refactor, thanks

**Pull request merged**
