### PR TITLE
Use interpolated values to do formal integral with more shells

### PR DESCRIPTION
**Pull request by chvogl**

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@chvogl are the refdata still misbehaving ?

**Comment by chvogl** [comment]
@wkerzendorf Yes, the problem still persists. I have run the tests locally with the same cython that is used on Travis and the tests pass. I am currently at a loss to why it does not work on Travis. It must be related to the interpolation in some way.

**Comment by wkerzendorf** [comment]
@chvogl should we just merge this?

**Comment by chvogl** [comment]
@wkerzendorf In principle, I think we can merge this. Do you think we should resolve #878 first?

**Pull request merged**
