### PR TITLE
Cmfgen2tardis.py fix

### PR DESCRIPTION
**Pull request by shreyansjain012**
The import path and the function name is wrong 
## Description

`tardis/scripts/cmfgen2tardis.py`:
   - Updated import path 
   - corrected `from_hdf5()` to `from_hdf()`
## Motivation and Context
This file can't run if import statements and functions names are wrong

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jaladh-singhal** [comment]
@shreyansjain012 Congrats for your 1st contribution to TARDIS! Good catch - logically it seems right to me. 

Have you practically verified these errors (& your fixes) by running this python script?

**Comment by shreyansjain012** [comment]
@shivaylamba Thank You. I will soon make the necessary changes in my other PR's descriptions too.

**Comment by shreyansjain012** [comment]
> Have you practically verified these errors (& your fixes) by running this python script?

@jaladh-singhal I ran the script and this is what I got
**Without correction**
no-module
**After correction**
with-module

Now the error has changed. Working on it

**Comment by shreyansjain012** [comment]
@jaladh-singhal - in the documentation they used `DDC15_SN_HYDRO_DATA_0.976d` file as input where can I find this file?

**Comment by jaladh-singhal** [comment]
@shreyansjain012 Search it around, it is possibly some atomic data file. And maybe @marxwillia or @epassaro can help you!

And one thing to keep in mind, try to avoid screenshots for sharing code/command/tracebacks - rather use multi-line code blocks (see markdown guide, if you don't know).

**Comment by shreyansjain012** [comment]
I have searched in tardis-refdata repo also coudn't find it.

**Pull request closed without merging**
