### PR TITLE
completed the first objective mentioned in the integration test topic.

### PR DESCRIPTION
**Pull request by not4win**
All the respective test logs found in unit-test and integration-test folder.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
could you please be more descriptive in your PR.

**Comment by not4win** [comment]
Objective : Run tests.
Unit tests
* the output of  python setup.py test is stored in simple-unit-test.log
* the output of the advanced unit test 'python setup.py test --args="--tardis-refdata=/path/to/tardis-refdata/" ' is stored in advanced-test.log
* the output of plasma reference 'pytest -rs tardis/plasma/tests/test_complete_plasmas.py
--tardis-refdata="/path/to/tardis-refdata/" --generate-reference ' is stored in plasma-refernce.html
Integration test
*Downloaded the reference files, configured the integration.yml and ran the command 'python setup.py test --args="--integration=integration.yml -m integration
--generate-reference --less-packets" '. The output is stored in integration-test/integration-test.log

**Comment by wkerzendorf** [comment]
The integration tests have failed - have a look what went wrong.

**Comment by not4win** [comment]
Oh okay! But I'm not able to figure out what is the error over here.

**Comment by wkerzendorf** [comment]
care to try to figure it out?

**Comment by marxwillia** [comment]
You have the output of the tests.  Have you read through them and tried to identify any potential problems?

**Comment by not4win** [comment]
I read the output of the test files. The schema defined in /tardis/io/schmeas/montecarlo.yml doesnt match the json file. Therfore gives out a validation error.
`jsonschema.exceptions.ValidationError: Additional properties are not allowed ('black_body_sampling' was unexpected)
`
The atom data used for this is kurucz_atom_chianti_many.h5
Tweaking the schema files doesnt seem to be the solution because it gives several other validation errors.
Tweaking around validation does not seem to be a solution as it degrades the purpose of testing.

My issue is similar to open issue #997

**Comment by not4win** [comment]
After even deeper inspection, I found that the montecarlo schema file did not have 'black_body_sampling' definition defined. Hence the error(mismatch of values from integration-tests/paper1_macroatom/config.yml and schmeas/montecarlo.yml).But even after adding the definition its giving me the same error! Really dont understand why!
Montecarlo schema is indeed added in base.yml schema.

Added schema definition:
`  black_body_sampling:
    start:
      type: quantity
      default : 1 angstrom
    stop:
      type: quantity
      default: 1000000 angstrom
    num:
      type: number
      default: 1000000`

**Comment by wkerzendorf** [comment]
for now maybe remove this line in the input file and try to get the tests running.

**Comment by not4win** [comment]
It worked! I feel so emotional. I'll make a new PR to show the results. 
Also integration-tests is using capturemanager class with outdated functions. Should I make a PR with the new updated working functions??

**Comment by not4win** [comment]
Ive got the integration tests running and the output is stored in integration_test.html. Whats my next objective??

**Comment by pkj-m** [comment]
@not4win can you share how you managed to run the integration tests? I am facing the same error and can't figure out how to get the tests to successfully run without significantly modifying the schemas in the YAML files. 

Did you modify one of the files to match the schema of the other or is there some other solution to the problem?

**Comment by not4win** [comment]
Yes! I had to modify the files to match the schema. Otherwise it throws validation error

**Pull request closed without merging**
