### PR TITLE
Bugfix test cmontecarlo

### PR DESCRIPTION
**Pull request by yeganer**
Fixed a bug in the test_cmontecarlo.c file and enabled testing for the C funtctions.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@orbitfold @ssim can one of you check and merge? I'm happy with these changes.

**Comment by yeganer** [comment]
added `include_dirs = ['numpy']` as proposed by @embray

**Comment by wkerzendorf** [comment]
@tardis-sn/tardis-core As per our guidelines I need a second person to look at this PR and merge it.

**Comment by orbitfold** [comment]
Looks good, merging.

**Pull request merged**
