### PR TITLE
First Objective in 'TARDIS Setup Framework'

### PR DESCRIPTION
**Pull request by karban8**
## Description

This Pull request is for submission of the first objective for the proposal, "TARDIS Setups Framework", mentored by Ezequiel Passaro and Andrew Fullard, in a Jupyter Notebook. It contains the simulation of a 16d model as provided in tardis-setups in this [link](https://github.com/tardis-sn/tardis-setups/tree/master/2020/2020_williamson_94I/code_comp_setups).
## How Has This Been Tested?
- [ ] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

## Screenshots (if appropriate):
Plotted Spectrum of Model 16d
Screenshot from 2021-03-19 11-40-52
Screenshot from 2021-03-19 11-40-56
Screenshot from 2021-03-19 11-40-58

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by karban8** [comment]
@epassaro and @andrewfullard Please review my PR. Thanks!

**Comment by andrewfullard** [comment]
Please commit your notebook so we can check the run and plotted spectrum

**Comment by karban8** [comment]
> Please commit your notebook so we can check the run and plotted spectrum

I have already committed my notebook( kar_model_run/run_16d.ipynb ) along with the model files.

**Comment by andrewfullard** [comment]
Thanks, that looks good. You can go ahead and start your application following the guidelines on the TARDIS GSoC page

**Review by andrewfullard — APPROVED** [review]

**Pull request closed without merging**
