### PR TITLE
Updating the citation guidelines. 

### PR DESCRIPTION
**Pull request by wkerzendorf**
Inspired by discussion with Stephen Smartt, @ssim et al.

### CODE REVIEW

**Comment by marxwillia** [comment]
Rerun the tests, things should pass.

**Comment by jamesgillanders** [comment]
The link for the Zenodo citation will continue to get outdated if the version is always fixed like in this case. Consider using the link that always defaults to the most up-to-date version (https://doi.org/10.5281/zenodo.592480), and/or specify that the user should/is encouraged to change the version link depending on the version they used for their work

**Comment by jamesgillanders** [comment]
Also, it would be good to get this merged to improve citation stuff

**Review by jamesgillanders — APPROVED** [review]

**Review by jamesgillanders — CHANGES_REQUESTED** [review]
see comments - otherwise looks good

**Pull request closed without merging**
