### PR TITLE
Fixed the array types when interpolate_shells > 0.  Now returns the p…

### PR DESCRIPTION
**Pull request by Rodot-**
When interpolate_shells > 0, the formal integral broke with an attribute error claiming that numpy arrays had no attribute "values"
Issue #1463 

I've corrected the return types of one of the functions so that they are no longer numpy arrays.

## Description

When interpolate_shells > 0, `interpolate_integrator_quantities` would change the type of electron_densities_integ, tau_sobolev_integ, and Jredlu from pandas dataframes or series to numpy arrays due to the fact that `scipy.interp1d` always returns a numpy array.  This was problematic because the formal_integral Cython wrapper access the `.values` attributes of these arrays assuming they were pandas objects.  I've corrected this so now these arrays are set to have the correct type.
## Motivation and Context
Now interpolate_shells can have values greater than 0 without failing.

## How Has This Been Tested?
- [x] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [x] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by Rodot-** [comment]
Should also be of note: This bug really demonstrates the need for formal integral tests

**Review by chvogl — APPROVED** [review]
Thanks for fixing my blunder ;)

**Comment by chvogl** [comment]
I also agree that we should include a test with interpolate_shells > 0, which is the setting people should be using.

**Comment by chvogl** [comment]
I took the liberty to merge this without a second review. The changes are minimal and fix an urgent problem.

**Pull request merged**
