### PR TITLE
Simulation - restructure

### PR DESCRIPTION
**Pull request by wkerzendorf**
I have restructured the simulation part of TARDIS to be able to do runs that allow to get a consistent plasma state with just a given t_inner. In the process - the model and the simulation have been disentangled. @tardis-sn/tardis-core I'll need some testing and feedback,

### CODE REVIEW

**Comment by souravsingh** [comment]
I will be willing to do the testing.What unit tests do I need to write for this?

**Comment by wkerzendorf** [comment]
@souravsingh I think this is work relatively deep inside the code. To get a good overview, you should do the colorize the logger part.

**Comment by chvogl** [comment]
@wkerzendorf  There are no objections on my part.

**Comment by wkerzendorf** [comment]
@tardis-sn/tardis-core merging

**Pull request merged**
