### PR TITLE
More work on cmontecarlo.c and the unit tests

### PR DESCRIPTION
**Pull request by mreineck**
cmontecarlo.c and cmontecarlo.h:
- some functions rearranged to allow better inlining
- specify "const" in the interfaces where appropriate
- add FIXME comments in places where I suspect problems but can't fix them myself
- minor performance tweaks (replacing divisions by multiplications etc.)
- unify variable declaration/definition where possible

Tests:
- avoid memory leaks in test_rpacket.c
- fix initialisations in test_montecarlo.c

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@mreineck if you want to discuss again, bigger restructuring let me know. This looks very good - thank you!

**Comment by mreineck** [comment]
Hmm, the bound_free test still fails on Travis. Can't reproduce it locally. Xfailing it again...

**Comment by wkerzendorf** [comment]
travis is running on docker containers on ubuntu as far as I understand.

**Comment by mreineck** [comment]
I'm now done with the things that seemed most urgent to me. Performance-wise I don't see any more low-hanging fruit.
The cmontecarlo tests definitely need reworking though - but I fear I'm not really qualified for this.

**Comment by wkerzendorf** [comment]
looks good!

**Pull request merged**
