### PR TITLE
Restructure the MontecarloRunner

### PR DESCRIPTION
**Pull request by ftsamis**
This PR introduces the necessary changes to the `MontecarloRunner` in order to make it work with the restructured `Radial1DModel`.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
looking good.

**Comment by ftsamis** [comment]
@wkerzendorf It doesn't. :( I realized that I need to change `montecarlo.pyx` as well because it uses the now gone `model.tardis_config` a lot.

Working on it now...

**Comment by yeganer** [comment]
I think of `MonteCarloRunner` as the bridge between python and C. So all information that needs to be passed to the C should be available in the runner.
I don''t know if that makes sense but that's how I see it, do you agree/disagree?

**Comment by ftsamis** [comment]
@yeganer That's right, it already gets the model and the plasma, but `montecarlo.pyx` was accessing `model.tardis_config` which is no longer available. So the point now is changing those access attempts to the correct thing.

Should be relatively easy.

**Comment by ftsamis** [comment]
Closing in favor of #652.

**Pull request closed without merging**
