### PR TITLE
Doc changes for RPacketTracker

### PR DESCRIPTION
**Pull request by Sumit112192**
### :pencil: Description

**Type:** :memo: `documentation` 

Many things in the RPacketTracker were outdated, so I updated those and also added the `boundary_interaction` part.

Things to add: Generate a diff version of what has changed, and comment it.
Edit*: It is already generated by github workflows
https://app.reviewnb.com/tardis-sn/tardis/pull/2795/

### CODE REVIEW

**Comment by Sumit112192** [comment]
Not much changed in the file, just some class renaming and added the new attributes.

**Comment by andrewfullard** [comment]
Make sure you commit the notebook *without* outputs.

**Comment by Sumit112192** [comment]
> Make sure you commit the notebook _without_ outputs.

done

**Comment by andrewfullard** [comment]
Do you know why the docs aren't building?

**Comment by Sumit112192** [comment]
> Do you know why the docs aren't building?

Due to the meta data of the notebook, right? It was discussed that this will be fixed in the workflows.

**Review by andrewfullard — APPROVED** [review]

**Review by Knights-Templars — APPROVED** [review]

**Pull request merged**
