### PR TITLE
Fix references and typos in documentation

### PR DESCRIPTION
**Pull request by shreyas3156**
### :pencil: Description

**Type:**  :memo: `documentation` 

- Fixes a typo in the Physics Walkthrough Intro doc.
- Changed the velocity subscript in the 'Model' notebook.
- Fixes a few grammatical errors.
- Corrects the reference to Energy Packet Initialization doc in [Line Interaction Treatments](https://tardis-sn.github.io/tardis/physics/montecarlo/lineinteraction.html) (which was earlier referring to some Python package).

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [x] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [x] I requested two reviewers for this pull request
- [x] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

### CODE REVIEW

**Comment by andrewfullard** [comment]
Nice PR, though the gamma-ray documentation notebook is pre-run because it currently cannot be run as part of the documentation action workflow

**Comment by shreyas3156** [comment]
> Nice PR, though the gamma-ray documentation notebook is pre-run because it currently cannot be run as part of the documentation action workflow

Thanks for the review. Shall I remove the commit with the change in the gamma-ray notebook?

**Comment by shreyas3156** [comment]
@andrewfullard @smithis7 I have removed the commit with the path-correction in gamma-ray notebook and added a few other commits.

**Review by andrewfullard — APPROVED** [review]

**Comment by shreyas3156** [comment]
> The docs don't seem to be building on GitHub, I'm not sure why. I want to take a look at the built docs before approving, but it looks very good.

Sure! We can try it out once the build-docs issue is fixed.

**Pull request merged**
