### PR TITLE
Migrate gui to PyQt5 (issue #988)

### PR DESCRIPTION
**Pull request by jordi5**
Replace calls for QtWidgets which changed from Qt4 to Qt5

Qt5 migrated all widgets from class QtGui to its own QtWidgets. This PR adresses those changes to make the GUI useful again.
Adresses issue #988

## Motivation and Context
Anaconda installs PyQt5 by default when installing the TRADIS env, and I found it very complicated to revert to PyQt4. Since the GUI was already written and the code already present, it turned out to work pretty well with minor changes.
This GUI will serve mainly as a visual guide of features to implement in Jupyter Notebook.

Files changed in tardis/gui: 
- `datahandler.py`: changed QtGui for QtWidgets, and PyQt4 to PyQt5. Fixed Sgnal functions
- `interface.py`: changed QtGui for QtWidgets, and PyQt4 to PyQt5
- `widgets.py`: changed QtGui for QtWidgets, and PyQt4 to PyQt5 Fixed Sgnal functions
- docs: `gui.rst` updated and improved slightly but not final commit                    
- added test files
- `simple_test_framework.yml`: added QT_API variable
- add `test_gui.py`
I think I restored most functionalities. Save figure is not working.

## How Has This Been Tested?
- [x] Wrote a new test for the GUI.

## Types of changes

- [x] Bug fix: if GUI wasn't working on your version it should now

Add PySide2 to the yml file to avoid errors.

## Checklist:

- [x]  I have updated the documentation accordingly.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
nice!

**Comment by wkerzendorf** [comment]
every PR should have tests and documentation in addition to the code.

**Comment by marxwillia** [comment]
This is good work. As you said, next step is to get the display info on click and double click to work.

**Comment by jordi5** [comment]
Thanks! There are residual files since I'm still figuring out the branching. I will improve this

**Comment by marxwillia** [comment]
Since you require pyside2, change the tardis_env.yml file and verify that a fresh install of the environment works.

**Comment by marxwillia** [comment]
Next, add a function that plots the TARDIS spectrum interactively using bqplot.

**Comment by wkerzendorf** [comment]
@jordi5 really well done!!

**Comment by jordi5** [comment]
Thank you! Marc, I'm sorry, I've been busy with college so just today I started with bqplot. It seems to have many tools for plotting, however from what I tried, animations will still be a little clunky as they in the current GUI. I will probably have something for tomorrow night or Sunday.

**Comment by marxwillia** [comment]
How is the bqplot task going @jordi5 ?

**Comment by jordi5** [comment]
Not great. I've been busy, sorry.

**Comment by jordi5** [comment]
im working on it

**Comment by jordi5** [comment]
@marxwillia Hi! I've finally started toying with the interactive plotting. I'm doing it via jupyter notebook. Should I keep working on a Notebook or should I try to include this in the GUI? I don't even know if that can be done but it doesn't seem productive to keep adding to the GUI.

**Pull request merged**
