### PR TITLE
Reading in decay radiation data in atom data

### PR DESCRIPTION
**Pull request by Knights-Templars**
Type: | 🚦 new feature

Added "decay_radiation_data" as an hdf name in atomdata class.
This makes it easier to use the atomic data file to store both atomic and nuclear data.
📌 Resources

🚦 Testing

How did you test these changes?

 Testing pipeline
 Other method (describe)
 My changes can't be tested (explain why)
☑️ Checklist

 I requested two reviewers for this pull request
 I updated the documentation according to my changes
 I built the documentation by applying the build_docs label
Note: If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by andrewfullard** [comment]
Please update the relevant documentation for this change

**Comment by Knights-Templars** [comment]
> Please update the relevant documentation for this change

Done! Is this fine?

**Comment by wkerzendorf** [comment]
@Knights-Templars I don't see any documentation

**Comment by Knights-Templars** [comment]
I have added docstrings. Thanks @andrewfullard for noticing.

**Comment by Knights-Templars** [comment]
> @Knights-Templars I don't see any documentation

Thanks. Added now.

**Pull request merged**
