### PR TITLE
added units to test_simulation.py

### PR DESCRIPTION
**Pull request by mishinma**
I just added some units to tests in test_simulation.py. This seems to resolve the issue #478

### CODE REVIEW

**Comment by yeganer** [comment]
I'm fine with that change and i think we should use `assert_quantity_allclose` whenever possible.

@wkerzendorf @unoebauer Any comments? If you are fine i think we should merge.

**Comment by mishinma** [comment]
Do we need to pass `atol=0.0` in every assert statement? Its default value is 0 already. 
And when providing atol value to `assert_quantity_allclose` one must specify units because of the implementation in Astropy:
```
if atol is None:
        # by default, we assume an absolute tolerance of 0
        atol = u.Quantity(0)
    else:
        atol = u.Quantity(atol, subok=True, copy=False)
        try:
            atol = atol.to(actual.unit)
        except u.UnitsError:
            raise u.UnitsError("Units for 'atol' ({0}) and 'actual' ({1}) "
                               "are not convertible"
                               .format(atol.unit, actual.unit))

```

**Comment by unoebauer** [comment]
Looks very good - thanks for the effort @mishinma.

I am wondering, though, if (maybe for future reference) it would make more sense to generate a proper reference data set, containing quantities instead of bare numpy arrays. Thoughts on this, @wkerzendorf, @yeganer?

**Comment by wkerzendorf** [comment]
@unoebauer - yes it would make sense to do this, however it's not clear how to store those. But for now we are merging this.

**Pull request merged**
