### PR TITLE
Feature request: add virtual-packet-logging option to run_tardis()

### LINKED ISSUE #1356: Add virtual_packet_logging option to run_tardis()
Current way (after merging numba) is to specify this option in the configuration file. Considering visualization tools we're developing, it'll be more convenient if user can set this option during run-time instead of adding/removing it again & again from their configuration file.

### PR DESCRIPTION
**Pull request by yuyizheng1112**
## Description

This PR is to resolve #1356.
## Motivation and Context

The virtual packet data is not enabled by default. Currently, we have to enable `virtual_packet_logging` by editing the configuration file to use visualization tools that require virtual packet data. Although offering instruction in the documentation can partly solve the problem, it is still inconvenient to edit configuration file every time.

The new feature allows us to enable `virtual_packet_logging` option while running TARDIS simulation by setting the parameter `virtual_packet_logging=True`. The default value of the parameter is `False`. Meanwhile, it still supports specifying the option in configuration files.
## How Has This Been Tested?
- [x] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

## Screenshots (if appropriate):
The output of `virt_packet_last_interaction_type` indicates whether the packet has been enabled.
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [ ] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by andrewfullard** [comment]
Thank you for this contribution! Please look at the results of failing checks and adjust appropriately. In particular, apply `black` formatting and add a docstring that informs the user of the new virtual packet logging option.

**Comment by yuyizheng1112** [comment]
> Thank you for this contribution! Please look at the results of failing checks and adjust appropriately. In particular, apply `black` formatting and add a docstring that informs the user of the new virtual packet logging option.

Thanks for your kind reminder. I made some additions to the docstring and reformatted the files. Please review my work.

**Review by andrewfullard — APPROVED** [review]

**Review by jaladh-singhal — APPROVED** [review]
@yuyizheng1112 this looks good. Just to make sure everything is alright, can you post output of `sim.runner.virt_logging` for both cases?

**Comment by yuyizheng1112** [comment]
> @yuyizheng1112 this looks good. Just to make sure everything is alright, can you post output of `sim.runner.virt_logging` for both cases?

I've post the screenshot of new output. Please review it :)

**Pull request merged**
