### PR TITLE
Convergence plots Demo [Do Not Merge]

### PR DESCRIPTION
**Pull request by atharva-2001**
This PR aims to share a demo of convergence plots to be made for TARDIS.
Please see: https://github.com/tardis-sn/tardis/pull/1636

**Description**

**Motivation and context**

**How has this been tested?**
- [ ] Testing pipeline.
- [ ] Other. 

**Examples**
[Link](https://nbviewer.jupyter.org/github/atharva-2001/tardis/blob/convergence_plots_demo/docs/using/visualization/cplots_combined.ipynb) to view the combined plots as plotly subplots
[Link](https://nbviewer.jupyter.org/github/atharva-2001/tardis/blob/convergence_plots_demo/docs/using/visualization/cplots_vbox.ipynb) to convergence plots with Vbox. 
[Link](https://atharva-2001.github.io/tardis/branch/convergence_plots_demo_docs/using/visualization/cplots_vbox) to the above convergence plot notebook in the documentation

**Type of change**

- [ ] Bug fix. 
- [X] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [ ] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Review by jaladh-singhal — COMMENTED** [review]
The VBox solution looks great (moving iterations legends to above) but it affected the alignment of top & bottom plots' rightmost edge which was fine in combined plots. Maybe you can delve into CSS and reduce the width of above plot in a calculated way that alignment looks fine.

Also, I was thinking that VBox solution won't render in html notebooks, so sticking with combined plot (plotly sublot) will be more beneficial since it will render fine. Can you please search if plotly allows creating 2 legend boxes - then we can confine height of iterations' legend and scroll down won't happen.

And, can you give different colors to next boundary temperature and residual luminosity?

**Comment by jaladh-singhal** [comment]
Also I noticed plot labels were not present and dots were present in luminosity plots (that we decided to remove) - I hope you'll fix that since you showed us plot with these changes right?

**Comment by jaladh-singhal** [comment]
And one last thing - the 1st cell which widens entire notebook shouldn't be done. By default 1200px width of jupyter notebook should be respected because as per design principles, our eyes can only see that much width in one glance. This is the very reason many websites you see out there have content horizontally centered and confined in fixed width on desktop screens (leaving empty space on both left & right ends).

And you also need not to constraint height of vbox to 1000px - plotly plots are smart enough to adapt according to space available to them so let them be.

**Comment by atharva-2001** [comment]
Thanks for reviewing it! 
I'm afraid plotly only allows one legend per graph at the moment. ([Link](https://community.plotly.com/t/plotly-subplots-with-individual-legends/1754) to the discussion). I did however find a workaround, pinning the right margin of the plasma plot to 135, almost aligns the plots perfectly, but if someone changes the width of the cell, the plots move from the perfect alignment just a little bit. 
I'm sorry for changing the width of the cell to 100%, I had done that to take a screenshot :)

I found a way to show the plots on nbviewer as well in the documentation, but I did it by suppressing errors that showed up. 
[Here is the link](https://atharva-2001.github.io/tardis/branch/convergence_plots_demo_docs/using/visualization/cplots_vbox) to the documentation I built to show the plots. 
[Here is the link](https://nbviewer.jupyter.org/github/atharva-2001/tardis/blob/convergence_plots_demo/docs/using/visualization/cplots_vbox.ipynb) to the notebook on nbviewer.
If you are not able to view the plots, please try [this link](https://nbviewer.jupyter.org/github/atharva-2001/tardis/blob/192a5472f9a2e89f6d2d9cf9240b92508d841462/docs/using/visualization/cplots_vbox.ipynb), as the notebook was probably not updated.

**Pull request closed without merging**
