### PR TITLE
Update TARDIS environment after replacing PyNE

### LINKED ISSUE #1895: system pickle overriden
@epassaro you are messing with numba using this method - see https://github.com/numba/numba/issues/7807

https://github.com/tardis-sn/tardis/blob/c70594674b4e0998f3ea8a349911c1096e877331/tardis/__init__.py#L26

Can we fix this?

### LINKED ISSUE #1940: Update black version to fix  `cannot import name '_unicodefun' from 'click'` error
See issue here:

https://github.com/psf/black/issues/2964

and here:

https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click

Fix: update `black` version or pin `click` version`

### PR DESCRIPTION
**Pull request by epassaro**
**Description**

Changes to dependencies:

- `python` -> 3.8 (3.9 requires upgrading `pandas`, discuss)
- `astropy` -> 4 (v3 requires `python`<=3.7, v5 is also available, should we try?)
- `pickle5` -> removed (protocol v5 is available in `python>=3.8` , backporting is not required anymore)
- `jupyter` -> changed to `notebook` (no Qt deps required)
- `matplotlib` -> changed to `matplotlib-base` (no Qt deps required)
- `pyside2`/`pyqt` -> removed (if you want to use the Qt GUI install it manually, add procedure to docs)
- `Jinja=3.0.3` -> removed (bug fixed upstream)
- `docutils=0.16` -> removed (bug fixed upstream)
- `dot2tex` -> remove from `pip` section, use the `conda-forge` version (requires `python>=3.8)
- `black` -> 22.3 (Fix #1940, see also #1946)

Changes to code:

- Fix testing pipeline (`mamba` is broken) and disable warnings in `setup.cfg` (remove before merging)
- Replace [deprecated functions](https://astropy-astrofrog.readthedocs.io/en/latest/modeling/blackbody_deprecated.html) `blackbody_lambda` and `blackbody_nu` with `Blackbody` (required `astropy=4`) - [see here](https://docs.astropy.org/en/v4.0.x/whatsnew/4.0.html#api-changes-in-astropy-modeling)
- Fix `np.histogram` calls related to `astropy.units` (can't convert `dimensionless` -> `Hz` or vice-versa) - [see here](https://docs.astropy.org/en/v4.0.x/whatsnew/4.0.html#major-improvements-in-compatibility-of-quantity-objects-with-numpy-functions)
- Changes to GUI code (incomplete, required by `pyqt` and `pyside2`)
- Import constants from `tardis` in `opacities.py`
- Remove `pickle5` backport from `__init__.py` - Fix #1895
- Pin constants used by `astropy.units` to `codata2014` and `iau2012` (required to pass tests).

To do:
- Provide instructions to install dependencies for the Qt GUI in the documentation.

**Motivation and context**

After merging the long-awaited #1813 we can update the environment. PyNE was holding Python version, and consequently, other packages too.

**How has this been tested?**
- [x] Testing pipeline.
- [ ] Other. 

**Examples**

**Type of change**

- [ ] Bug fix. 
- [ ] New feature. 
- [x] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [x] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/contributing/development/documentation_guidelines.html#sharing-the-built-documentation-in-your-pr-documentation-preview).
- [ ] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Comment by andrewfullard** [comment]
See issue #1958 regarding mamba. May need to be a separate PR.

**Comment by epassaro** [comment]
> See issue #1958 regarding mamba. May need to be a separate PR.

Yes, that's why the description says:

```
- Fix testing pipeline (mamba is broken) and disable warnings in setup.cfg (remove before merging)
```

**Comment by epassaro** [comment]
Finally, I know what's going on with `constant` and all the tests pass now. However, we should discuss what we need to do in the close future.

The way we pin `astropy.constants` to version 1.3 through `tardis.constants` module was described in the [Astropy v3 documentation](https://astropy-cjhang.readthedocs.io/en/latest/constants/#collections-of-constants-and-prior-versions), but [changed in v4](https://docs.astropy.org/en/stable/constants/index.html#collections-of-constants-and-prior-versions).

Seems that `astropy.units` has some circular dependency with `astropy.constants`. To make this PR pass without changing the reference data I needed to patch `__init__.py` and pin the constants to Astropy v3.

Then, we have mixed constants: `astropy.units` is using v3, while when import `constants` from `tardis.constants` module we're using v1.3. Notice this was happening from the beginning, this PR just discovered this.

What should we do in the future?

**Comment by wkerzendorf** [comment]
@epassaro is this a draft PR - or ready got merge

**Pull request merged**
