### PR TITLE
Test added in test_atomic.py file

### PR DESCRIPTION
**Pull request by vaibhav4595**
test function for read_lines_data() in atomic.py added to test_atomic.py

### CODE REVIEW

**Comment by vaibhav4595** [comment]
@wkerzendorf Please do review it whenever free. Will add a few more tests to the same after this seems to be a go ahead

**Comment by wkerzendorf** [comment]
please rebase on the new master

**Comment by vaibhav4595** [comment]
@wkerzendorf Seemed to have some problems with the forked repo, now have corrected it...do have a look at it

**Comment by vaibhav4595** [comment]
@wkerzendorf Do have a look at it whenever free. Will add more tests to this after this is a go ahead

**Comment by wkerzendorf** [comment]
it does look good.

**Comment by vaibhav4595** [comment]
@wkerzendorf is it up to the standards to be merged ?

**Comment by wkerzendorf** [comment]
we merged somethings in the beginning, but for now we'll just let them stand so that we can use them in the evaluation. Some students started testing the same function, and we want to evaluate both (so we don't want to merge either one of them).

**Comment by vaibhav4595** [comment]
@wkerzendorf Can I continue adding tests to this same PR ?

**Comment by wkerzendorf** [comment]
We will get your application, that will contain links to your PRs (you need to put them in there) and then we will have a look after the student deadline on the 23rd of March. It is customary to open a new PR for each set of changes (not for every little change, but for a group of changes - like it is done in the right way in this PR). does that explain it?

**Comment by vaibhav4595** [comment]
@wkerzendorf Thank You. Sure it does

**Pull request closed without merging**
