### PR TITLE
[WIP] Enable full tests for Formal Integral

### LINKED ISSUE #1465: Formal integral tests needed for interpolate_shells: > 0
As demonstrated through the bug from issue #1463, we need tests of the formal integral that also cover the case where "interpolate_shells > 0".

### PR DESCRIPTION
**Pull request by aribalam**
## Description

Fixes #1465.
The PR reintroduces tests for Formal Integrals which was apparently disabled earlier due to a memory problem.

**Note: The PR for updating reference data has been merged in the `tardis-refdata` repository**

## How Has This Been Tested?
- [ ] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by andrewfullard** [comment]
I recommend running the local test pipeline to determine the cause of test failures. Glancing at the logs it appears that data required for the test are not available in the test HDF file (a storage of the test data).

**Comment by aribalam** [comment]
@andrewfullard I think the problem lies here in the [comment](https://github.com/tardis-sn/tardis/issues/1465#issuecomment-803442645).
The test HDF file is not available as it is not getting generated due to the error mentioned [here](https://github.com/tardis-sn/tardis/issues/1465#issuecomment-802823554).
I can commit the changes as mentioned in the first link to my comment above and check if its working.

**Comment by andrewfullard** [comment]
Please do. Thanks for the work on this

**Comment by aribalam** [comment]
The tests are still failing due to the fact that the `unit_test_data.h5` that the azure pipeline is referring to has not been updated with the current `tardis-refdata` repository. This is because these tests are passing locally on my machine.
I came across an azure pipeline `update-refdata.yml` (link [here](https://github.com/epassaro/tardis/blob/ea1a89c18d800e82b6add8f0e1693d4db6e42a7d/azure-pipelines/update-refdata.yml)) that seems to achieve the said task. 
Maybe @epassaro can help on this?

**Comment by epassaro** [comment]
I'll take a look.

**Comment by epassaro** [comment]
As you can see in the [Azure repo history](https://dev.azure.com/tardis-sn/TARDIS/_git/tardis-refdata?_a=history) the commit hash is exactly the same as the latest `tardis-refdata`.

**Comment by aribalam** [comment]
@epassaro That clears everything. 
One more thing. When the tests are run using `python setup.py test --args="--tardis-refdata=<refdata dir>"`. The result comes out to be different than what we get here. 
The test results are as follows - 

```
============================================================================ short test summary info =============================================================================
FAILED tardis/montecarlo/tests/test_packet_source.py::test_bb_packet_sampling - assert False
FAILED tardis/simulation/tests/test_simulation.py::test_plasma_estimates[nu_bar_estimator] - AssertionError: Series are different
FAILED tardis/simulation/tests/test_simulation.py::test_plasma_estimates[j_estimator] - AssertionError: Series are different
FAILED tardis/simulation/tests/test_simulation.py::test_plasma_estimates[t_radiative] - AssertionError: Series are different
FAILED tardis/simulation/tests/test_simulation.py::test_plasma_estimates[dilution_factor] - AssertionError: Series are different
FAILED tardis/simulation/tests/test_simulation.py::test_plasma_estimates[output_nu] - AssertionError: Series are different
FAILED tardis/simulation/tests/test_simulation.py::test_plasma_estimates[output_energy] - AssertionError: Series are different
FAILED tardis/simulation/tests/test_simulation.py::test_plasma_state_iterations[iterations_w] - AssertionError: DataFrame.iloc[:, 0] (column name="0") are different
FAILED tardis/simulation/tests/test_simulation.py::test_plasma_state_iterations[iterations_t_rad] - AssertionError: DataFrame.iloc[:, 0] (column name="0") are different
FAILED tardis/simulation/tests/test_simulation.py::test_plasma_state_iterations[iterations_electron_densities] - AssertionError: DataFrame.iloc[:, 0] (column name="0") are dif...
FAILED tardis/simulation/tests/test_simulation.py::test_plasma_state_iterations[iterations_t_inner] - AssertionError: Series are different
FAILED tardis/tests/test_tardis_full.py::TestRunnerSimple::test_j_blue_estimators - AssertionError: 
FAILED tardis/tests/test_tardis_full.py::TestRunnerSimple::test_spectrum - AssertionError: 
FAILED tardis/tests/test_tardis_full.py::TestRunnerSimple::test_virtual_spectrum - AssertionError: 
FAILED tardis/tests/test_tardis_full_formal_integral.py::TestRunnerSimpleFormalInegral::test_j_blue_estimators[-1-downbranch] - KeyError: 'No object named test_runner_simple_i...
FAILED tardis/tests/test_tardis_full_formal_integral.py::TestRunnerSimpleFormalInegral::test_spectrum[-1-downbranch] - KeyError: 'No object named test_runner_simple_integral_d...
FAILED tardis/tests/test_tardis_full_formal_integral.py::TestRunnerSimpleFormalInegral::test_spectrum_integrated[-1-downbranch] - KeyError: 'No object named test_runner_simple...
FAILED tardis/tests/test_tardis_full_formal_integral.py::TestRunnerSimpleFormalInegral::test_j_blue_estimators[30-downbranch] - KeyError: 'No object named test_runner_simple_i...
FAILED tardis/tests/test_tardis_full_formal_integral.py::TestRunnerSimpleFormalInegral::test_spectrum[30-downbranch] - KeyError: 'No object named test_runner_simple_integral_d...
FAILED tardis/tests/test_tardis_full_formal_integral.py::TestRunnerSimpleFormalInegral::test_spectrum_integrated[30-downbranch] - KeyError: 'No object named test_runner_simple...
FAILED tardis/tests/test_tardis_full_formal_integral.py::TestRunnerSimpleFormalInegral::test_j_blue_estimators[30-macroatom] - KeyError: 'No object named test_runner_simple_in...
FAILED tardis/tests/test_tardis_full_formal_integral.py::TestRunnerSimpleFormalInegral::test_spectrum[30-macroatom] - KeyError: 'No object named test_runner_simple_integral_ma...
FAILED tardis/tests/test_tardis_full_formal_integral.py::TestRunnerSimpleFormalInegral::test_spectrum_integrated[30-macroatom] - KeyError: 'No object named test_runner_simple_...
FAILED tardis/tests/test_tardis_full_formal_integral.py::TestRunnerSimpleFormalInegral::test_j_blue_estimators[-1-macroatom] - KeyError: 'No object named test_runner_simple_in...
FAILED tardis/tests/test_tardis_full_formal_integral.py::TestRunnerSimpleFormalInegral::test_spectrum[-1-macroatom] - KeyError: 'No object named test_runner_simple_integral_ma...
FAILED tardis/tests/test_tardis_full_formal_integral.py::TestRunnerSimpleFormalInegral::test_spectrum_integrated[-1-macroatom] - KeyError: 'No object named test_runner_simple_...
====================================================== 26 failed, 1177 passed, 207 skipped, 6 xpassed in 206.84s (0:03:26) =======================================================
```

I was expecting the results to be the same as the one we get here using `pytest tardis --tardis-refdata=...`. Am I missing something?

**Comment by epassaro** [comment]
I think using `pytest tardis ...` requires installing the package with `python setup.py develop` but I'm not sure.

**Comment by andrewfullard** [comment]
I believe `python setup.py test` is deprecated.

**Comment by aribalam** [comment]
@epassaro @andrewfullard I have updated the reference data and opened a PR in the refdata repository (link [here]()https://github.com/tardis-sn/tardis-refdata/pull/41). Let me know if anything else is required!

**Comment by andrewfullard** [comment]
For some reason, a manual re-run of the tests is not working (Azure seems to have lost the test run) so if you make a commit to this branch it should trigger them again

**Review by andrewfullard — APPROVED** [review]

**Pull request merged**
