### PR TITLE
[GSoC] Import and store NNDC deposition data - First Objective

### PR DESCRIPTION
**Pull request by shreyas3156**
### :pencil: Description

**Type:** :sun_with_face: GSoC

This is a submission completing the first objective of the Project "Import and store NNDC deposition data" for GSoC '23.

This notebook allows one to enter a Nuclide and the ENSDF data is downloaded into a JSON Format. 

### :pushpin: Resources

[2023 Ideas Page](https://tardis-sn.github.io/gsoc_2023/ideas/)
[NNDC Radlist](https://www.nndc.bnl.gov/radlist/)
[Decay Radiation Search](https://www.nndc.bnl.gov/nudat3/indx_dec.jsp)

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [x] Other method (describe)
- [ ] My changes can't be tested (explain why)

Entered the Nuclide name and verified the download of the corresponding JSON file.

### :ballot_box_with_check: Checklist

- [x] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by atharva-2001** [comment]
Thank you @shreyas3156 for creating the pull request! Would you mind writing tests for the functions you wrote? Also, if you could make the JSON data presentable- ideally in some pandas dataframe, it would be great!

**Comment by shreyas3156** [comment]
> Thank you @shreyas3156 for creating the pull request! Would you mind writing tests for the functions you wrote? Also, if you could make the JSON data presentable- ideally in some pandas dataframe, it would be great!

@atharva-2001 Thank you for the review. I am onto making the modifications you suggested.

**Comment by andrewfullard** [comment]
Well done! This is an excellent completion of the first objective. Just so you are aware, the work will be conducted in the Carsus repository https://github.com/tardis-sn/carsus so you should familiarise yourself with its documentation and installation. Please begin writing your application and message your draft to me privately on gitter!

**Comment by shreyas3156** [comment]
> Well done! This is an excellent completion of the first objective. Just so you are aware, the work will be conducted in the Carsus repository https://github.com/tardis-sn/carsus so you should familiarise yourself with its documentation and installation. Please begin writing your application and message your draft to me privately on gitter!

Thank you for the encouraging words! I will now begin familiarizing myself with the Carsus repository and subsequently prepare a draft of my approach to the project.

**Pull request closed without merging**
