### PR TITLE
addressing the issue caused by relative file path

### PR DESCRIPTION
**Pull request by not4win**
Addressing issue #962 . As relative filepath to tardis refadata causes problems, making the user to use only absolute filepath to tardis-refdata seems to solve the problem

### CODE REVIEW

**Comment by marxwillia** [comment]
This is good, but we also need to check that the unit tests always use absolute paths.  Can you go through them and verify that they use absolute paths, and fix them where relative paths are used?

**Comment by not4win** [comment]
Can we assume all the files are in tardis-master folder? Then the fix is pretty easy.

**Comment by not4win** [comment]
So now, when the user enters absolute filepath, well and good! For relative filepath, it adds the current working directory to the relative filepath to get the absolute filepath

**Comment by wkerzendorf** [comment]
@not4win tests and documentation would be great

**Comment by orbitfold** [comment]
Could you please write a test that demonstrates the issue that your fix fixes. It has to fail before your changes and pass after basically.

**Comment by not4win** [comment]
Okay I ran the tests on my laptop and it worked fine. I'll use one simple testing framework on azure pipelines and display the results(take screenshot) over here.

**Comment by not4win** [comment]
So the command used:
pytest tardis --tardis-refdata=tardis-refadata-master/

The test results:
tardis/io/tests/test_HDFWriter.py ...............                        [  1%]
tardis/io/tests/test_ascii_readers.py ....                               [  1%]
tardis/io/tests/test_atomic.py .....                                     [  1%]
tardis/io/tests/test_config_reader.py ..                                 [  1%]
tardis/io/tests/test_configuration_namespace.py .........                [  2%]
tardis/io/tests/test_csvy_reader.py ....                                 [  2%]
tardis/io/tests/test_decay.py ..                                         [  2%]
tardis/io/tests/test_model_reader.py ......                              [  3%]
tardis/model/tests/test_base.py ........................                 [  5%]
tardis/model/tests/test_csvy_model.py .......                            [  5%]
tardis/model/tests/test_density.py ..                                    [  5%]
tardis/montecarlo/tests/test_base.py ...........                         [  6%]
tardis/montecarlo/tests/test_cmontecarlo.py ............................ [  8%]
...................ssssss..............x................................ [ 13%]
............s                                                            [ 14%]
tardis/montecarlo/tests/test_formal_integral.py .......s................ [ 16%]
........                                                                 [ 17%]
tardis/montecarlo/tests/test_packet_source.py F                          [ 17%]
tardis/montecarlo/tests/test_spectrum.py ............................... [ 19%]
..                                                                       [ 19%]
tardis/plasma/tests/test_complete_plasmas.py ........................... [ 21%]
........................................................................ [ 26%]
........................................................................ [ 31%]
........................................................................ [ 37%]
........................................................................ [ 42%]
........................................................................ [ 47%]
........................................................................ [ 52%]
........................................................................ [ 57%]
........................................................................ [ 63%]
........................................................................ [ 68%]
........................................................................ [ 73%]
........................................................................ [ 78%]
.........................................                                [ 81%]
tardis/plasma/tests/test_hdf_plasma.py ................................. [ 84%]
.......                                                                  [ 84%]
tardis/plasma/tests/test_plasma_vboundary.py FFFFFFFFFFFFF               [ 85%]
tardis/plasma/tests/test_plasmas_full.py EEEE                            [ 85%]
tardis/plasma/tests/test_tardis_model_density_config.py ..               [ 86%]
tardis/simulation/tests/test_simulation.py EEEEEEEEEEEE                  [ 86%]
tardis/tests/test_tardis_full.py EEEE                                    [ 87%]
tardis/tests/test_tardis_full_formal_integral.py EEEEEEEEEEEE            [ 88%]
tardis/tests/test_util.py .............................................  [ 91%]
tardis/tests/integration_tests/test_integration.py sssssssssssssssssssss [ 92%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 98%]
sssssssssssssssssssssssssss                                              [100%]

As you can see: bunch of errors! All coz of this:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tardis/simulation/base.py:442: in from_config
    atom_data=kwargs.get('atom_data', None))
tardis/plasma/standard_plasmas.py:77: in assemble_plasma
    atom_data = AtomData.from_hdf(atom_data_fname)
tardis/io/atom_data/base.py:154: in from_hdf
    fname = resolve_atom_data_fname(fname)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

fname = 'tardis/plasma/tests/data/tardis-refdata-master/atom_data/kurucz_cd23_chianti_H_He.h5'

**Comment by not4win** [comment]
After the changes, the test results:
tardis/io/tests/test_HDFWriter.py ...............                        [  1%]
tardis/io/tests/test_ascii_readers.py ....                               [  1%]
tardis/io/tests/test_atomic.py .....                                     [  1%]
tardis/io/tests/test_config_reader.py ..                                 [  1%]
tardis/io/tests/test_configuration_namespace.py .........                [  2%]
tardis/io/tests/test_csvy_reader.py ....                                 [  2%]
tardis/io/tests/test_decay.py ..                                         [  2%]
tardis/io/tests/test_model_reader.py ......                              [  3%]
tardis/model/tests/test_base.py ........................                 [  5%]
tardis/model/tests/test_csvy_model.py .......                            [  5%]
tardis/model/tests/test_density.py ..                                    [  5%]
tardis/montecarlo/tests/test_base.py ...........                         [  6%]
tardis/montecarlo/tests/test_cmontecarlo.py ............................ [  8%]
...................ssssss..............x................................ [ 13%]
............s                                                            [ 14%]
tardis/montecarlo/tests/test_formal_integral.py .......s................ [ 16%]
........                                                                 [ 17%]
tardis/montecarlo/tests/test_packet_source.py F                          [ 17%]
tardis/montecarlo/tests/test_spectrum.py ............................... [ 19%]
..                                                                       [ 19%]
tardis/plasma/tests/test_complete_plasmas.py ........................... [ 21%]
........................................................................ [ 26%]
........................................................................ [ 31%]
........................................................................ [ 37%]
........................................................................ [ 42%]
........................................................................ [ 47%]
........................................................................ [ 52%]
........................................................................ [ 57%]
........................................................................ [ 63%]
........................................................................ [ 68%]
........................................................................ [ 73%]
........................................................................ [ 78%]
.........................................                                [ 81%]
tardis/plasma/tests/test_hdf_plasma.py ................................. [ 84%]
.......                                                                  [ 84%]
tardis/plasma/tests/test_plasma_vboundary.py .............               [ 85%]
tardis/plasma/tests/test_plasmas_full.py FFFF                            [ 85%]
tardis/plasma/tests/test_tardis_model_density_config.py ..               [ 86%]
tardis/simulation/tests/test_simulation.py FFFFFFFFFF..                  [ 86%]
tardis/tests/test_tardis_full.py FFF.                                    [ 87%]
tardis/tests/test_tardis_full_formal_integral.py FFFFFFFFFFFF            [ 88%]
tardis/tests/test_util.py .............................................  [ 91%]
tardis/tests/integration_tests/test_integration.py sssssssssssssssssssss [ 92%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 98%]
sssssssssssssssssssssssssss                                              [100%]


As you can see: No errors!

**Comment by not4win** [comment]
Is there a need to run this on azure pipeline?

**Pull request closed without merging**
