### PR TITLE
Updated the quickstart example to show TARDIS flow graph

### PR DESCRIPTION
**Pull request by Chinmay4400**
updated the quickstart example to show TARDIS flow through a graph and completed the first objective for GSOC 2020 project idea "Visualizing TARDIS flow through a graph"

### CODE REVIEW

**Comment by marxwillia** [comment]
@Chinmay4400 You only added the checkpoint backup notebook, and there do not appear to be any changes.  Please remove anything in the .ipynb directory.  You should update the actual quickstart.ipynb notebook.

**Comment by marxwillia** [comment]
Thanks for the prompt response!  Please address the following comments:
 
1.  Please remove the .ipynb_checkpoints directory.
2.  I do not see the graph in your notebook, just the code to make the graph.  Please make the graph show up in the notebook.
3.  When I run the first cell to do the imports in your notebook, I get an error: `ModuleNotFoundError: No module named 'graphviz'` 

Does this import work for you?  Did you install any new packages to the tardis conda env?
4.  If you have created a separate file for the graph, add it to the PR.

**Comment by Chinmay4400** [comment]
Would it be alright if I write the pip installs for graphviz in the jupyter notebook itself?

**Comment by marxwillia** [comment]
No, if you need new packages, they need to be added to the tardis_env yml file.

**Pull request closed without merging**
