### PR TITLE
Test added in test_atomic.py

### PR DESCRIPTION
**Pull request by vaibhav4595**
Functional test for read_levels_data() in the atomic.py file

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@orbitfold travis doesn't seem to run for some reason?

**Comment by vaibhav4595** [comment]
@wkerzendorf shall I try closing this and issuing it again ?

**Comment by wkerzendorf** [comment]
@vaibhav4595 maybe try closing and reissuing it.

**Comment by vaibhav4595** [comment]
@wkerzendorf seems to be building now

**Comment by vaibhav4595** [comment]
@wkerzendorf travis build has now passed for this

**Comment by vaibhav4595** [comment]
@wkerzendorf Please do review it whenever free :). I am interested in adding a few more tests to the same once this accomplices with the specifications and manner.

**Comment by wkerzendorf** [comment]
I think that looks fine. We can merge and you can open another one.

**Pull request merged**
