### PR TITLE
Resurrect Integration Tests

### PR DESCRIPTION
**Pull request by unoebauer**
This PR updates various config and python files such that the integration test suite can be run locally. In a next step (future PR), the integration tests will be integrated as a cron job into the Travis continuous integration process.

Verify the following features
- [x] reference generation and validation with few packets
- [ ] reference generation and validation with high statistics
- [x] local reporting
- [ ] (*optional*) remote reporting

### CODE REVIEW

**Comment by unoebauer** [comment]
@wkerzendorf - I can now successfully run the integration tests locally on my machine. For now I've tested the following features:
- generate the reference with ``--less-packets``
- test against this reference value (again with ``--less-packets``)
- produce the html report

Not yet tested:
- remote reporting (not sure this is necessary for the Travis CI process)
- run test suite with large statistics, i.e. without ``--less-packets`` (this should be tried before merging, I think)

**Comment by unoebauer** [comment]
@wkerzendorf - I am really at a loss here - the command for starting the integration tests works flawlessly on my machine but fails on Travis.

On my laptop:
```
python setup.py test --args="--integration=/home/ulrich/Work/Astrophysical_Codes/tardis/integration/integration.yml -m integration --less-packets"
/home/ulrich/miniconda2/envs/tardis_new/lib/python2.7/site-packages/matplotlib/style/core.py:197: UserWarning: In /home/ulrich/.config/matplotlib/stylelib/538_cols.mplstyle: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(message)
tardis/plasma/setup_package.py:2: RuntimeWarning: Parent module 'tardis.plasma' not found while handling absolute import
  from setuptools import Extension
tardis/plasma/setup_package.py:3: RuntimeWarning: Parent module 'tardis.plasma' not found while handling absolute import
  from astropy_helpers.setup_helpers import get_distutils_option
tardis/plasma/setup_package.py:4: RuntimeWarning: Parent module 'tardis.plasma' not found while handling absolute import
  import numpy as np
tardis/montecarlo/setup_package.py:2: RuntimeWarning: Parent module 'tardis.montecarlo' not found while handling absolute import
  from setuptools import Extension
tardis/montecarlo/setup_package.py:3: RuntimeWarning: Parent module 'tardis.montecarlo' not found while handling absolute import
  import numpy as np
tardis/montecarlo/setup_package.py:4: RuntimeWarning: Parent module 'tardis.montecarlo' not found while handling absolute import
  import os
tardis/montecarlo/setup_package.py:5: RuntimeWarning: Parent module 'tardis.montecarlo' not found while handling absolute import
  from astropy_helpers.setup_helpers import get_distutils_option
tardis/montecarlo/setup_package.py:6: RuntimeWarning: Parent module 'tardis.montecarlo' not found while handling absolute import
  from Cython.Build import cythonize
tardis/montecarlo/setup_package.py:8: RuntimeWarning: Parent module 'tardis.montecarlo' not found while handling absolute import
  from glob import glob
tardis/simulation/setup_package.py:2: RuntimeWarning: Parent module 'tardis.simulation' not found while handling absolute import
  from setuptools import Extension
tardis/simulation/setup_package.py:3: RuntimeWarning: Parent module 'tardis.simulation' not found while handling absolute import
  from astropy_helpers.setup_helpers import get_distutils_option
tardis/simulation/setup_package.py:4: RuntimeWarning: Parent module 'tardis.simulation' not found while handling absolute import
  import numpy as np
Freezing version number to tardis/version.py
running test
running build
running build_py
copying tardis/version.py -> build/lib.linux-x86_64-2.7/tardis
copying tardis/tests/integration_tests/test_integration.py -> build/lib.linux-x86_64-2.7/tardis/tests/integration_tests
copying tardis/_compiler.c -> build/lib.linux-x86_64-2.7/tardis
copying tardis/plasma/properties/util/macro_atom.c -> build/lib.linux-x86_64-2.7/tardis/plasma/properties/util
copying tardis/montecarlo/montecarlo.c -> build/lib.linux-x86_64-2.7/tardis/montecarlo
copying tardis/tests/integration_tests/paper1_downbranch/config.yml -> build/lib.linux-x86_64-2.7/tardis/tests/integration_tests/paper1_downbranch
copying tardis/tests/integration_tests/w7/config.yml -> build/lib.linux-x86_64-2.7/tardis/tests/integration_tests/w7
copying tardis/tests/integration_tests/paper1_scatter/config.yml -> build/lib.linux-x86_64-2.7/tardis/tests/integration_tests/paper1_scatter
copying tardis/tests/integration_tests/at/config.yml -> build/lib.linux-x86_64-2.7/tardis/tests/integration_tests/at
copying tardis/tests/integration_tests/paper1_macroatom/config.yml -> build/lib.linux-x86_64-2.7/tardis/tests/integration_tests/paper1_macroatom
running build_ext
building 'tardis._compiler' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ulrich/miniconda2/envs/tardis_new/include/python2.7 -c tardis/_compiler.c -o build/temp.linux-x86_64-2.7/tardis/_compiler.o
gcc -pthread -shared -L/home/ulrich/miniconda2/envs/tardis_new/lib -Wl,-rpath=/home/ulrich/miniconda2/envs/tardis_new/lib,--no-as-needed build/temp.linux-x86_64-2.7/tardis/_compiler.o -L/home/ulrich/miniconda2/envs/tardis_new/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/tardis/_compiler.so
cythoning tardis/plasma/properties/util/macro_atom.pyx to tardis/plasma/properties/util/macro_atom.c
building 'tardis.plasma.properties.util.macro_atom' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ulrich/miniconda2/envs/tardis_new/lib/python2.7/site-packages/numpy/core/include -I/home/ulrich/miniconda2/envs/tardis_new/include/python2.7 -c tardis/plasma/properties/util/macro_atom.c -o build/temp.linux-x86_64-2.7/tardis/plasma/properties/util/macro_atom.o -W -Wall -Wmissing-prototypes -std=c99 -Wp,-w -Wno-unused-function
gcc -pthread -shared -L/home/ulrich/miniconda2/envs/tardis_new/lib -Wl,-rpath=/home/ulrich/miniconda2/envs/tardis_new/lib,--no-as-needed build/temp.linux-x86_64-2.7/tardis/plasma/properties/util/macro_atom.o -L/home/ulrich/miniconda2/envs/tardis_new/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/tardis/plasma/properties/util/macro_atom.so
cythoning tardis/montecarlo/montecarlo.pyx to tardis/montecarlo/montecarlo.c
building 'tardis.montecarlo.montecarlo' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Itardis/montecarlo -Itardis/montecarlo/src -Itardis/montecarlo/src/randomkit -I/home/ulrich/miniconda2/envs/tardis_new/lib/python2.7/site-packages/numpy/core/include -I/home/ulrich/miniconda2/envs/tardis_new/include/python2.7 -c tardis/montecarlo/montecarlo.c -o build/temp.linux-x86_64-2.7/tardis/montecarlo/montecarlo.o -W -Wall -Wmissing-prototypes -std=c99 -Wp,-w -Wno-unused-function
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Itardis/montecarlo -Itardis/montecarlo/src -Itardis/montecarlo/src/randomkit -I/home/ulrich/miniconda2/envs/tardis_new/lib/python2.7/site-packages/numpy/core/include -I/home/ulrich/miniconda2/envs/tardis_new/include/python2.7 -c tardis/montecarlo/src/rpacket.c -o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/rpacket.o -W -Wall -Wmissing-prototypes -std=c99 -Wp,-w -Wno-unused-function
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Itardis/montecarlo -Itardis/montecarlo/src -Itardis/montecarlo/src/randomkit -I/home/ulrich/miniconda2/envs/tardis_new/lib/python2.7/site-packages/numpy/core/include -I/home/ulrich/miniconda2/envs/tardis_new/include/python2.7 -c tardis/montecarlo/src/integrator.c -o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/integrator.o -W -Wall -Wmissing-prototypes -std=c99 -Wp,-w -Wno-unused-function
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Itardis/montecarlo -Itardis/montecarlo/src -Itardis/montecarlo/src/randomkit -I/home/ulrich/miniconda2/envs/tardis_new/lib/python2.7/site-packages/numpy/core/include -I/home/ulrich/miniconda2/envs/tardis_new/include/python2.7 -c tardis/montecarlo/src/cmontecarlo.c -o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/cmontecarlo.o -W -Wall -Wmissing-prototypes -std=c99 -Wp,-w -Wno-unused-function
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Itardis/montecarlo -Itardis/montecarlo/src -Itardis/montecarlo/src/randomkit -I/home/ulrich/miniconda2/envs/tardis_new/lib/python2.7/site-packages/numpy/core/include -I/home/ulrich/miniconda2/envs/tardis_new/include/python2.7 -c tardis/montecarlo/src/randomkit/rk_mt.c -o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/randomkit/rk_mt.o -W -Wall -Wmissing-prototypes -std=c99 -Wp,-w -Wno-unused-function
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Itardis/montecarlo -Itardis/montecarlo/src -Itardis/montecarlo/src/randomkit -I/home/ulrich/miniconda2/envs/tardis_new/lib/python2.7/site-packages/numpy/core/include -I/home/ulrich/miniconda2/envs/tardis_new/include/python2.7 -c tardis/montecarlo/src/randomkit/rk_sobol.c -o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/randomkit/rk_sobol.o -W -Wall -Wmissing-prototypes -std=c99 -Wp,-w -Wno-unused-function
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Itardis/montecarlo -Itardis/montecarlo/src -Itardis/montecarlo/src/randomkit -I/home/ulrich/miniconda2/envs/tardis_new/lib/python2.7/site-packages/numpy/core/include -I/home/ulrich/miniconda2/envs/tardis_new/include/python2.7 -c tardis/montecarlo/src/randomkit/rk_isaac.c -o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/randomkit/rk_isaac.o -W -Wall -Wmissing-prototypes -std=c99 -Wp,-w -Wno-unused-function
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Itardis/montecarlo -Itardis/montecarlo/src -Itardis/montecarlo/src/randomkit -I/home/ulrich/miniconda2/envs/tardis_new/lib/python2.7/site-packages/numpy/core/include -I/home/ulrich/miniconda2/envs/tardis_new/include/python2.7 -c tardis/montecarlo/src/randomkit/rk_primitive.c -o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/randomkit/rk_primitive.o -W -Wall -Wmissing-prototypes -std=c99 -Wp,-w -Wno-unused-function
gcc -pthread -shared -L/home/ulrich/miniconda2/envs/tardis_new/lib -Wl,-rpath=/home/ulrich/miniconda2/envs/tardis_new/lib,--no-as-needed build/temp.linux-x86_64-2.7/tardis/montecarlo/montecarlo.o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/rpacket.o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/integrator.o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/cmontecarlo.o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/randomkit/rk_mt.o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/randomkit/rk_sobol.o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/randomkit/rk_isaac.o build/temp.linux-x86_64-2.7/tardis/montecarlo/src/randomkit/rk_primitive.o -L/home/ulrich/miniconda2/envs/tardis_new/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/tardis/montecarlo/montecarlo.so
copying tardis/cython_version.py -> build/lib.linux-x86_64-2.7/tardis
running build_scripts
=============================================================================================== test session starts ================================================================================================
```

On Travis:
```
$ CC=$COMPILER python setup.py $SETUP_CMD
tardis/plasma/setup_package.py:2: RuntimeWarning: Parent module 'tardis.plasma' not found while handling absolute import
  from setuptools import Extension
tardis/plasma/setup_package.py:3: RuntimeWarning: Parent module 'tardis.plasma' not found while handling absolute import
  from astropy_helpers.setup_helpers import get_distutils_option
tardis/plasma/setup_package.py:4: RuntimeWarning: Parent module 'tardis.plasma' not found while handling absolute import
  import numpy as np
tardis/montecarlo/setup_package.py:2: RuntimeWarning: Parent module 'tardis.montecarlo' not found while handling absolute import
  from setuptools import Extension
tardis/montecarlo/setup_package.py:3: RuntimeWarning: Parent module 'tardis.montecarlo' not found while handling absolute import
  import numpy as np
tardis/montecarlo/setup_package.py:4: RuntimeWarning: Parent module 'tardis.montecarlo' not found while handling absolute import
  import os
tardis/montecarlo/setup_package.py:5: RuntimeWarning: Parent module 'tardis.montecarlo' not found while handling absolute import
  from astropy_helpers.setup_helpers import get_distutils_option
tardis/montecarlo/setup_package.py:6: RuntimeWarning: Parent module 'tardis.montecarlo' not found while handling absolute import
  from Cython.Build import cythonize
tardis/montecarlo/setup_package.py:8: RuntimeWarning: Parent module 'tardis.montecarlo' not found while handling absolute import
  from glob import glob
tardis/simulation/setup_package.py:2: RuntimeWarning: Parent module 'tardis.simulation' not found while handling absolute import
  from setuptools import Extension
tardis/simulation/setup_package.py:3: RuntimeWarning: Parent module 'tardis.simulation' not found while handling absolute import
  from astropy_helpers.setup_helpers import get_distutils_option
tardis/simulation/setup_package.py:4: RuntimeWarning: Parent module 'tardis.simulation' not found while handling absolute import
  import numpy as np
Freezing version number to tardis/version.py
Compiling tardis/montecarlo/montecarlo.pyx because it changed.
[1/1] Cythonizing tardis/montecarlo/montecarlo.pyx
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: option -m not recognized
The command "CC=$COMPILER python setup.py $SETUP_CMD" exited with 1.
after_failure
0.01s$ cat /home/travis/.pip/pip.log
```

**Note**:
```
$ echo CC=$COMPILER python setup.py $SETUP_CMD
CC=gcc python setup.py test --args="--integration=/home/travis/tardis-refdata/integration/integration_lesspackets_travis.yml -m integration --less-packets"
```

**Comment by unoebauer** [comment]
Any ideas, @wkerzendorf ?

**Comment by wkerzendorf** [comment]
@unoebauer haven't had a chance to check. I'm maybe trying circle CI as astropy has moved there. 

We'll see.

**Comment by wkerzendorf** [comment]
to be continued in #887

**Pull request closed without merging**
