### PR TITLE
Modified intensity_black_body to use numba

### PR DESCRIPTION
**Pull request by Phantsure**
## Description

- Imported `njit` from `numba`.
- Removed `numexp` in ordered to use `numba` properly

## Motivation and Context

This should make the function a lot faster 
## How Has This Been Tested?

Tested using cProfile. Results as follows
Screenshot_2020-02-29 Screenshot from 2020-02-29 22-53-23 png (PNG Image, 1920 × 1080 pixels) - Scaled (84%)
This shows performance increase with fastmath. Results for others also shown.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Phantsure** [comment]
From the previous PRs by shreyansjain012 and others, I have understood that it is not just this function to improve but others too for overall improvement. Just did this PR to tell that I am also trying to work on this.

**Comment by Phantsure** [comment]
@wkerzendorf I saw the montecarlo_numba branch for help in this. I think i have achieved faster results. Not so fast, but better than before.

**Comment by Phantsure** [comment]
why is a ZeroDivisionError being thrown? Is it automatically handled when not using fastmath?

**Comment by epassaro** [comment]
Numba can handle exceptions in two ways. Read the numba documentation!

**Comment by Phantsure** [comment]
> Numba can handle exceptions in two ways. Read the numba documentation!

Thanks for this.

**Comment by epassaro** [comment]
The Numba documentation gives you a better, straightforward solution. Read it again.

**Comment by Phantsure** [comment]
numba documentation currently supports try...except in limited form, i.e. for python >3.7 but tardis can run on only python >=3.6 and <3.7

**Comment by Phantsure** [comment]
okay, used a better way. Thanks @epassaro

**Comment by marxwillia** [comment]
Find other functions to optimize using profiling.

**Comment by Phantsure** [comment]
@marxwillia tardis.plasma.properties.util.macro_atom.calculate_transition_probabilities(0.250 sec) seems to take time the most after montecarlo(30+sec). But comparatively it is very less. Still should i continue with transitions probabilities?

**Comment by lukeshingles** [comment]
> numba currently supports try...except in limited form, i.e. for python >3.7 but tardis can run on only python==3.6.x, limited due to pyne

I have tardis running on Python 3.7 but I had to build PyNE from the develop branch.

**Pull request closed without merging**
