### PR TITLE
Shell Info Widget demo for new TARDIS GUI

### PR DESCRIPTION
**Pull request by jaladh-singhal**
This PR demonstrates the prototype for new GUI for TARDIS using Jupyter Widgets.

> Note: Don't merge this PR, it is only for demonstration purpose. The code produced here will be integrated in tardis codebase only after the prototypes become complete and a proper structure for new GUI subpackage is decided.

# Interfaces to implement
## Shell Info
- [x] Interconnected tables (shells and abundances)
- [x] Model parameters in a new tab
- [ ] Name elements & Ion species
- [ ] Shell vs Density plot
- [ ] Shell vs Rad. Temp plot
- [ ] Make iterations visible
- [ ] Spaghetti plot for shell abundances

## Others
- [ ] Line Info
- [ ] New interfaces

More (future) features to be added can be tracked in [this project board](https://github.com/tardis-sn/tardis/projects/5).

### CODE REVIEW

**Comment by jaladh-singhal** [comment]
There are a few bugs in Qgrid (the table widget package that we're using) though they are being handled by workarounds I came up with and they're not breaking our GUI so far! 

Moreover I have opened issues for them which can be traked at [qgrid#316](https://github.com/quantopian/qgrid/issues/316) and [qgrid#320](https://github.com/quantopian/qgrid/issues/320).

**Comment by wkerzendorf** [comment]
are we closing this?

**Comment by jaladh-singhal** [comment]
@wkerzendorf If you think so, we can!

**Comment by jaladh-singhal** [comment]
A new widgets sub-package containing Shell Info widget (as of now) based on prototype of this PR has been implemented by PR #1166. It can be closed and referred to in future - when requiring past ideas/options to improve shell info widget.

**Pull request closed without merging**
