### PR TITLE
Clumping Project

### PR DESCRIPTION
**Pull request by JSmyth94**
Changes to the montecarlo and io sections to add a random element of whether or not a packet is in a "cloud" of material or in the "intercloud medium", and adjust the tau sobolev accordingly.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@JSmyth94 very nice! Those are big changes to the code, so maybe we want to skype on this. @ssim what do you think?

**Comment by ssim** [comment]
@wkerzendorf Would be good to Skype with you sometime, yes. I'll need to make time to take a look first though (=not today). Do we know why the Travis build fails?

**Comment by wkerzendorf** [comment]
@ssim there are some problems with the full run. @JSmyth94 do you know how to see where the TRAVIS build fails?

**Comment by JSmyth94** [comment]
@wkerzendorf @ssim Problems with the TRAVIS build have been fixed, just problems with how the code dealt with YAML files missing the clumping data. All resolved now.

**Comment by ssim** [comment]
@JSmyth94 @wkerzendorf That's great - good job on the TRAVIS stuff. Once Wolfgang and I have had a chance to look through this perhaps we can have a Skype in the next couple of days.

**Comment by wkerzendorf** [comment]
@JSmyth94 How are things progressing. Have you had a chance to think about tests? Let me know if there's anything I can do to help.

**Comment by JSmyth94** [comment]
@wkerzendorf I have been mainly focusing on getting the theory together for the report side of my project, so I haven't had much of a chance to consider tests yet. I am hoping to get started on them in the next week or two, so I will let you know if I could use any advice. Thanks!

**Pull request closed without merging**
