### PR TITLE
Changing way of simulation display results by logger

### PR DESCRIPTION
**Pull request by parikshit14**
Having a first glance at the logger output, it seemed very confusing and verbose, though I haven't changed the verbosity (already updated in PR: #1514 ) but have changed the way result(logger result) were displayed.

## Description

1. Installed a new library _TableLogger_ using `pip install table-logger` (version=0.3.6)
2. Added **display_type** as an argument to function `run_tardis()` with which, one can choose what kind of display they want for _Plasma Stratification_.
- 0 -> using normal logger
- 1 -> dataframe kind of log table
- 2 -> using TableLogger
[default=0]

## Motivation and Context

These changes are for visualization purpose and help the end-user to understand the simulation results well. Earlier the logger was more crowded, it seemed very confusing and verbose, this PR solves that problem a bit.

## How Has This Been Tested?
- [ ] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [x] Other (please describe)
1. Results are present in `tardis/docs/quickstart/test_logger_display.ipynb`, so basically it is tested only on the quickstart guide provided.
2. The above-mentioned file was executed in the tardis virtual environment which had was updated a bit (`pip install table-logger` (version=0.3.6))
3. Changes done, are included in some function calls as well as in function headers.
4. Also added _\n_ here and there to make it look better.
 

## Screenshots (if appropriate):
normal/default display:

dataframe kind of log table:

using TableLogger:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (~~fix~~ or feature that ~~would~~ may cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [x] I have assigned and requested two reviewers for this pull request

@jamesgillanders @MarkMageeAstro @marxwillia kindly review this PR

### CODE REVIEW

**Comment by parikshit14** [comment]
I have installed a new library is that the reason why the tests are failing?

**Comment by MarkMageeAstro** [comment]
I don't know about the tests, but I like the changes to the output you've made. Can you add comments to the code to explain everything that's going?

**Comment by parikshit14** [comment]
Added comments for better understanding and readability to all modifications in the repository

**Comment by aribalam** [comment]
@parikshit14 @MarkMageeAstro The tests are failing a necessary argument has been added `display_type` into the `run()` function. The tests are using the old version of `run()` function, and hence are failing.
@parikshit14 You might want to add `display_type` as a keyword argument (with a default set to 0 by looking at your logic) so that the `run()` function could also be invoked without any arguments.

**Comment by aribalam** [comment]
@parikshit14 Also I would recommend you to open Pull Requests from a non-master branch. It is the general practice.

**Comment by parikshit14** [comment]
> @parikshit14 Also I would recommend you to open Pull Requests from a non-master branch. It is the general practice.

Thanks for the suggestion, I'll keep this in mind next time.

**Comment by parikshit14** [comment]
@MarkMageeAstro kindly have a look at the changes which helped to pass the tests. If any improvements needed kindly suggest them as well.

**Comment by MarkMageeAstro** [comment]
Looks good to me, I don't have any further comments

**Comment by parikshit14** [comment]
added two basic convergence plot in the simulation results namely:
1. Temperature VS Shell 
2. Dilution factor VS Shell
with respect to iterations(1-19)

Temperature VS Shell
Dilution factor VS Shell

**Comment by parikshit14** [comment]
@MarkMageeAstro can you please review the changes ?

**Comment by MarkMageeAstro** [comment]
It would be good if the colours were based on a map, rather than just random. That way there's a progression from the first to last iteration and it's immediately obvious from looking at it.

**Pull request closed without merging**
