### PR TITLE
Tests added in test_util

### PR DESCRIPTION
**Pull request by imjalpreet**
Tests added for function species_tuple_to_string.

### CODE REVIEW

**Comment by imjalpreet** [comment]
@wkerzendorf, I have added a Test for the function species_tuple_to_string. Please tell if something is missing.

**Comment by kaushik94** [comment]
This is wrong. Take a look at #233  and #234

**Comment by wkerzendorf** [comment]
@kaushik94 it's not wrong, it's outdated - @imjalpreet for now you should use pytests parametrize

**Comment by imjalpreet** [comment]
@wkerzendorf, Can you give me an example of a parametrize pytest?

**Pull request closed without merging**
