### PR TITLE
Remove integration tests

### PR DESCRIPTION
**Pull request by KasukabeDefenceForce**
### :pencil: Description

**Type:** :beetle: `bugfix` | :rocket: `feature` | :biohazard: `breaking change` | :vertical_traffic_light: `testing` | :memo: `documentation` | :roller_coaster: `infrastructure`

This PR removes the outdated  integration tests.

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by andrewfullard** [comment]
Can you check that the configuration yml files are stored in https://github.com/tardis-sn/tardis-setups ?

**Comment by KasukabeDefenceForce** [comment]
> Can you check that the configuration yml files are stored in https://github.com/tardis-sn/tardis-setups ?

I dont think its there. Should I create a new dir and copy only the config files in that repo?

**Comment by andrewfullard** [comment]
> > Can you check that the configuration yml files are stored in https://github.com/tardis-sn/tardis-setups ?
> 
> I dont think its there. Should I create a new dir and copy only the config files in that repo?

Yes, make sure these configurations are stored there in some form.

**Comment by KasukabeDefenceForce** [comment]
> > > Can you check that the configuration yml files are stored in https://github.com/tardis-sn/tardis-setups ?
> > 
> > 
> > I dont think its there. Should I create a new dir and copy only the config files in that repo?
> 
> Yes, make sure these configurations are stored there in some form.

https://github.com/tardis-sn/tardis-setups/pull/22

**Review by andrewfullard — DISMISSED** [review]

**Review by andrewfullard — APPROVED** [review]

**Review by wkerzendorf — APPROVED** [review]

**Pull request merged**
