### PR TITLE
Completed task for TARDIS Setups Framework

### PR DESCRIPTION
**Pull request by anirudhprabhakaran3**
Completed the initial task for GSoC entitled "TARDIS Setups Framework"

## Description

Completed the initial task for GSoC entitled "TARDIS Setups Framework" by running the 30d.yml file from tardis_setups

## Motivation and Context

This is the initial task required for the above mentioned project for TARDIS at Google Summer of Code (GSoC)

## How Has This Been Tested?
- [ ] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

## Screenshots (if appropriate):
30d

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by anirudhprabhakaran3** [comment]
The simulation has been run, and a screenshot has been taken after making changes to the .yml file. I had asked on Gitter what I could do because the original settings were taking very long to run, and I was suggested to change the number of threads and the number of packets.

**Comment by andrewfullard** [comment]
Can you adjust the plot so it is easier to read the spectrum? Currently there is a lot of empty space in the plot.

**Comment by anirudhprabhakaran3** [comment]
> Can you adjust the plot so it is easier to read the spectrum? Currently there is a lot of empty space in the plot.

Yeah sure. Should I just add a screenshot or should I push the modified Jupyter Notebook too?

**Comment by anirudhprabhakaran3** [comment]
30d_1

Is this what was required?

**Review by andrewfullard — APPROVED** [review]

**Comment by andrewfullard** [comment]
Please write your application following the guidelines on the TARDIS GSOC page.

**Comment by anirudhprabhakaran3** [comment]
I have a few questions regarding the task. Should I ask them on the Gitter chat?

Also, where should I send a draft proposal for review?

**Pull request closed without merging**
