### PR TITLE
Small update of to_hdf5 for runner: Necessary for Kromer Plots

### PR DESCRIPTION
**Pull request by unoebauer**
This small PR adds ``last_interaction_type`` to ``to_hdf`` of the runner class. This is needed for making Kromer plots.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@unoebauer how does this relate to @vg3095 efforts?

**Comment by vg3095** [comment]
@unoebauer @wkerzendorf I have now added `last_interaction_type` in hdf_properties list (PR #748) .

**Comment by wkerzendorf** [comment]
@unoebauer this is outdated - right?

**Comment by unoebauer** [comment]
Yes! Closing

**Pull request closed without merging**
