### PR TITLE
Macro atom to numba

### PR DESCRIPTION
**Pull request by shreyansjain012**
Removed cython support and modified macro_atom to use numba 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by shreyansjain012** [comment]
@wkerzendorf I modified the macro_atom file to support numba and it does showing improved results
image

Build tests are failing so finding the problem

**Comment by shreyansjain012** [comment]
It seems like tests are still looking for macro_atom.pyx file

**Comment by wkerzendorf** [comment]
@shreyansjain012 have you run the tests locally?

**Comment by shreyansjain012** [comment]
Yes they are giving the same error

**Comment by shreyansjain012** [comment]
I am going through setup files and astropy_helper files to see where do I need to make the change, I think i need to modify the tests to not to look for macro_atom.pyx

**Pull request closed without merging**
