### PR TITLE
Updated widgets.py Changing all T's to temprature

### PR DESCRIPTION
**Pull request by pokwer**
**Description**
Updated widgets.py Changing all T's to temprature

**Motivation and context**
solving issue #1600 

**How has this been tested?**
- [ ] Testing pipeline.
- [x] Other. 

**Examples**

**Type of change**

- [x] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [x] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [ ] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Comment by andrewfullard** [comment]
Thanks for your first contribution! It looks like I need to clarify my issue, because the `T` I meant was the variable, not the labels on plots. Furthermore, you misspelled `Temperature` in your contribution.

**Comment by pokwer** [comment]
> Thanks for your first contribution! It looks like I need to clarify my issue, because the `T` I meant was the variable, not the labels on plots. Furthermore, you misspelled `Temperature` in your contribution.

can you tell me what files these variables are in so that I can change them?

**Comment by andrewfullard** [comment]
You should search the files to find them :)

**Comment by jaladh-singhal** [comment]
We no longer support `tardis/gui` since we now have `tardis/visulaization/widgets` for the same.

@andrewfullard should we close it?

**Pull request closed without merging**
