### PR TITLE
Added Verbosity option and Convergence Plot for Project: Notebook Logging Framework

### PR DESCRIPTION
**Pull request by Davidgokimmung**
## Description
Add a verbosity option that suppresses warnings by default but allows errors. Changes were made in base.py file by adding additional argument in run_simulation function (verbose). Default value of verbose is set to 0, which by default hides the warnings content, whereas when verbose is set to 1, it will show the warnings.

## Motivation and Context
When TARDIS is run, log output including warnings and other prints, are dumped to the standard output. This creates confusing messaging for the end user. So in order to reduce this confusion, the user should be provided with the choice to suppress warnings, but not errors.

## How Has This Been Tested?
- [ ] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [x] Other (please describe)

This feature is tested on tardis_example.yml file which by default shows warnings, but when verbose is set to 1 the warnings stay hidden.
- To hide the warnings: `sim = run_tardis('tardis_example.yml')` or `sim = run_tardis('tardis_example.yml', verbose=0)`
- To show the warnings: `sim = run_tardis('tardis_example.yml', verbose=1)`

## Screenshots (if appropriate):
-Verbose=0 _(By default)_ without warnings
FireShot Capture 031 - quickstart - Jupyter Notebook - localhost

-Verbose=1 showing warnings
FireShot Capture 028 - quickstart - Jupyter Notebook - localhost

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by andrewfullard** [comment]
Please give this PR a more descriptive name

**Comment by jamesgillanders** [comment]
PR looks good, and it resolves the issue

**Comment by Davidgokimmung** [comment]
> PR looks good, and it resolves the issue

Can you give me any other objective to look into for me to get more familiar with the project before I start writing my application proposal? That would be great.

**Comment by MarkMageeAstro** [comment]
Looks good to me. As for another objective, I think you can start looking into the plasma information (temperature, etc.) that's printed on the screen and think about how you might implement the convergence plots during the project.

**Comment by Davidgokimmung** [comment]
@andrewfullard @MarkMageeAstro @jamesgillanders I have added the convergence plot which will show live changes in the plot depending on the temperature and dilution factor values. 
It is working fine in Jupyter Notebook. Kindly have a look at it.

asd

**Comment by MarkMageeAstro** [comment]
When submitting commits, it would be good to give more unique titles so they're not all 'update base'. When you say it shows live changes, can you add a .gif or something to demonstrate?

**Comment by Davidgokimmung** [comment]
> When submitting commits, it would be good to give more unique titles so they're not all 'update base'. When you say it shows live changes, can you add a .gif or something to demonstrate?

**Comment by Davidgokimmung** [comment]
Sorry for the titles. I was trying to clear the check failures.

Here is a gif that demonstrates the convergence plot when I run the simulation.
Plot 1: Radiation Temperature vs Iteration
Plot 2: Dilution Factor vs Iteration

Using this method it is possible to create any plots as required.

convergence (1)

**Comment by Davidgokimmung** [comment]
@MarkMageeAstro I see that there is a TARDIS visualization tool (SDECPlotter). Should this convergence plot be incorporated with that tool or is it fine to visualize it separately?

**Comment by MarkMageeAstro** [comment]
Looks good, nice job. The convergence stuff should be separate from the sdec plotter but it will eventually be included as a visualisation tool

**Comment by Davidgokimmung** [comment]
@jamesgillanders @MarkMageeAstro @marxwillia I have added 2 more convergence plots namely:
1. Radiation Temperature vs. shell
2. Dilution factor vs. shell


chrome-capture (1) (1) (1)

**Comment by andrewfullard** [comment]
This looks good to me, if the other mentors agree I recommend you begin writing your application following the guidelines on the TARDIS GSoC website

**Pull request closed without merging**
