### PR TITLE
Fix typos in repository

### PR DESCRIPTION
**Pull request by AyushiDaksh**
### :pencil: Description

**Type:** :vertical_traffic_light: `testing`

Changed the name of the class from `TestRunnerSimpleFormalInegral` to `TestRunnerSimpleFormalIntegral`

### :vertical_traffic_light: Testing

How did you test these changes?

- [x] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [x] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

### CODE REVIEW

**Comment by atharva-2001** [comment]
@AyushiDaksh Thanks for creating this pull request! Would you mind finding where else there are typos in the code(programmatically)? I'd also suggest making progress with your first objective alongside these pull requests.

**Comment by AyushiDaksh** [comment]
@atharva-2001  sure, i'm working on it. Should i rename this pull request to a more general title like "fix typos in the codebase" ?

**Comment by AyushiDaksh** [comment]
@atharva-2001 While I was browsing the tools available to spell check, I stumbled upon this: https://github.com/marketplace/actions/github-spellcheck-action

In addition to fixing the current typos, should we add this to our pre-commit workflow going forward?

**Comment by atharva-2001** [comment]
What are the outputs of the workflow? Have you tried it running on TARDIS? What does it say?

**Review by ymatsumu — APPROVED** [review]

**Comment by sonachitchyan** [comment]
hey @AyushiDaksh ! can you rebase this or so that we can merge it?

**Review by Rodot- — DISMISSED** [review]

**Comment by AyushiDaksh** [comment]
@sonachitchyan Sorry I somehow missed this. I have rebased the changes now, you can go ahead and merge.
Thanks!

**Review by ymatsumu — APPROVED** [review]

**Comment by AyushiDaksh** [comment]
@andrewfullard Rebased this onto latest master now

**Comment by AyushiDaksh** [comment]
Now sure why the mailmap is failing even though I have added my credentials

**Review by ymatsumu — APPROVED** [review]

**Review by atharva-2001 — APPROVED** [review]

**Pull request merged**
