### PR TITLE
Added option for keyword arguments in the TardisSpectrum's plot method

### PR DESCRIPTION
**Pull request by aribalam**
## Description

This PR is a feature request to facilitate the option of adding keyword arguments to the `plot` function of the `TardisSpectrum` to provide more flexibility in plotting the spectrum using matplotlib.

## Motivation and Context

The current implementation of the `plot` function of `TardisSpectrum` does not provide any flexibility in plotting the spectrums.

For example, using the Tardis Example setup, the spectrum plot in normal packet mode can be plotted using below code - 

But in order to plot spectrums in different modes in the same figure with proper legends, the code is below - 

With this feature, the code reduces down to -

Similarly, more customizations can be made to the plots this way, just by adding the required keyword arguments in the function the way it is done in matplotlib.

## How Has This Been Tested?
- [x] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

## Screenshots (if appropriate):
Given in Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by aribalam** [comment]
@wkerzendorf @epassaro Could you review it please?

**Review by marxwillia — APPROVED** [review]
This is a good idea to add.

**Comment by epassaro** [comment]
probably this is on @jaladh-singhal side of the project

**Review by jaladh-singhal — APPROVED** [review]
@aribalam wow! very thoughtful :+1:

**Pull request merged**
