### PR TITLE
Use pytest's monkeypatch.chdir to change the working directory in the config_reader tests

### PR DESCRIPTION
**Pull request by ftsamis**
Following @yeganer's suggestion at https://github.com/tardis-sn/tardis/pull/543#issuecomment-216568575 and replacing the custom function in ``test_config_reader``, for temporarily changing the working directory in a test, with pytest's ``monkeypatch.chdir``.

### CODE REVIEW

**Comment by yeganer** [comment]
I think you could go even so far as to have one test function and parametrize it. I think you wouldn't need a class in that case.

**Comment by wkerzendorf** [comment]
@yeganer @ftsamis are we done here?

**Comment by ftsamis** [comment]
@yeganer Checked parametrize, and I think it would probably make sense to only use it for 2 of the 3 functions, since the one with the absolute path has slightly different behaviour (no `monkeypatch`).

If you don't insist on using parametrize, I'd say we can merge this @wkerzendorf.

**Comment by wkerzendorf** [comment]
@yeganer @ftsamis looks good - signing off.

**Comment by yeganer** [comment]
Actually I'd use parametrize because the functionality is the same in all 3 functions.
```
@pytest.parametrize(['.', '..', os.path.abs(os.cwd())])
```
something like this.
That would make it very obvious what's happening.
@wkerzendorf If you don't share my opinion, you can merge. The rest looks good.

**Comment by wkerzendorf** [comment]
@ftsamis I agree with @yeganer. It's a quick change and will reduce the code. Will merge once this is in.

**Comment by wkerzendorf** [comment]
@ftsamis can you fix this?

**Comment by ftsamis** [comment]
@wkerzendorf I'm now working on it.
@yeganer The first two functions need to change working directory, and to have a relative path. The third doesn't need to change working directory but needs an absolute path. That's the slightly different behaviour I meant.

Anyhow, I'll use parametrize.

**Comment by wkerzendorf** [comment]
@yeganer what do you think?

**Comment by yeganer** [comment]
I think, I'm a bit nitpicking here but you could have the cwd as parameter for your function and then read the config two times, once with a relative path to the destination and once with an absolute path. That should cover everything and you don't have to do if/else in the test.

**Comment by ftsamis** [comment]
That sounds indeed better. Done.

**Comment by yeganer** [comment]
Thanks, that looks great.
@tardis-sn/tardis-core Ready to merge from my side.

**Pull request merged**
