### PR TITLE
Donot run docs, benchmarks and stardis tests on draft PRs.

### PR DESCRIPTION
**Pull request by KasukabeDefenceForce**
### :pencil: Description

**Type:** :beetle: `bugfix` | :rocket: `feature` | :biohazard: `breaking change` | :vertical_traffic_light: `testing` | :memo: `documentation` | :roller_coaster: `infrastructure`

This PR makes sure that the build docs, benchmarks and stardis tests are run on a PR which is ready for review.

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by KasukabeDefenceForce** [comment]
Sample PR to test the workflow:
https://github.com/KasukabeDefenceForce/tardis/pull/39

Sample Run:
https://github.com/KasukabeDefenceForce/tardis/pull/38

**Comment by andrewfullard** [comment]
Can we also trigger the actions when the PR changes from draft to ready? I think that is what @wkerzendorf wanted so that we don't forget the labels.

**Comment by KasukabeDefenceForce** [comment]
> Can we also trigger the actions when the PR changes from draft to ready? I think that is what @wkerzendorf wanted so that we don't forget the labels.

Yes I have shared a link to the PR on my fork. You can test it on that.

**Comment by andrewfullard** [comment]
> > Can we also trigger the actions when the PR changes from draft to ready? I think that is what @wkerzendorf wanted so that we don't forget the labels.
> 
> Yes I have shared a link to the PR on my fork. You can test it on that.

I can't mark the PR as ready for review on your fork but I do see the actions running.

**Comment by KasukabeDefenceForce** [comment]
> > > Can we also trigger the actions when the PR changes from draft to ready? I think that is what @wkerzendorf wanted so that we don't forget the labels.
> > 
> > 
> > Yes I have shared a link to the PR on my fork. You can test it on that.
> 
> I can't mark the PR as ready for review on your fork but I do see the actions running.

Oh I forgot about that, apologies. Yes, it is setup in a way that the tests will start after we shift it to ready for review.

**Review by andrewfullard — APPROVED** [review]

**Review by atharva-2001 — APPROVED** [review]

**Pull request merged**
