### PR TITLE
Restructure/detailed balance foundation

### PR DESCRIPTION
**Pull request by wkerzendorf**

### CODE REVIEW

**Comment by andrewfullard** [comment]
Tests rely on https://github.com/tardis-sn/tardis-regression-data/pull/24 merging first.

**Review by andrewfullard — APPROVED** [review]
I'm happy with this, but I have also done a lot of work on it so it needs other reviews.

**Review by jvshields — DISMISSED** [review]
As far as I can tell it looks fine, but it's always hard to tell with the restructure PRs which parts are renames or functional changes worth paying attention to, or are just files and functions being moved around to places that make more sense.

**Comment by andrewfullard** [comment]
> As far as I can tell it looks fine, but it's always hard to tell with the restructure PRs which parts are renames or functional changes worth paying attention to, or are just files and functions being moved around to places that make more sense.

In this case @jvshields I think the tests are most illustrative because we compare this new structure with the previous way(s) of doing things.

**Comment by andrewfullard** [comment]
Tests are now failing for a different but related reason. `electron_densities` seems to stick around in memory for too long. Unclear why.

**Review by andrewfullard — DISMISSED** [review]

**Pull request merged**
