### PR TITLE
Enabling Repository on Binder

### PR DESCRIPTION
**Pull request by smithis7**
This allows for the TARDIS repository to be built on binder, which will in turn allow for the running of TARDIS online.

You can see the binder built on my fork [here](https://mybinder.org/v2/gh/smithis7/tardis/2nd-binder-attempt).

**Type of change**

- [ ] Bug fix. 
- [x] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [x] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Review by epassaro — COMMENTED** [review]
- Is the `cd` command needed? If that's true, why not doing `cd ..`? It's unclear what's the `$HOME` dir for `binder` (it's difficult to track what's $HOME for every CI/CD service!). Using the latter it's more clear, the script is going to the parent directory before executing the command. 

- Try `install` instead of `develop`, it's preferred.

- Add a new blank line at the end of the file.

**Comment by smithis7** [comment]
> * Is the `cd` command needed? If that's true, why not doing `cd ..`? It's unclear what's the `$HOME` dir for `binder` (it's difficult to track what's $HOME for every CI/CD service!). Using the latter it's more clear, the script is going to the parent directory before executing the command.
> * Try `install` instead of `develop`, it's preferred.
> * Add a new blank line at the end of the file.

All of those changes have been made and binder still works! I seemingly overcomplicated the `cd` part.

**Review by epassaro — APPROVED** [review]

**Comment by epassaro** [comment]
@smithis7 

Are you interested in implementing a **binder** badge on the **nbsphinx** prolog like [this](https://nbsphinx.readthedocs.io/en/0.3.3/markdown-cells.html)?

I think it's better than have the **binder** badge on README.rst.

If you are interested, see their [`conf.py`](https://github.com/spatialaudio/nbsphinx/blob/master/doc/conf.py#L33).

**Comment by smithis7** [comment]
> @smithis7
> 
> Are you interested in implementing a **binder** badge on the **nbsphinx** prolog like [this](https://nbsphinx.readthedocs.io/en/0.3.3/markdown-cells.html)?
> 
> I think it's better than have the **binder** badge on README.rst.
> 
> If you are interested, see their [`conf.py`](https://github.com/spatialaudio/nbsphinx/blob/master/doc/conf.py#L33).

I actually have a few different ideas on this that are contingent on me getting a few packages working. For now I think we should leave `conf.py` as it is but possibly change it in the future.

**Review by andrewfullard — APPROVED** [review]

**Pull request merged**
