### PR TITLE
Add comparision of numba implementation to initialization doc

### PR DESCRIPTION
**Pull request by light2802**
### :pencil: Description

**Type:**  :memo: `documentation`

Created a version of planck_function() that is jit compiled by Numba and compared how long it takes to calculate planck_function(nus_planck) for the original function versus the jitted function for 100, 200, and 500 frequency bins.

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [x] Tested online on Binder

### :ballot_box_with_check: Checklist

- [x] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

### CODE REVIEW

**Review by smithis7 — COMMENTED** [review]
It looks really good!

This was not explicitly in the instructions, but one thing you may want to do is show the comparison via a loop -- i.e. instead of individually running the comparison for 100, 200, and 500 bins, write a loop that does all three.

You also recognized that the numba code is accelerated after compilation. Could you try not calling the function prior to running the comparison loop, and showing what happens?

**Comment by smithis7** [comment]
Looks great!

**Review by AlexHls — APPROVED** [review]

**Review by smithis7 — APPROVED** [review]

**Comment by atharva-2001** [comment]
Hi @light2802, thank you for the pull request! Have you started working on your proposal? I believe now is a good time to send us a draft!

**Comment by light2802** [comment]
Hi @atharva-2001, I have already started with the proposal. I have been discussing it with @smithis7

**Pull request closed without merging**
