### PR TITLE
Replace LegacyPlasmaArray with a function

### PR DESCRIPTION
**Pull request by ftsamis**
With this PR `LegacyPlasmaArray` is replaced with `assemble_plasma` which takes a `Configuration` object and a `Radial1DModel` (in the form it has in #632) and returns a `BasePlasma` instance.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@ftsamis should we merge this one?

**Comment by ftsamis** [comment]
@wkerzendorf Not yet, I'm doing some tests first.

**Comment by ftsamis** [comment]
**Note: It's not possible to initialize property classes with the current implementation. That is a problem for `LevelBoltzmannFactorNLTE` which needs to be instantiated.**

Details: https://gitter.im/tardis-sn/tardis?at=57a9f1f2f7f11a7936af6afc

**Comment by ftsamis** [comment]
Closing in favor of #652.

**Pull request closed without merging**
