### PR TITLE
Removing usage of yield in test_utils.py

### PR DESCRIPTION
**Pull request by kaushik94**
Please take a look at #233. Also added a test for `species_tuple_to_string`. @wkerzendorf  please take a look.

### CODE REVIEW

**Comment by kaushik94** [comment]
Works perfect now( with the fix also in #232 )
```
kaushik@ghost:~/Desktop/soc/tardis/tardis/tests$ py.test -q test_util.py
..................
18 passed in 0.69 seconds
```

**Comment by kaushik94** [comment]
@wkerzendorf  The test_utils.py doesn't work currently even if we plug in the wrong values, because of the usage of yield and I think this PR solves it. I think we should merge it before we make any major changes to the files. What do you think ?

**Comment by wkerzendorf** [comment]
@kaushik94 well done!

**Comment by kaushik94** [comment]
Thanks @wkerzendorf .

**Pull request merged**
