### PR TITLE
Fixing plasma in 41d8fcd (not for merging)

### PR DESCRIPTION
**Pull request by aoifeboyle**
Issue #455: 41d8fcd is the commit at which the plasma_restructure branch was originally merged with the Tardis master branch. Here I have fixed a couple of things to ensure the plasma results are consistent with those of 45eca24 (last working example). All of the plasma quantities (taus, transition_probabilities, etc.) now agree between this version and 45eca24. But the nubar_estimators are still wrong. I think this may be a view/copy issue. Someone who knows more about the C/Python interface needs to look at these parameters to see which are being transferred wrong.

### CODE REVIEW

**Comment by aoifeboyle** [comment]
@unoebauer I was planning to re-check my results from last night, but I messed something up with my conda environment when I was changing the pandas version to 0.16.0 to check for the error. Hopefully I'll get it fixed over the weekend...

**Comment by yeganer** [comment]
When i try to mdl.to_hdf5('file') with this PR i'm getting a
```
(<type 'exceptions.AttributeError'>, AttributeError("'LegacyPlasmaArray' object has no attribute 'ion_populations'",), <traceback object at 0x7f3ab4ffca70>)
```
Error. (I had to add additional info in the error handling block to see, what's really going on)
Is this a common problem with that state of the master branch or is this related to your fix?

**Comment by aoifeboyle** [comment]
@yeganer This was a problem with the original plasma/restructure merge that was fixed in later commits. I'm working on debugging the problem right now but later I can go back and add the fix to this version.

**Comment by yeganer** [comment]
@aoifeboyle don't worry adding the fix to this version. Since i'm not familiar with Panda Dataframes and HDF5 yet i'll do my debugging and comparing with binary dumps in the C part anyway.

**Comment by yeganer** [comment]
I did some more tests and found out that between 45eca24 and 41d8fcd the electron density changed only little. The change in electron density was fixed in d84d1f6 which brought the difference between 45eca24 and c1e1b97 below 1e-15.

@aoifeboyle : @unoebauer told me you found something which reduced the relative difference in your version to 1e-5? Can you please update your pull request so i can check if merging the PR with d84d1f6 solves the issue?

**Comment by aoifeboyle** [comment]
@yeganer That actually falls right in line with what I was thinking - that the electron density disparity had been fixed in a later PR (I was getting a difference that @unoebauer was not with the current master). I did find a fix for the transition probabilities yesterday that reduced the relative errors to below 1.e-5, and that was with a relative electron density error of about the same magnitude in my current version. I sent Uli instructions for how to implement my fix, did you get a chance to try it with the master version yet @unoebauer? Basically it was to substitute the following for the `Lines` module in tardis/plasma/properties/atomic.py @yeganer (you can also try it):

    class Lines(ProcessingPlasmaProperty):
            outputs = (‘lines’, ‘nu’, ‘f_lu’, ‘wavelength_cm’)
            def calculate(self, atomic_data):
                    return atomic_data.lines, atomic_data.lines.nu, atomic_data.lines.f_lu, atomic_data.lines.wavelength_cm

The master has changed so much since my version that I think just taking this and pasting it in would be much quicker than doing a full merge. I promised myself I'd focus on other work today, and I know if I start looking at the Tardis stuff again I won't come back to it, but please let me know what you find.

**Comment by yeganer** [comment]
@aoifeboyle Thanks for the code snippet. When i implemented that into d84d1f6 i got relative errors of 1e-13 which seems okay to me. However when implemented in the current master i got a relative error of 0.24.
I'm currently bisecting with your fix and trying to find the commit where the new error occured.

**Comment by aoifeboyle** [comment]
@yeganer You mean relative errors in the transition probabilities or the nubar estimators of 1e-13? And were other plasma quantities (e.g. t_rad, electron_densities) the same?

**Comment by unoebauer** [comment]
@yeganer: how about the transition probabilities? How big is their relative error? We always suspected that the nubar_estimator error may come from this. If we are now at the position that with @aoifeboyle 's fixes we get at least the transition probabilities right again, we made an important step into the right direction.

**Comment by yeganer** [comment]
@unoebauer i just created a new PR with only the fix inside. As i wrote there, as far as i can tell all plasma properties have a relative error below 1e-12 ( the maximum rel. error i found were the transition_probabilities with 9.1e-13)

**Comment by wkerzendorf** [comment]
@aoifeboyle can we close this - if yes .. please do.

**Comment by unoebauer** [comment]
@wkerzendorf : this was definitely a by-product of the #455 debugging process. The changes of the PR only involve a simple code refactoring (jblues -> jblues_array) and one formula change. The latter is already in the current master. Consequently, I'll close this PR.

**Pull request closed without merging**
