### PR TITLE
improved gh-pages

### PR DESCRIPTION
**Pull request by debajyotidasgupta**

### CODE REVIEW

**Comment by debajyotidasgupta** [comment]
I have made the required changes and the github page is up working fine as per your requirement.

**Comment by wkerzendorf** [comment]
this needs to live in the `docs/` and the PR should have some description.

**Comment by wkerzendorf** [comment]
and you need to merge it into master. things are built from master.

**Comment by wkerzendorf** [comment]
I'll merge this - but you need to fix this in master.

**Comment by debajyotidasgupta** [comment]
should I be making another pr for the merging in master?

**Comment by debajyotidasgupta** [comment]
i will take care of the description from next time
thank you

**Comment by wkerzendorf** [comment]
yes please make a PR to master and put this in `.docs`

**Pull request merged**
