### PR TITLE
Name plotly traces in SDEC plot

### PR DESCRIPTION
**Pull request by atharva-2001**
This PR names a few traces in plotly SDEC plot and makes some style changes to the hover text.
Because this helps me write SDEC tests too, this should be merged before the SDEC tests PR #1752.

**Description**

The traces displaying element contributions in plotly SDEC plot were not named earlier. This names those traces and the colour bar, with making some style changes to the hover text, to make it more clearly visible.

**Motivation and context**

https://github.com/tardis-sn/tardis/issues/1670
https://github.com/tardis-sn/tardis/pull/1752#discussion_r755251608

**How has this been tested?**
- [ ] Testing pipeline.
- [ ] Other. 

**Examples**

Before:
image

After:
image

**Type of change**

- [ ] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] I have assigned and requested two reviewers for this pull request.
- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).

### CODE REVIEW

**Review by jaladh-singhal — APPROVED** [review]
Thanks!

**Review by jamesgillanders — COMMENTED** [review]
Looks good! Can we do the rounding of the numbers in the hover box here or does it not belong in this PR?

**Comment by jamesgillanders** [comment]
How did you choose how to round the data? .4g is 4 significant figures right? That seems reasonable for the luminosity values, whereas .4f is 4 decimal places for the wavelength? this seems excessive - I would go for 1 d.p. for wavelength, and keep the luminosity as is

**Comment by atharva-2001** [comment]
I'm sorry I was about to ask this, I was not sure about the notation too- Plotly's `hovertemplate` uses's the [D3 format](https://github.com/d3/d3-format/blob/main/README.md#api-reference) underneath:

> f - fixed point notation.
g - either decimal or exponent notation, rounded to significant digits.


I would do just one decimal place for wavelength, but for luminosity, it by default displays 6 decimal places, is that alright as well?

**Comment by atharva-2001** [comment]
@MarkMageeAstro @jamesgillanders This is what it looks like at the moment. 
image

Does it look alright to you? I would build the documentation after PR https://github.com/tardis-sn/tardis/pull/1832 gets merged, for the meantime, maybe you can take a look at it on [Binder](https://mybinder.org/v2/gh/tardis-sn/tardis/HEAD?filepath=docs/io/visualization/sdec_plot.ipynb)?

**Comment by MarkMageeAstro** [comment]
Looks good to me.

**Review by jamesgillanders — APPROVED** [review]

**Pull request merged**
