### PR TITLE
Added objective notebook for Proposal - "TARDIS Setups Framework".

### PR DESCRIPTION
**Pull request by dhiganthrao**
## Description
This Pull request is for submission of the objective for the proposal, "TARDIS Setups Framework", mentored by Ezequiel Passaro and Andrew Fullard, in a Jupyter Notebook. It contains the simulation of a 30d model as provided in `tardis-setups` in [this link.](https://github.com/tardis-sn/tardis-setups)

## How Has This Been Tested?
- [ ] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

## Screenshots (if appropriate):
Spectrum of the Simulated Model:
image

SDEC Plot in "real" mode:
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by dhiganthrao** [comment]
@andrewfullard @epassaro would you mind reviewing this PR? Thanks!

**Comment by epassaro** [comment]
I think this looks good @dhiganthrao

**Comment by dhiganthrao** [comment]
@epassaro thank you! May I start working on the proposal now?

**Comment by andrewfullard** [comment]
> 
> 
> @epassaro thank you! May I start working on the proposal now?

Yes, you can work on your application following the guidelines on the TARDIS GSoC website

**Review by andrewfullard — APPROVED** [review]

**Pull request closed without merging**
