### PR TITLE
Plasma Graph Tutorial

### PR DESCRIPTION
**Pull request by bartnikm**
**Description**

This introduces a tutorial on how to plot the plasma graph within a jupyter notebook as well as saving it onto a .tex file 

**Motivation and context**

There is no current tutorial on the graph, and since it has different methods of saving the graph, this aims to show examples of different ways the graph can be displayed. 

**How has this been tested?**
- [ ] Testing pipeline.
- [ ] Other. 

**Examples**

https://bartnikm.github.io/tardis-bartnikm/branch/graph-tutorial_doc/physics/setup/plasma/index.html#the-plasma-graph
https://bartnikm.github.io/tardis-bartnikm/branch/graph-tutorial_doc/physics/setup/plasma/graph_tutorial.html

**Type of change**

- [ ] Bug fix. 
- [x] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [x] My change requires a change to the documentation.
    - [x] I have updated the documentation accordingly.
    - [x] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/contributing/development/documentation_guidelines.html#sharing-the-built-documentation-in-your-pr-documentation-preview).
- [ ] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Comment by andrewfullard** [comment]
Great work! Can you make a more "human readable" set of examples for the LaTeX plasma graph? The text is generally extremely small.

**Comment by smithis7** [comment]
Really nice -- I will have to get to a more thorough review later.

Just a quick thing to think about. This may belong in the "additional outputs" part of the "input/output" section of the docs, and just linked to in the plasma physics section. This is for two reasons: First, thematically this is an output of the simulation and not a part of the physics. Second, this is an important tutorial and I believe it belongs on the list of tutorials, which compiles notebooks in the "input/output" section of the docs.

Also, perhaps a title like "Generating the Plasma Graph" would be better, especially if it is moved to where I recommend.

This is just my opinion and someone else may have a more convincing argument for the notebook staying where it is.

**Review by andrewfullard — APPROVED** [review]
Looking much better, well done!

**Review by smithis7 — CHANGES_REQUESTED** [review]
This is a great PR. I hate to be so nit-picky but these are my comments/suggestions:

- In my opinion, the packages needed to generate the graph (i.e. networkx) should be added to the TARDIS environment.
- `Plasma_Graph_Default.tex` appears to be generated by the notebook and thus should not be in the repository and should be added to `.gitignore` (there is a section for notebook-generated files). The other generated files should also be added to `.gitignore`.
- All `tardis_example.yml` files should be symlinks of `docs/tardis_example.yml`.
- Is there a particular reason you use ipython to display images in addition to markdown HTML? All the images are shown twice. I typically prefer to use just markdown HTML, which would let you get rid of all the iframe stuff (including the import statement).
- This is a very small point, but for consistency we try to have all filenames be in snake case.
- Also very small, you should delete the empty code cell at the bottom of the notebook.
- Finally, take a look at my previous comment about the location of your notebook.

**Review by smithis7 — COMMENTED** [review]
Once you rebase and I check out the docs build I should be able to approve!
Edit: Sorry, I must have missed that you already did.

**Review by smithis7 — APPROVED** [review]
Awesome!

**Pull request merged**
