### PR TITLE
NF - running full test from comand line

### PR DESCRIPTION
**Pull request by Minhmo**
Added a pytest.mark.slow to run test from command line.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@Minhmo how will this be able to be switched on from the command line

**Comment by Minhmo** [comment]
@wkerzendorf adding "-m slow" to the py.test command. The whole command to run the full (slow) test would look like "py.test -m slow -q --atomic-dataset=<path to dataset>".

**Comment by wkerzendorf** [comment]
@mishinma sorry I should have clarified, it should normally not run these tests only with the commandline option. As far as I can tell - your code will always also run the slow tests. with the `-m slow` option only this test will be run. Have you tested it?

**Comment by mishinma** [comment]
@wkerzendorf you probably meant @Minhmo

**Comment by Minhmo** [comment]
@wkerzendorf full test can be excluded by adding -m "not slow". Yeah, I have just checked -m "not slow" and it automatically deselects full test.

**Comment by wkerzendorf** [comment]
@mishinma sorry wrong name. @Minhmo I want slow tests only if we specifically select them.

**Comment by orbitfold** [comment]
@Minhmo why did you close this? You don't have to close pull requests to respond to comments. If you want to make changes then pushing to your fork will update this pull request.

**Comment by Minhmo** [comment]
@orbitfold I just lost control, my bad. However, I opened a new pull request. Won't do this in future.

**Pull request closed without merging**
