### PR TITLE
Aggregate changes by tobychev

### PR DESCRIPTION
**Pull request by yeganer**
List of changes:

- [x] source function

- [ ] python formal integral

- [ ] c formal integral

### CODE REVIEW

**Comment by ftsamis** [comment]
This will probably need a rebase now.

**Comment by yeganer** [comment]
Yes, I agree.

**Comment by wkerzendorf** [comment]
@yeganer - this is outdated right? please close

**Comment by yeganer** [comment]
Changes merged through #724. Closing.

**Pull request closed without merging**
