### PR TITLE
First Objective Completed for Simulation Logging Framework

### PR DESCRIPTION
**Pull request by DhruvSondhi**
Generated the Log file from Simulation running on the default configuration of `tardis_example.yml`
## Description

The following Log file has been created with the default simulation & default `tardis_example.yml` with slight modification for debugging. Problem is that the `Wrapper` function is not working so everything in the Numba debug logging is also included. Modification for Logger module is evident & need some guidance for the same :)
## Motivation and Context

In relation to the Tardis GSOC 2021 idea list, Completes first objective of **Simulation Notebook Framework** 

## How Has This Been Tested?
- [ ] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [x] Other (please describe)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] None of the above (please describe)

## Checklist:

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by andrewfullard** [comment]
That's certainly a lot of output! Can you commit the changes you made to produce this output?

**Comment by DhruvSondhi** [comment]
Hello @andrewfullard, I made some changes to `montecarlo_logger.py` based on the Python Documentation. There is some problem with the decorator function or I am not understanding it correctly. I also tried running the decorator with some specific function but it was not generating the log ... returned the `wrapper object` but didn't produce the log that way, thus tried making the log through the `montecarlo_logger.py` instead 😄

**Comment by DhruvSondhi** [comment]
The majority of the log here show the **Numba** `DEBUG` logs ... I don't understand that getting the Numba logs is a good thing or a bad one but when we use something else (I have an example in a Jupyter notebook) I can generate all the logs thus produced in another file (was also able to generate the same thing through montecarlo_log.log file but needs some tinkering around to do that)

**Comment by DhruvSondhi** [comment]
Please do let me know if you able to reproduce the output or else I will commit the Jupyter Notebook as well :)

**Comment by andrewfullard** [comment]
Thanks for the info. Sadly most of the raw Numba debug information isn't particularly useful, though you've definitely completed the first objective of the project. I'm happy for you to start working on your application. For the project itself we intend for the debug information to primarily show function input/output and the states of the Packet objects.

**Review by andrewfullard — APPROVED** [review]

**Comment by DhruvSondhi** [comment]
Hello @andrewfullard, wish to Thank you for acknowledging my input. I initiate the process of completing my proposal as early as possible with your guidance & mentoring 😄

**Pull request closed without merging**
