### PR TITLE
Fix for automerge

### LINKED ISSUE #2157: Pre/post release automerge fails
**Describe the bug**
Auto merging the pre/post release PRs is not currently working due to upstream git action failures.

**To Reproduce**

Run the pre/post release workflows

### PR DESCRIPTION
**Pull request by epassaro**
### :pencil: Description

**Type:** :beetle: `bugfix` |  :roller_coaster: `infrastructure`

- Use the `gh` CLI to approve the pull request
- Use a new token `INFRASTRUCTURE_COORDINATOR_TOKEN` for first approval
- Add a second approval with `CORE_COORDINATOR_TOKEN`

Closes #2157

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [x] Other method (describe)
- [ ] My changes can't be tested (explain why)

Tested on a special repository:  https://github.com/epassaro/pr-automerge/pull/6

### :ballot_box_with_check: Checklist

- [x] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [x] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Review by andrewfullard — APPROVED** [review]
Thanks @epassaro this looks great

**Comment by andrewfullard** [comment]
It should probably be my token (the other being Wolfgang's?). How would I create that?

**Comment by epassaro** [comment]
> It should probably be my token (the other being Wolfgang's?). How would I create that?

You need to create your token [here]( https://github.com/settings/tokens), then copy it and create a new repository secret [here](https://github.com/tardis-sn/tardis/settings/secrets/actions) with an appropriate name according to your role.

Make sure to create a **classic token** with the correct scope.

**Comment by andrewfullard** [comment]
Created the PAT with the name "CORE_COORDINATOR_TOKEN"

**Review by andrewfullard — DISMISSED** [review]

**Review by andrewfullard — APPROVED** [review]

**Review by atharva-2001 — APPROVED** [review]

**Pull request merged**
