### PR TITLE
Revert "Move to qgridnext"

### PR DESCRIPTION
**Pull request by andrewfullard**
Reverts tardis-sn/tardis#2814.

Unfortunately qgridnext does not seem to resolve the issues with qgrid. Its pip install also makes our conda lock files very difficult to use.

### CODE REVIEW

**Comment by jaladh-singhal** [comment]
> Unfortunately qgridnext does not seem to resolve the issues with qgrid.

Do you mean issues regarding installation? Or issues in rendering widgets too? 

Because I tested latter and they worked. About the former, I built my environment from tardis_env3.yml, do we absolutely need to use conda lock files for visualization use cases?

**Comment by andrewfullard** [comment]
> > Unfortunately qgridnext does not seem to resolve the issues with qgrid.
> 
> @andrewfullard Do you mean issues regarding installation? Or issues in rendering widgets too?
> 
> Because I tested latter and they worked. About the former, I built my environment from tardis_env3.yml, do we absolutely need to use conda lock files for visualization use cases?

I created an environment and tested it on a jupyter server, and got the same Java errors as with qgrid. I can double check. Regardless, we have lock files because we want a reproducible environment, and that should extend to visualizations.

**Comment by andrewfullard** [comment]
I tested in VS Code with qgridnext and it appears to be working, which is great. However, it does fail on the *older* notebook server style ("classicnb") with the Java errors.

**Comment by andrewfullard** [comment]
After discussion- this is being closed in favour of a try-except clause in the import block of qgridnext

**Pull request closed without merging**
