### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by PIYUSHgoyal16**
This python script read in the tabulated data contained in "si2_osc_kurucz" in atomic data downloaded from http://kookaburra.phyast.pitt.edu/hillier/web/CMFGEN.htm. The script is well commented so as to assure the understanding of the code.

### CODE REVIEW

**Comment by marxwillia** [comment]
@PIYUSHgoyal16 looks good.  A few things to work on:

1.  Can you make your PR title more descriptive, and add a description of the work that you're doing? What is the purpose of the PR, what has been implemented, what will be implemented in the future, testing, etc.

2.  TARDIS contains some parsers for loading data.  Please make your script one of the parsers and document it according to the numpydocs style.

**Comment by PIYUSHgoyal16** [comment]
@marxwillia Thanks for the suggestions. The mistakes may be due to the fact that I am new to open source. Will definitely look for more descriptive titles, description, etc.
I will look for parser and document according to numpystyle docs :)

**Comment by epassaro** [comment]
@PIYUSHgoyal16 on the second table you have some issues with first and second columns, compare the beggining of the table and the bottom of it.

**Comment by PIYUSHgoyal16** [comment]
@marxwillia kindly view my PR and suggest the neccessary changes. Also @epassaro I have taken care of second table. That to in a generic manner allowing to use the same code on other files as well.

**Comment by epassaro** [comment]
It's not really generic, you hardcoded a lot of information. Also try to use `.read_csv()` parameters like `skiprows`, `nrows` and use less indexing. And please change the PR title!.

**Pull request closed without merging**
