### PR TITLE
Corrected csvy model files

### PR DESCRIPTION
**Pull request by antreev-brar**
This PR aims to correct the csvy files ```csvy_full.csvy``` and ```csvy_full_rad.csvy``` 

## Description
Changes made to the code are:
- Introduced the line ```model_isotope_time_0: 0 day```  in .csvy files

## Motivation and Context

When tardis model is simulated using the csvy format file examples provided in repository, it gives an error.  In the tardis/io/schemas/csvy_model.yml , it's description states:

 ```model_isotope_time_0:```
 ```   type: quantity```
 ```   description: Initial time for isotope decay. Set to 0 for no isotopes.```

Also, various other csvy files in the repository like ```tardis/tardis/model/tests/data/exponential_csvy.csvy ```and ```tardis/tardis/model/tests/data/uniform_csvy.csvy``` have these corrections.

## How Has This Been Tested?
- [x] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

I checked it by running unit tests on it with python setup.py test that gave the following output on my local machine.

- 156 passed, 1254 skipped, 6 xpassed in 7.80s

### Before the changes: 
Screenshot 2021-03-14 at 2 25 26 PM

 ### After the changes:
Screenshot 2021-03-14 at 2 31 29 PM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by andrewfullard** [comment]
Thanks for this fix!

**Review by andrewfullard — APPROVED** [review]

**Comment by marxwillia** [comment]
Thanks for fixing this!  Can you please clean up the commit history?  Since this is a very simple PR there should only be one commit.

**Comment by antreev-brar** [comment]
@marxwillia I have cleaned the commit history, can you review it?

**Comment by antreev-brar** [comment]
@marxwillia I have made the requested changes, can you review it?

**Pull request merged**
