### PR TITLE
First Objective Completed for Tardis Custom Abundance Widget Idea

### PR DESCRIPTION
**Pull request by DhruvSondhi**
## Description
This PR is in reference to the First objective completion for the Custom Abundance Widget Project Idea.

The current implementation is using the `tardis_challenge.csvy` CSVY model file to generate the required plot.

## Motivation and Context

This is for the reference of the challenge completion for the project idea.

## How Has This Been Tested?
- [ ] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [x] Other (please describe) ---> Tested Locally 

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] None of the above (please describe) : 

## Checklist:

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by jamesgillanders** [comment]
Take a look at what the units are for the velocity that is output by the TARDIS model... this plot suggests the ejecta velocity reaches 2e+9 km/s, which is ~7000 times larger than the speed of light!

**Comment by DhruvSondhi** [comment]
> Take a look at what the units are for the velocity that is output by the TARDIS model... this plot suggests the ejecta velocity reaches 2e+9 km/s, which is ~7000 times larger than the speed of light!

Yes sure ... Sorry I found the problem ... It was actually in (cm/s) but I was not able to push the commit ... Fixing it right away :)

**Comment by marxwillia** [comment]
Take a look at the y values of the data points that you are plotting.  What do you notice?

**Comment by DhruvSondhi** [comment]
Hello, @marxwillia , According to my understanding, the Y values are the fractional abundance of the respective elements. The Y is a function of X ie Abundance of the elements (each of them) with respect to the velocity of the shell expansion ... Abundance is a unitless quantity so I marked it as a ratio with respect to the full 1.0 part of the particular element ... I would change it to a fraction ... Please do let me know whether I am correct or wrong & Please correct me as needed 😄

**Comment by DhruvSondhi** [comment]
Hello, Please provide me with any other follow up challenge that may be satisfied from my side?  I hope I have fixed the issue with the Y-axis label :)

**Comment by andrewfullard** [comment]
Looks good to me

**Review by jaladh-singhal — COMMENTED** [review]
@DhruvSondhi Sorry for such delayed reply. This looks good but it'll be better if you can structure your plotting code into a module. Besides, can you reproduce this plot in plotly?

Besides, you should start working on your application.

**Pull request closed without merging**
