### PR TITLE
Fix numba parallel issues

### PR DESCRIPTION
**Pull request by AlexHls**
### :pencil: Description

**Type:** :beetle: `bugfix`

Fixes the numba parallel issues mentioned in #2021 (at least for normal packets)

### :pushpin: Resources

None.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by andrewfullard** [comment]
This is great to see fixed. Do you have examples showing the improvement to reproducibility?

**Comment by AlexHls** [comment]
Yes, here is a plot showing the comparison between a serial and a parallel run (10 threads) of the ``tardis_example.yml``:
test_parallel
You can see that the difference is at the level of machine precision.

Before the fix this would have been the result:
test_parallel

I didn't do more extensive testing, but I think this is such a trivial fix/ clear case that more extensive testing isn't necessary

**Comment by andrewfullard** [comment]
Great, thank you! Next up we need to actually make the monte carlo loop parallel with numba, but that is a LOT more work.

**Comment by wkerzendorf** [comment]
@Rodot- signed off.

**Review by wkerzendorf — APPROVED** [review]

**Review by Rodot- — COMMENTED** [review]
Looks good to me!

**Pull request merged**
