### PR TITLE
Make consistency edits to documentation

### PR DESCRIPTION
**Pull request by arjunsavel**
## Description

I've gone through through the documentation and ensuring consistency throughout: 
- making sure links are correctly linked
- words are all caps if they should be (e.g. TARDIS)
- em dashes are used instead of hyphens
- spaces are used
- typos are fixed
- LaTeX is rendered correctly

In addition, I've removed the extra Monte Carlo Primer section in the navigation sidebar (under "The Physics of Tardis") — it's already a subsection within "Physics Overview."

No content changes are being proposed.

## Motivation and Context

These changes serve the broader goal of making the documentation as easy to digest for newcomers as possible. The fewer small inconsistencies there are, the smoother the experience of first looking at our documentation will be.

## How Has This Been Tested?

I've built the docs locally, and nothing seems to have broken.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by arjunsavel** [comment]
@chvogl @afloers ready for review! I'm thinking that the other items we discussed (now listed under "To do" on [this project board](https://github.com/tardis-sn/tardis/projects/7)) are more related to content additions than just maintaining consistency, so I think they belong in another PR. Please let me know if I've missed anything!

**Comment by arjunsavel** [comment]
@afloers I've now checked for Astropy, HDF5, CMFGEN, GitHub, and YAML!

**Comment by wkerzendorf** [comment]
@arjunsavel - sorry there is a merge conflict - we removed physical_quantities and replaced it with a notebook.

**Comment by arjunsavel** [comment]
@wkerzendorf No worries! I've rebased onto master.

**Pull request merged**
