### PR TITLE
Add Extend Array Function

### PR DESCRIPTION
**Pull request by Sumit112192**
### :pencil: Description

**Type:** :roller_coaster: `restructure`

Add an extend array function to RPacketTracker class

### CODE REVIEW

**Comment by Sumit112192** [comment]
@wkerzendorf @andrewfullard Aren't numpy arrays passed by reference by default?

**Review by andrewfullard — DISMISSED** [review]
Looks great, very clean

**Comment by Sumit112192** [comment]
I should add a test for this function.

**Comment by Sumit112192** [comment]
@andrewfullard @wkerzendorf This PR is now complete and ready to review.

**Review by andrewfullard — APPROVED** [review]

**Pull request merged**
