### PR TITLE
create update refdata pipeline

### PR DESCRIPTION
**Pull request by epassaro**
## How Has This Been Tested?
- [ ] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by epassaro** [comment]
The above command just tested some steps of the pipeline, no new reference data has been pushed.

**Comment by epassaro** [comment]
Seems everything is ok but we need the TARDIS bot token to push.

**Review by andrewfullard — APPROVED** [review]

**Comment by epassaro** [comment]
This should be working, but needs to be tested with a new reference data update (soon?).

**Pull request merged**
