### PR TITLE
Implemented the Simulation Logger as a Class

### PR DESCRIPTION
**Pull request by DhruvSondhi**
Implemented the Simulation Logger as a Class instead of the existing functional implementation

**Description**

**Motivation and context**

**How has this been tested?**
- [x] Testing pipeline.
- [ ] Other. 

**Type of change**

- [ ] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [x] None of the above.  Restructured for clearer implementation

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [x] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Comment by epassaro** [comment]
Sorry about not knowing too much about this. Why we use `log_state` instead of `log_level`? Also why we use `Info` in title case and not lowercase or uppercase?

**Comment by DhruvSondhi** [comment]
Hey @epassaro, `log_state` was actually the name of the variable given by me in the initial implementation of the logger. That time it used to have 3 states: `TRUE`, `FALSE` & `Log_level` which could be a valid string for the log level. After changing the implementation, the variable name was left as it was. 
For the title case, we actually convert the whole string into Uppercase & hence it is just for a check. Also, where did you find `Info` in the code? I am not able to find it 🤔

**Comment by epassaro** [comment]
Not in the code, in the Quickstart guide: `sim = run_tardis('tardis_example.yml', log_state = "Info")`

**Comment by DhruvSondhi** [comment]
Oh, as explained in the previous message, this was just for testing out that it was working & to show that the `log_state` parameter is independent of the case of the input 😉

**Pull request closed without merging**
