### PR TITLE
Fix broken URL in generating_widgets.ipynb

### PR DESCRIPTION
**Pull request by sarthak-dv**
### :pencil: Description

Fixed broken URL as pointed by the linked issue.

**Type:** :beetle: `bugfix`

Resolves https://github.com/tardis-sn/tardis/issues/2532

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [x] Other method: Tested the URL
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [x] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by sarthak-dv** [comment]
@MarkMageeAstro @jamesgillanders please review

**Review by AyushiDaksh — APPROVED** [review]
Looks good to me. Thanks Sarthak.

**Comment by sarthak-dv** [comment]
I don't know why doc build failed, even though I only changed the URL in a markdown cell.

**Review by MarkMageeAstro — APPROVED** [review]

**Comment by MarkMageeAstro** [comment]
Maybe someone else can comment on the fails. Seems like a simple fix so I imagine it's not just this PR

**Comment by andrewfullard** [comment]
> Maybe someone else can comment on the fails. Seems like a simple fix so I imagine it's not just this PR

It's the usual annoying random docs fail due to hdf files.

**Comment by andrewfullard** [comment]
@sarthak-dv please add yourself to the mailmap! You can use the no-reply github email address if you like.

**Comment by sarthak-dv** [comment]
@andrewfullard Updated the mailmap

**Review by jvshields — APPROVED** [review]

**Pull request merged**
