### PR TITLE
Embedded Documentation Version 0.1

### PR DESCRIPTION
**Pull request by Pabla007**
Task 1 Embedding the installation Documentation with Nbsphix

## Description
I have added an Nbsphix folder in the docs to let you go through and see if the documentation is right. I have been succesfully able to parse .ipynb to .html and added additional feature of copy the code from the cell block.

## Motivation and Context
It can make documentation from directly jupyternote book to .html that can be viewed in sphnix.

## Screenshots (if appropriate):
solution

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@Pabla007 you have 62 changed files - was that your intention?

**Comment by Pabla007** [comment]
> @Pabla007 you have 62 changed files - was that your intention?
No it wasn't.
I have copied the whole buid file created by nbsphinx so that you can see the the output.
After i run the python3 -m sphinx <source-dir> <build-dir> that much files are being created. 
I don't know how to show you the output for the documentation to you.

**Comment by marxwillia** [comment]
@Pabla007 see if you can figure out how to open a documentation page locally on your machine without using the internet to access the official docs pages.

**Comment by Pabla007** [comment]
@marxwillia I have made the documentation and it is running offline. 
done

**Comment by marxwillia** [comment]
So if you update a documentation page, we can view it similarly.

**Comment by Pabla007** [comment]
@marxwillia I have to embedded the jupyter notebook using nbsphinx or simply have to update the documentation ??

**Pull request closed without merging**
