### PR TITLE
Add SnakeViz profiling example

### PR DESCRIPTION
**Pull request by KevinCawley**
This is a notebook that shows a sample output from SnakeViz.

**Description**

I made a notebook that runs SnakeViz on run_tardis('tardis_example.yml'). While the HTML cannot be accurately displayed inline, a PNG of the output is displayed below. There is text for explanation for each cell.

**Motivation and context**

Shows an example of how to profile TARDIS. 

**How has this been tested?**
- [x] Testing pipeline.
- [ ] Other. 

**Examples**

**Type of change**

- [ ] Bug fix. 
- [x] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [x] My change requires a change to the documentation.
    - [x] I have updated the documentation accordingly.
    - [x] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [x] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Comment by KevinCawley** [comment]
How it will look upon merge. If Dhruv's PR #1633 is merged, then the long output from Cell 2 will dissapear.

https://kevincawley.github.io/tardis/branch/snakeviz_notebook/io/output/profiling_example.html

**Review by andrewfullard — APPROVED** [review]
Looks good, can the snakeviz image include the table?

**Comment by KevinCawley** [comment]
By the table do you mean the cProfile information? I was unable to get it to due to constraints on my virtual box with taxing pictures.

**Review by smithis7 — APPROVED** [review]

**Review by smithis7 — CHANGES_REQUESTED** [review]
Can you commit the notebook with cells not executed?

**Comment by KevinCawley** [comment]
I could try, but that would be another commit. Are you fine w/ that?

**Comment by smithis7** [comment]
> I could try, but that would be another commit. Are you fine w/ that?

Yeah. It is important that notebooks are committed without any output.

**Comment by KevinCawley** [comment]
I feel like that should be put somewhere.

**Comment by KevinCawley** [comment]
Do not merge until I have gotten rid of some of these commits, thanks.

**Comment by smithis7** [comment]
@KevinCawley your latest doc build action failed

**Comment by smithis7** [comment]
> I feel like that should be put somewhere.

It should be. I am going to put it somewhere in one of my upcoming PRs.

**Comment by KevinCawley** [comment]
I'm going to build the documentation locally, but that's weird that it's appearing now. Maybe you must first do a pip install snakeviz?

**Comment by KevinCawley** [comment]
The error stems from SnakeViz not being inside of the TARDIS environment.

**Comment by andrewfullard** [comment]
It appears that `<script>document.getElementById("snakeviz-4fcfc466-d039-11eb-88f7-000d3a7cea3b").setAttribute("src", "http://" + document.location.hostname + ":8080/snakeviz/%2Ftmp%2Ftmpiy9oiaxj")</script>` is where the display is failing, probably because of how snakeviz accesses the data. This may be solvable with pipeline changes. For now, it just leaves a blank space in the notebook.

**Comment by KevinCawley** [comment]
Yes. There is nothing for it to display, but the white space still shows up.

**Review by andrewfullard — APPROVED** [review]

**Comment by KevinCawley** [comment]
@smithis7

**Pull request merged**
