### PR TITLE
Fix relative atom data path to eliminate use of configuration directory

### PR DESCRIPTION
**Pull request by shreyas3156**
### :pencil: Description

**Type:** :beetle: `bugfix` 

`resolves` #2102 

This PR aims to solve the Atom Data relative path issue that arises when the configuration file is not in the same directory as the notebook/file calling `run_tardis()`. The issue arises because we currently use `config.config_dirname` in `standard_plasmas.py` to find the path to the atom data file which seems counter-intuitive because config and atom data are quite unrelated.

The solution proposed in this PR:

1. Moves all logic that handles `atom_data_fname` from `standard_plasmas.py` to `tardis/io/atom_data/util.py`, with the rationale that resolution of the file path is more appropriate for the `resolve_atom_data_fname()` method in the latter.

2. Eliminates the usage of `config.config_dirname` altogether and instead relies on `data_dir` to find the atom data file.

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [x] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Review by andrewfullard — CHANGES_REQUESTED** [review]

**Review by andrewfullard — APPROVED** [review]

**Review by andrewfullard — DISMISSED** [review]
Looks good. Could add some docstrings to the tests to make the coverage check happy.

**Comment by shreyas3156** [comment]
> Looks good. Could add some docstrings to the tests to make the coverage check happy.

Sure, I'll add the docstrings.

**Comment by andrewfullard** [comment]
Looks like the test is failing

**Comment by shreyas3156** [comment]
> Looks like the test is failing

Yes, the test passed on my local when I specified the `tardis-refdata` path to the `DEFAULT_DATA_DIR` while running pytest. I'm not sure what the `get_data_dir()` call in the tests in github actions receives so I've decided to instead mock the `get_data_dir()` function and I'll amend the recent commit with the change.

**Comment by shreyas3156** [comment]
Sorry, I mistakenly removed the other reviewers while requesting a review! :(

**Review by andrewfullard — APPROVED** [review]

**Comment by andrewfullard** [comment]
@wkerzendorf I think this should be revisited with the restructure

**Comment by andrewfullard** [comment]
Duplicated by other fixes more recently

**Pull request closed without merging**
