### PR TITLE
Added workflow for Documentation preview generation

### LINKED ISSUE #1456: GH action to auto-build documentation for PRs
Currently, we have [documentation preview](https://tardis-sn.github.io/tardis/development/documentation_preview.html) option which requires PR author to do manual setup of deploying docs on their fork. The process is difficult for people unfamiliar with GH action and hence if authors can't do it, there's no way PR reviewers can see the built docs online.

We need to automate it by creating a GH action workflow which should trigger on a PR if `docs/` files are changed and will build docs and deploy them either:
- on `tardis-sn.github.io/tardis/<pr no.>` (as @harpolea suggested) or,
- on `tardis-sn.github.io/docs-demo/tardis/<pr no.>` (what I personally prefer because `docs-demo` repo can then contain docs of other repos like `carsus`, etc. besides tardis). 

Besides, once the deployment is done, workflow should comment on PR with link to deployed docs and once PR is closed/merged, it should delete the docs related to that PR.

### Some Pointers:
- Check config options in https://github.com/peaceiris/actions-gh-pages
- Example of how this idea looks in action is RTD: https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html (see docs for their  readthedocs/readthedocs.org#7894 at https://docs--7894.org.readthedocs.build/en/7894/)

### Concern:
As @epassaro pointed out, 
> I think it's not possible because GA does not share secrets with forks, then you can't write in tardis gh-pages.

But we should give this a try considering how useful it will be!

### PR DESCRIPTION
**Pull request by aribalam**
## Description

Partially fixes #1456 
This PR attempts to automate the process of documentation preview generation for each PR made to modify the documentation files.
Deploying previews through PRs in the main tardis site was not possible due to Github Actions' security concerns. This is a workaround to create documentation previews on the author's github site instead. Moreover, each branch of the fork can also have different previews. To view the preview, we need to visit `<author>.github.io/tardis/<branch-name>`.

**Note: The workflow should be disabled after merging it to master. The workflow should only be enabled in forks.**

Current docs should be changed on how to create documentation previews after merging of this PR.

@epassaro @jaladh-singhal thoughts on this?

## Motivation and Context

See above.

## How Has This Been Tested?
- [ ] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [X] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [X] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by epassaro** [comment]
Great, I'll take a look today.

**Comment by epassaro** [comment]
Hi @aribalam, nice work. Some considerations:

- Very interesting choice of triggers. It has one downside: some sections of `tardis` documentation (notebooks) are executed during build time. This allows us to use part of the documentation as "tests" and also to automatically update it to reflect changes in the code. By specifying that path, this pipeline will not update documentation when the code of `tardis` is changed. On the other hand, I think seems like overkill rendering the documentation on every commit made to a PR.

- I think the step **Extract branch name** could be removed and use some GitHub Actions context instead. Maybe I'm wrong.

- Finally, would be nice to see a preview on your site.

**Comment by aribalam** [comment]
@epassaro Thank you for the review.

>  It has one downside: some sections of tardis documentation (notebooks) are executed during build time. This allows us to use part of the documentation as "tests" and also to automatically update it to reflect changes in the code. By specifying that path, this pipeline will not update documentation when the code of tardis is changed.

I am not quite sure how to address this issue. Any input from your side will be appreciated.

>  On the other hand, I think seems like overkill rendering the documentation on every commit made to a PR.

It certainly seems an overkill to build documentation on each commit made. As far as I know, this is the only way where we could achieve some more automation. There do not seem to be any other Github events for this purpose.
 
> I think the step Extract branch name could be removed and use some GitHub Actions context instead. Maybe I'm wrong.

For the push event, there does not seems to be any context that stores the branch name of the commit. I will take a look nevertheless. 

>Finally, would be nice to see a preview on your site.

I will try to build a documentation preview on my fork and paste the link and screenshot here soon.

**Comment by epassaro** [comment]
> I am not quite sure how to address this issue. Any input from your side will be appreciated.

I think this Is more about a design decision I should discuss with the team. One approach could be to build documentation for every commit pushed to a branch ending with `-docs` suffix. But this is just an idea.

> For the push event, there does not seems to be any context that stores the branch name of the commit. I will take a look nevertheless.

I think there is one, maybe I'm wrong.

**Comment by aribalam** [comment]
@epassaro I have generated a preview on my site with this workflow.

I have created a test page in the documentation which can be found in `Contributing to Tardis -> Developer Workflow -> TESTING DOCUMENTATION PREVIEW` in two different branches. (named `doc-branch-1` and `doc-branch-2`)

The preview for the first branch can be seen here - https://aribalam.github.io/tardis/doc-branch-1

The preview for the second branch can be seen here - https://aribalam.github.io/tardis/doc-branch-2

It can be observed that the contents of the above-specified page are different in both branches.

**Comment by DhruvSondhi** [comment]
Instead of this, I think the branch can be easily modified & the PR can be easily hosted on Read The Docs instead of creating a new webpage through GitHub pages ... I can proceed with this, if needed 😄

**Comment by epassaro** [comment]
> Instead of this, I think the branch can be easily modified & the PR can be easily hosted on Read The Docs instead of creating a new webpage through GitHub pages ... I can proceed with this, if needed

No, we moved away from RTD because offers very limited resources.

**Comment by epassaro** [comment]
> @epassaro I have generated a preview on my site with this workflow.
> 
> I have created a test page in the documentation which can be found in `Contributing to Tardis -> Developer Workflow -> TESTING DOCUMENTATION PREVIEW` in two different branches. (named `doc-branch-1` and `doc-branch-2`)
> 
> The preview for the first branch can be seen here - https://aribalam.github.io/tardis/doc-branch-1
> 
> The preview for the second branch can be seen here - https://aribalam.github.io/tardis/doc-branch-2
> 
> It can be observed that the contents of the above-specified page are different in both branches.

Looks nice. Try to deactivate jobs on main repo from the YAML file (this is better than do it from the GitHub UI). I think I did the opposite (deactivate jobs on forks) on some pipeline, but can't remember on which one.

**Comment by aribalam** [comment]
@epassaro From the YAML file? Are you suggesting applying conditions on jobs to run only on forks?
In that case, I am thinking of adding the condition when `github.repository_owner != 'tardis-sn'` (will be true in case of forks).
Please correct me if I am wrong.

**Comment by epassaro** [comment]
> @epassaro From the YAML file? Are you suggesting applying conditions on jobs to run only on forks?
> In that case, I am thinking of adding the condition when `github.repository_owner != 'tardis-sn'` (will be true in case of forks).
> Please correct me if I am wrong.

Yes. That's right.

**Comment by aribalam** [comment]
@epassaro Done! Kindly have a look.

**Comment by jaladh-singhal** [comment]
> @epassaro I have generated a preview on my site with this workflow.
> 
> I have created a test page in the documentation which can be found in `Contributing to Tardis -> Developer Workflow -> TESTING DOCUMENTATION PREVIEW` in two different branches. (named `doc-branch-1` and `doc-branch-2`)
> 
> The preview for the first branch can be seen here - https://aribalam.github.io/tardis/doc-branch-1
> 
> The preview for the second branch can be seen here - https://aribalam.github.io/tardis/doc-branch-2
> 
> It can be observed that the contents of the above-specified page are different in both branches.

The both links are 404 for me. Also can you please post the link of corresponding PRs for which these previews were generated?

**Comment by aribalam** [comment]
@jaladh-singhal I am guessing the link expired as I did not schedule the workflow to build previews. I have added the schedule keyword to my fork workflow to fix it. You can access the links now. It should be working.

> Also can you please post the link of corresponding PRs for which these previews were generated?

As you can notice these previews get generated on pushing a commit in a non-master branch and not on opening a PR. So there isn't any PR associated with it. These 2 branches were merely created to demonstrate how separated previews can be generated for each branch in the fork.

**Comment by jaladh-singhal** [comment]
@epassaro in your opinion, will this work at tardis repo once merged?

**Comment by epassaro** [comment]
> @epassaro in your opinion, will this work at tardis repo once merged?

I'm not sure. I have to look at this more carefully.

**Comment by epassaro** [comment]
@aribalam There are some hidden env variables in GA check if one can be used to replace the extract step branch: https://stackoverflow.com/questions/62368708/how-to-set-and-access-a-workflow-variable-in-github-actions

**Comment by aribalam** [comment]
@epassaro I'll have a look.

**Comment by aribalam** [comment]
@epassaro I have tested it and there doesn't seem to be any default env variable `GITHUB_REF_NAME`. However, there exists a GA action by the name `github-slug action` that can expose that variable as mentioned in the link you provided. I can go ahead and use it if you want me to.

**Comment by epassaro** [comment]
> @epassaro I have tested it and there doesn't seem to be any default env variable `GITHUB_REF_NAME`. However, there exists a GA action by the name `github-slug action` that can expose that variable as mentioned in the link you provided. I can go ahead and use it if you want me to.

Ok, don't worry.

**Comment by epassaro** [comment]
@aribalam We discussed with the team how to finish this PR:

- Some pages of the TARDIS-SN documentation are notebooks rendered at documentation build time via `nbconvert`. Your approach of using `path: docs/` is really clever, but does not suit our use case (the documentation is also affected by changes in the code!).
- We agreed the best solution for us is mixing these two approaches: a) build documentation for all branches with names containing the `docs` word, and b) building docs when a commit with `[build-docs]` is pushed to a branch.

[Here](https://dev.to/epassaro/use-skip-ci-in-github-actions-1mnf) is an useful link.

**Comment by aribalam** [comment]
@epassaro This is an elegant solution. This will avoid building docs on each commit, which was, as we both agree, a bit of overkill. 
However, I was wondering that do we really need point a) if we are going for b)?. We could just build docs for any branch, irrespective of their name, by just giving the commit message.

**Comment by epassaro** [comment]
> @epassaro This is an elegant solution. This will avoid building docs on each commit, which was, as we both agree, a bit of overkill.
> However, I was wondering that do we really need point a) if we are going for b)?. We could just build docs for any branch, irrespective of their name, by just giving the commit message.

Because some branches are exclusively dedicated to update documentation and it's kinda annoying marking all commits with that tag.

**Comment by aribalam** [comment]
@epassaro Cool! I will get to it right away!

**Comment by aribalam** [comment]
@epassaro I have made the required changes. Kindly have a look!

**Comment by epassaro** [comment]
It works! https://epassaro.github.io/tardis/branch/changes-pr-1493/

I opened a PR pointing this branch making some minor changes plus updating the docs @aribalam

**Comment by aribalam** [comment]
@epassaro Will merge it! I think we also need to mention that any commit made to the master branch of the fork will require the previews of all the branches to be rebuilt again.
This is because pushing a commit to the master branch will trigger the already existing `documentation-build` workflow and will rewrite all the URLs made by the `documentation-preview` workflow.
I realized that it was the main reason why the demo links showed 404 later as pointed in this [comment](https://github.com/tardis-sn/tardis/pull/1493#issuecomment-805671309). 
I will check it again if it shows the same behaviour.

**Comment by epassaro** [comment]
I see, good catch! Seems the scheduled workflow is the one to blame. Maybe forcing the `documentation-build` pipeline to not run on forks will do the trick, but users will need to sync their `master` branches with upstream.

I think does not worth it. Just build the docs again if you see it has been removed.

**Review by epassaro — APPROVED** [review]

**Comment by epassaro** [comment]
Before merge please add:

```
with:
   fetch-depth: 0
```

to the checkout step.

**Pull request merged**
