### PR TITLE
Bug fixes and Improvements in Custom Abundance Widget

### PR DESCRIPTION
**Pull request by yuyizheng1112**
This PR contains several changes and bug fix to custom abundance widget.

**Description**

- Set abundances in new shell(s) to the abundances in the left (inner) shell instead of setting to 0. In the case of adding/overwriting innermost shell, set the abundances equal to the first shell.
- Added the feature required in issue #1779 .
- Fixed the bugs in `write_csv_portion` function and added config version information when saving CSVY file. Now the velocity of the output file is correct and `from_csvy` function works properly.
- FIxed the issue of "Unnormalized" warning display.

**Motivation and context**

**How has this been tested?**
- [ ] Testing pipeline.
- [x] Other. 

**Examples**

After adding new shell(s), the abundances in new shell(s) keep the same with the left shell:

截屏2021-09-18 下午3 51 28

When Select a range of shells, it will be highlighted in the plot and the shell No dropdown will be disabled:

截屏2021-09-18 下午3 52 21

**Type of change**

- [x] Bug fix. 
- [x] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [x] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Review by jaladh-singhal — CHANGES_REQUESTED** [review]
Very excellent work @yuyizheng1112 - this is an almost perfect PR. :clap: 

You've made it exactly as we wanted it to be. I've ran the widget locally and it works great - esp. how the range selection is now handled.

I just think since this PR makes 4 different fixes as listed by you (that should have ideally be in separate PRs but it's ok now that you've made one), you should rename PR title to something more generic (like ___ improvements in custom abundance widget) that includes all 4 points. Current tile is just apt for 1st point.

Only problem that I noticed while running it locally is the shell-overwriting warning persists even after clicking "add" button which I guess was not the case before. I'm happy to merge this once that's fixed. And I should mention unnormalized warnings work correctly now!

**Comment by luharvey** [comment]
Hi Jenny, this is looking great and the csvy import and export issues are fixed. There is only one final bug I can see when trying to run the csvy file, for some reason the v_inner_boundary is slightly lower than the velocity of the first shell (about 1km/s lower so perhaps a rounding issue?). TARDIS then complains that the inner boundary velocity is lower than the lowest velocity in the model.

**Comment by yuyizheng1112** [comment]
I think this pr can be merged now @jaladh-singhal @jamesgillanders

**Comment by jaladh-singhal** [comment]
We'd be happy to! @yuyizheng1112 can you please quickly resolve the merge conflict by rebasing it?

**Review by jaladh-singhal — APPROVED** [review]
Everything works fine now! Thanks alot @yuyizheng1112

**Pull request merged**
