### PR TITLE
Submit the first objective for Custom Abundance Widget project for GSoC 2021

### PR DESCRIPTION
**Pull request by yuyizheng1112**
## Description

This is a PR for the first objective of Custom Abundance Widget project. 

The first line chart shows the elemental abundance as a function of velocity for an example tardis simulation set up using the self-constructed csvy model. The atomic number is also converted to element symbol by `atomic_number2element_symbol` function imported from `tardis.util.base`. The second chart shows the same plot using plotly.

- `first-objective.ipynb`: The code of the visualization process. 
- `fad_plot.py`: Integrate the generation process of plots using matplotlib and plotly by `FADPlotter` which is similar to `SDECPlotter`. 
- `fad_plot.ipynb`: An example of `FADPlotter`.

## Screenshots (if appropriate):
`fad_plot.ipynb`:
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by jamesgillanders** [comment]
Can you annotate the axes here - it is useful to know the fractional abundances and also the velocity for the different shells

**Comment by marxwillia** [comment]
@yuyizheng1112 great work!  Can you now please make the exact same plot, but using plotly which is an interactive python plotting tool.  We will most likely use plotly for the GSoC project, so it will be good to get familiar with how it works.

**Comment by yuyizheng1112** [comment]
> Can you annotate the axes here - it is useful to know the fractional abundances and also the velocity for the different shells

Hello, I think I have already annotated the axes. However, I found that I annotated the wrong unit and I corrected it. Please take a look at the new plot and let me know if there is something I can improve.

**Comment by yuyizheng1112** [comment]
> @yuyizheng1112 great work! Can you now please make the exact same plot, but using plotly which is an interactive python plotting tool. We will most likely use plotly for the GSoC project, so it will be good to get familiar with how it works.

I have updated the new plot using plotly. Also, I integrated the generation process of plots in `FADPlotter` in `fad_plot.py` so that we can generate plots using matplotlib/plotly freely just like `SDECPlotter`. Could you please give me some feedback?

**Review by jaladh-singhal — COMMENTED** [review]
@yuyizheng1112 sorry for delayed reply. It's good to see you've structured your code similar to SDEC plot. The matplotlib plot's labels font size can be increased a bit.

Besides, you should start working on your project proposal.

**Comment by yuyizheng1112** [comment]
@jaladh-singhal Thanks for your advice. Please check the screenshot with bigger font size.

**Pull request closed without merging**
