### PR TITLE
Fix virt energy

### PR DESCRIPTION
**Pull request by yeganer**
This is a simple change allowing access to virtual packet properties as quantities.

### CODE REVIEW

**Comment by yeganer** [comment]
@tardis-sn/tardis-core Is this something we want to merge into master or is this a `dalek-only` fix?

**Comment by wkerzendorf** [comment]
@tardis-sn/tardis-core I think that is good and am happy to merge.

**Comment by yeganer** [comment]
Why did nobody tell me to rebase... That history looks stupid. Sorry.

**Comment by wkerzendorf** [comment]
@yeganer - sorry, my bad. I was so eager to get your awesome changes in :wink:

**Pull request merged**
