### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by nileshpatra**
added '.' for relative file path , so that there are no conflicts during installation of tardis

### CODE REVIEW

**Comment by wkerzendorf** [comment]
I think absolute imports are better - try that.

**Comment by nileshpatra** [comment]
@wkerzendorf , did that for absolute path , import works on my machine . please review

**Comment by wkerzendorf** [comment]
That is not the full absolute path. TARDIS.io.util is

**Comment by nileshpatra** [comment]
Yeah , but when the repository is cloned on the machine , it would take the path for the utility folder in the same directory TARDIS/io where until is present . Is it wrong?😅

**Comment by wkerzendorf** [comment]
that works as long as in your system there is no `util` package. it is safer to spell it out what you mean. but enough with this PR. try to get the code running with the master branch version and get a spectrum out.

**Pull request closed without merging**
