### PR TITLE
Convert cython code in macro_atom to numpy with numba

### PR DESCRIPTION
**Pull request by Debjoy10**
## Description

In directory tardis/plasma/properties/util, added script **macro_atom_with_numba.py** incorporating all code in **macro_atom.pyx** in cython to numba optimised numpy code. Used `@jit` decorator with `parallel=True` and `prange` to parallel-process all loops in `calculate_transition_probabilities()`

Also added **macro_atom_with_numpy.py** with **NO** numba/cython optimisation to determine overall improvement from just python.

## Motivation and Context

Evaluating the sample improvement in performance on migrating cython code to NumPy with Numba.

## How Has This Been Tested?

`python setup.py test` posed no errors due to added code. Script `test_macro_atom.py` evaluates the performance of all three scripts based on the execution time.

**macro_atom_with_numba.py**
`Time taken (with compilation): 1.7195398807525635`
`Time taken (after compilation): 0.0388643741607666`

**macro_atom.pyx**
`Time taken (with compilation): 0.09258008003234863`
`Time taken (after compilation): 0.09229183197021484`

**macro_atom_with_numpy.py**
`Time taken (with compilation): 19.831270456314087`
`Time taken (after compilation): 19.669527769088745`

Numba improves performance after compilation, best suited to multiple function calls. Also simplifies code.  

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by shreyansjain012** [comment]
@Debjoy10 Are you sure the code is working? The program is still working on `macro_atom.pyx`

**Comment by Debjoy10** [comment]
No, the changes haven't been included in the scripts that `import macro_atom`, they still use the cython version. Once confirmed, I will add those in later commits.

**Comment by shreyansjain012** [comment]
Okay

**Comment by marxwillia** [comment]
We want to see that the TARDIS tests pass with your new implementation.

**Comment by Debjoy10** [comment]
Sorry, missed this comment. Tests pass.
P.S: I found only the radiative_properties.py script to import macro_atom and changed it.

teset

**Pull request closed without merging**
