### PR TITLE
Create profiling directory

### PR DESCRIPTION
**Pull request by KevinCawley**
Add a notebook about profiling TARDIS based on parameters, and made a directory to house the profiling information.

**Description**

**Motivation and context**

Feature

**How has this been tested?**
- [ ] Testing pipeline.
- [x] Other. 

**Examples**

**Type of change**

- [ ] Bug fix. 
- [x] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [x] My change requires a change to the documentation.
    - [x] I have updated the documentation accordingly.
    - [x] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [x] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Comment by andrewfullard** [comment]
Can you link to your documentation build for this branch?

**Comment by KevinCawley** [comment]
It's currently failing due to a version error which is trying to be fixed.

**Comment by KevinCawley** [comment]
https://kevincawley.github.io/tardis/branch/profiling/development/profiling/index.html

**Review by andrewfullard — APPROVED** [review]

**Comment by yuyizheng1112** [comment]
There's blank in the documentation page [here](https://kevincawley.github.io/tardis/branch/profiling/development/profiling/profiling_example.html), can this be removed?

**Review by smithis7 — APPROVED** [review]

**Comment by KevinCawley** [comment]
Not as far as I know. It is the display output of `snakeviz`, but it doesn't render when the documentation is built.

**Review by yuyizheng1112 — APPROVED** [review]

**Pull request merged**
