### PR TITLE
Move and rename coverage file

### PR DESCRIPTION
**Pull request by arjunsavel**
## Description

I've moved the coverage configuration file to the `TARDIS` root directory; this should ensure that it is read in correctly (e.g., correct files are omitted from coverage calculation).

## Motivation and Context

When running `python setup.py test --coverage` locally, I noticed that test files were being included in coverage counts. These are explicitly omitted in the coverage configuration file. 

## How Has This Been Tested?

Checking the [coverage page](https://codecov.io/gh/tardis-sn/tardis/pull/1218/tree) for this PR seems to indicate that it works as expected. 

## Screenshots (if appropriate):
sunburst
The above image shows the coverage sunburst from [our codecov page](https://codecov.io/gh/tardis-sn/tardis), which notably includes test folders that are excluded in the configuration file. By changing the location of the coverage file, this will (hopefully!) be fixed.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have assigned/requested two reviewers for this pull request.

### CODE REVIEW

**Comment by epassaro** [comment]
I don't know so much about coverage. This is the `.coveragerc` file from `carsus`: https://github.com/tardis-sn/carsus/blob/master/carsus/tests/coveragerc

**Comment by arjunsavel** [comment]
@marxwillia thanks for the suggestion — done!

**Comment by epassaro** [comment]
How does the sunburst graph looks now?

**Comment by arjunsavel** [comment]
@epassaro can't quite get the sunburst graph to happen — but [here's](https://codecov.io/gh/tardis-sn/tardis/pull/1218/tree/) how the tree looks. No tests are being checked for coverage anymore!

**Pull request merged**
