### PR TITLE
Fix the encoding error in setup.py

### PR DESCRIPTION
**Pull request by nomalocaris**
## Description

Fixed a potential error in setup.py, which may raises UnicodeDecodeError because  the docstring in the module has a Unicode character and our unpickler doesn't specify any encoding (thus defaulting to ascii).

## Motivation and Context

os: ubuntu::latest (DockerHub)

After built a new docker container for tardis and followed the Installation guide to create a development environment, I met this question as follow:

```Python
(tardis) root@8c64da05046f:/usr/depot/tardis# python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    LONG_DESCRIPTION = f.read()
  File "/usr/local/bin/miniconda3/envs/tardis/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3223: ordinal not in range(128)
```

The problem is that the docstring in the module has a Unicode character and our unpickler doesn't specify any encoding (thus defaulting to ascii).

## How Has This Been Tested?

Running `python setup.py test` gave no errors.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
Thanks - that looks great! In which way do you use TARDIS in docker if I may ask.

**Comment by nomalocaris** [comment]
> Thanks - that looks great! In which way do you use TARDIS in docker if I may ask.

This is not difficult. Docker can build Ubuntu containers, which is similar to virtual machines. In the container, I can develop just like in the Ubuntu system. Moreover, it is more pure and convenient.

**Comment by wkerzendorf** [comment]
I understand - I was just wondering for what science project you are using this - or are you a GSoC applicant?

**Comment by nomalocaris** [comment]
> I understand - I was just wondering for what science project you are using this - or are you a GSoC applicant?

Sorry, I misunderstood you. Yes, I am the latter. I am preparing for GSoC. I will create a PR for the first objective recently. By the way, This PR check failed in Test mac. It seems like fail at the beginning. Could you give me some suggestions?

**Pull request closed without merging**
