### PR TITLE
add the symlink to visualization examples

### PR DESCRIPTION
**Pull request by yuyizheng1112**
## Description

**Changes made:**
Add the configuration file _tardis_example.yml_ to the directory: docs/using/visualization.
## Motivation and Context

In _generating_widgets.ipynb_ and _sdec_plot.ipynb_, the file path of function `run_tardis()` is _'tardis_example.yml'_, which directs to the file in the same directory as notebooks. Therefore, the configuration file should be added to the directory.

## How Has This Been Tested?
- [x] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

## Screenshots (if appropriate):
截屏2021-03-14 上午10 46 51

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by marxwillia** [comment]
This seems reasonable to me.  The one thing we might want to consider is that the tardis_example.yml file is going to be living in multiple places in the repository.  We should think about other ways to make our common example files easily accessible, while minimizing copies.  @jaladh-singhal any thoughts?

**Comment by smithis7** [comment]
We use symbolic links for that file. The only real copy of `tardis_example.yml` is under `docs/using/components/models/examples/`-- this way, if we need to change it we only need to change one file.

@marxwillia is right though about accessibility. Perhaps we move the file somewhere easier to find, like just under `docs/`-- that would require changing all of the symlinks, so it would be a little bit of a task.

**Comment by andrewfullard** [comment]
Converting to draft until comments are addressed

**Comment by jaladh-singhal** [comment]
> We use symbolic links for that file. The only real copy of `tardis_example.yml` is under `docs/using/components/models/examples/`-- this way, if we need to change it we only need to change one file.

I second this. @yuyizheng1112 can you create a symlink to above path (as of now for this PR) instead of copying config file?

> @marxwillia is right though about accessibility. Perhaps we move the file somewhere easier to find, like just under `docs/`-- that would require changing all of the symlinks, so it would be a little bit of a task.

@marxwillia  @andrewfullard where do you think is the best place to keep `tardis_example.yml` within repo? @yuyizheng1112 once this is decided, you can dig all existing `tardis_example.yml` files & symlinks and change them as @smithis7 mentioned in another PR.

**Review by jaladh-singhal — CHANGES_REQUESTED** [review]
@yuyizheng1112 I think you're close, can you complete this PR with requested change (in comment above)?

**Comment by yuyizheng1112** [comment]
> @yuyizheng1112 I think you're close, can you complete this PR with requested change (in comment above)?

Sorry that I just saw your comment and thanks for your guidance!

**Comment by yuyizheng1112** [comment]
> > We use symbolic links for that file. The only real copy of `tardis_example.yml` is under `docs/using/components/models/examples/`-- this way, if we need to change it we only need to change one file.
> 
> I second this. @yuyizheng1112 can you create a symlink to above path (as of now for this PR) instead of copying config file?
> 
> > @marxwillia is right though about accessibility. Perhaps we move the file somewhere easier to find, like just under `docs/`-- that would require changing all of the symlinks, so it would be a little bit of a task.
> 
> @marxwillia @andrewfullard where do you think is the best place to keep `tardis_example.yml` within repo? @yuyizheng1112 once this is decided, you can dig all existing `tardis_example.yml` files & symlinks and change them (as @smithis7 mentioned) in another PR.

I am willing to take this task if the place of `tardis_example` would be changed.

**Review by smithis7 — APPROVED** [review]

**Review by jaladh-singhal — APPROVED** [review]

**Pull request merged**
