### PR TITLE
A better error message for collision matrix missing data

### PR DESCRIPTION
**Pull request by kaushik94**
Render a better error message when collision data is missing. #107

### CODE REVIEW

**Comment by kaushik94** [comment]
Take a look at https://travis-ci.org/tardis-sn/tardis/jobs/53281711. Weird error messages !

**Comment by kaushik94** [comment]
@wkerzendorf  please review, also take a look at https://github.com/rajul-iitkgp/tardis/commit/0f6e16dc9bd34659ef6d277b2b8f7551af3d26ab. Seems to be a good approach as well.

**Comment by wkerzendorf** [comment]
@kaushik94 you're fast. I'm currently trying to deal with the non-working GUI for one of the other applicants. I'll have a look a little later. If you want a hard nut to crack - try writing tests for the c part of the simulation using pytest ; we've not been able to deal with that (this obviously optional) .

**Comment by wkerzendorf** [comment]
I think @rajul-iitkgp's version is technically what we want. can you make a standards compliant one?

**Comment by kaushik94** [comment]
>I think @rajul-iitkgp's version is technically what we want

May be I din't understand the requirements correctly. Please point out where I went wrong btw.
> can you make a standards compliant one?

I think its best for @rajul-iitkgp to make a PR and merge, I don't want to take the credit for that. Btw I asked him to write a PR, guess he'll get back soon. For now Im closing this :)

**Comment by kaushik94** [comment]
>@kaushik94 you're fast

Not really, Im kinda finding a lot of free time these days.
>I'll have a look a little later

Not a problem, They are just tests afterall.
>try writing tests for the c part of the simulation using pytest ; we've not been able to deal with that (this obviously optional) . 

I don't understand the complication so probably Im not clear enough about the problem, so writing a PR might not be best idea for me at this moment. I got a few things to discuss regarding this and will ping you in the mailing list about this in a moment and then work around a fix for it. How does that sound ?

**Pull request closed without merging**
