### PR TITLE
Misleading header file

### PR DESCRIPTION
**Pull request by theaverageguy**
Fixes https://github.com/tardis-sn/tardis/issues/489

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@chvogl @yeganer @mreinecke can you guys look at this? I can't remember if that was a sensible fix.

**Comment by yeganer** [comment]
@theaverageguy Thank you for the contribution.
@wkerzendorf The change is fine but there are two issues:

- The 1st commit won't compile since there will be two declarations of line_search
- After the 2nd commit there will be an import error because `cmontecarlo1.h` is deleted.

I suggest you remove the `include "cmontecarlo1.h"` from `cmontecarlo.h` and then combine all commits into one commit that covers the whole change with a litte explanation in the body of the commit message summarizing what and why it changed.

**Comment by mreineck** [comment]
Also, you need to remove the
#include "cmontecarlo1.h"
from rpacket.h and add
#include "cmontecarlo1.h"
to rpacket.c.

**Comment by mreineck** [comment]
Sorry, correction ....
of course you need to 
#include "cmontecarlo.h"
from rpacket.c.

**Comment by yeganer** [comment]
@mreineck thanks, I totally forgot that rpacket.c is missing this `#include`.

In general there needs to be some cleanup of header files. Headers should only `#include ...` stuff the header needs. Everything else goes into the corresponding source file.

@wkerzendorf I'm not sure if it is a good idea to include these changes within this PR or if we want a new PR for header cleanup.

**Comment by yeganer** [comment]
#531 Fixed the corresponding issue. Closing this

**Pull request closed without merging**
