### PR TITLE
Updated nlte.rst 

### PR DESCRIPTION
**Pull request by souravsingh**

### CODE REVIEW

**Comment by souravsingh** [comment]
I am not able to figure out why the tests are failing.

**Comment by orbitfold** [comment]
Our tests are so good they are sentient. They fail when they feel like it.

**Comment by wkerzendorf** [comment]
They fail due to an astropy problem.

**Comment by wkerzendorf** [comment]
@souravsingh do you know how to look up the logs of the TRAVIS runs?

**Comment by souravsingh** [comment]
@wkerzendorf Yes,I do.The PR failed all 6 tests.

**Comment by souravsingh** [comment]
All tests failed at the same point
```
ImportError: numpy.core.multiarray failed to import
ERROR: could not load /tmp/tardis-test-7tLBAc/lib.linux-x86_64-2.7/tardis/conftest.py
```

**Comment by wkerzendorf** [comment]
@souravsingh I'm having a look into this. I'd like to chat to you offline - what's your email address?

**Comment by souravsingh** [comment]
@wkerzendorf My E-mail is ssouravsingh12@gmail.com

**Comment by wkerzendorf** [comment]
@souravsingh I fixed it. Can you rebase onto the newest master?

**Pull request closed without merging**
