### PR TITLE
Gsoc altock

### PR DESCRIPTION
**Pull request by altock**
Hi, I am Sam Svenningsen, though I go by Sven, and I'm a GSoC applicant for the Plasma Project.

### CODE REVIEW

**Comment by altock** [comment]
Landscape-bot seems to show errors in files I don't recall changing? Should I clone the original branch again and then just add the one file I changed?

**Comment by wkerzendorf** [comment]
make sure that you hand in a proposal!

**Comment by altock** [comment]
Finishing it up now. 

Would I be able to get it reviewed quickly before a final submission please? 

Also, is there a way to test the function I wrote? I don't quite know what tau and beta sobolevs are, so I wasn't really sure what a proper test would be. Thanks.

**Comment by altock** [comment]
Submitted.

**Pull request closed without merging**
