### PR TITLE
Added a few tests for atomic lines

### PR DESCRIPTION
**Pull request by kaushik94**
@wkerzendorf  I have added a few tests for atomic lines readin. Please review and let me know

### CODE REVIEW

**Comment by wkerzendorf** [comment]
there was already a test open on this - can you test something else. The general structure is correct. maybe not in atomic.

**Comment by kaushik94** [comment]
> there was already a test open on this 

Ohh Okay, are you talking about #229 . I just saw it, but its closed ?

> can you test something else. 

Sure, I'll close this one and get back to you :)

**Comment by wkerzendorf** [comment]
Why was this reopened @kaushik94 ?

**Comment by kaushik94** [comment]
Sorry, was going through the PRs and happened by mistake.

**Pull request closed without merging**
