### PR TITLE
Modified various functions to use numba

### PR DESCRIPTION
**Pull request by Phantsure**
## Description

Optimized functions to use numba for better results.
### calculate_transition_probabilites
The current code is written in cython but it could be improved using numba and python. I also tried improving the cython code but not much difference occurred. 
### calculate in atomic.py
Tried optimizing the python code using numba. No major improvement shown.
### calculate_transition_probabilites
Screenshot_2020-03-03 Screenshot from 2020-03-03 05-39-04 png (PNG Image, 1920 × 1080 pixels) - Scaled (85%)
### calculate in atomic.py
Screenshot_2020-03-05 Screenshot from 2020-03-05 02-43-26 png (PNG Image, 1920 × 1080 pixels) - Scaled (85%)
### calculate:32 in j_blues.py & calculate:45 in ion_population.py
Screenshot_2020-03-14 Screenshot from 2020-03-14 16-26-08 png (PNG Image, 1920 × 1080 pixels) - Scaled (85%)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] calculate_transition_probabilites in macro_atom.py
- [x] calculate in atomic.py
- [x] calculate:32 in j_blues.py
- [x] calculate:45 in ion_population.py

### CODE REVIEW

**Comment by wkerzendorf** [comment]
okay - find other functions that other students have not looked at. Profile the code.

**Comment by Phantsure** [comment]
I was looking through the code to find one more function in  tardis/plasma/properties/atomic.py(calculate). I wrote its code with numba but no major improvement. But still adding it.

**Comment by wkerzendorf** [comment]
did you profile the whole code to see if that is a signifcant fraction of TARDIS runtime?

**Comment by Phantsure** [comment]
i did that commit before i sorted the profile output by run time. I sorted the profile output and in 2-3 functions taking highest time, i.e. 1.8-1sec(after montecarlo), i tried optimizing that but it said that cant run in no python mode. i think i have to change the code and try again to make it work with njit.

**Comment by Phantsure** [comment]
Numba is not providing any major improvement in run time. I have tried many functions. I mean it either no improvement or very less.

**Comment by Phantsure** [comment]
Have updated a few files. At last found few improvements.

**Comment by wkerzendorf** [comment]
do the tests parse?

**Comment by Phantsure** [comment]
> do the tests parse?

what do you mean? Am i able to run error free `pytest`?

**Comment by Phantsure** [comment]
tests are running fine
Screenshot_2020-03-21 Screenshot from 2020-03-21 11-12-54 png (PNG Image, 1920 × 1080 pixels) - Scaled (85%)

**Pull request closed without merging**
