### PR TITLE
[WIP] Basic implementation of the formal integral

### PR DESCRIPTION
**Pull request by yeganer**
This is still WIP and contains a basic implementation of the formal integral approach ported to C.

Milestones:

- [x] Basic Implementation
- [x] Dicuss OMP
- [x] Config Integration
- [ ] Documentation (See #621)

### CODE REVIEW

**Comment by unoebauer** [comment]
Looks like a good starting point! Can you make a list of milestones to define the scope of this PR?

**Comment by yeganer** [comment]
Something like this?

**Comment by unoebauer** [comment]
Well, if you want to do everything in one go then I'd say yes.

**Comment by yeganer** [comment]
Not necessarily. We can split the PR in several smaller and more focused ones. Do you have suggestions?

**Comment by unoebauer** [comment]
I'd rather do it in smaller chunks and split it up into sensible sub-projects. E.g.:
- 1: basic C-implementation of FI (without e-scattering, without external configuration)
- 2: unit testing and configuration
- 3: including e-scattering
- 4: generalisation to macro-atom

**Comment by yeganer** [comment]
According to your suggestion part 1 is mostly done? Only function documentation is missing as of right now. Additionally I'm not happy with the implementation as it does not allow for modularity right now. But I have changes in mind that should solve this.

**Comment by yeganer** [comment]
fi_spectrum
Plot of the latest version (this PR is behind) of the formal integral.
The difference between MC and Integrator is due to the different initialization of the packets in the montecarlo code.

**Comment by yeganer** [comment]
Close in favor of #740.

**Pull request closed without merging**
