### PR TITLE
Fixing issues with `Citations` & `Label` references in Docs

### PR DESCRIPTION
**Pull request by DhruvSondhi**
Fixes issues with citations & labels for documentation generation

**Description**

Citations & Label referencing in the current documentation do not work as intended.
This PR aims to fix this :)

**Motivation and context**

Citations are now referenced correctly 
Labels now point to the correct part of the documentation

**How has this been tested?**
- [x] Testing pipeline.
- [x] Other.  Local Testing

**Type of change**

- [x] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [x] My change requires a change to the documentation.
    - [x] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [ ] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Review by smithis7 — COMMENTED** [review]
Everything looks good -- there were three more broken citations if you're able to fix them:

```
docs/physics/montecarlo/propagation.rst:39: WARNING: citation not found: Bjorkmann1999
docs/physics/plasma/nebular_plasma.rst:39: WARNING: citation not found: 1993A&A...279..447M
docs/physics/plasma/nebular_plasma.rst:63: WARNING: citation not found: 1993A&A...279..447M 
```

**Review by smithis7 — APPROVED** [review]
Perfect! I built it locally and everything is working!

**Comment by marxwillia** [comment]
@DhruvSondhi in order to speed up the review process, can you please include a link to your local build of the documentation for PR's like this one where you implement changes?  See PR [1584](https://github.com/tardis-sn/tardis/pull/1584) for an example.

**Comment by smithis7** [comment]
@marxwillia I don't know if Dhruv got this fixed yet, but there was an issue with his documentation deploying. That's why I had just built it locally.

**Comment by DhruvSondhi** [comment]
Hello @marxwillia, Sorry for the late response 😓 . There is some problem with my GitHub Pages Documentation Deployment. I can generate the documentation from the `gh-pages` branch (all thanks to @epassaro 🙌🏼 ) which can be seen [here](https://dhruvsondhi.github.io/tardis/) but I cannot generate the docs from this branch apparently. I am trying to figure out where the problem could be lurking but it seems distant from a potential fix. If I can share the screenshots of the documentation thus built locally, would it be adequate?

**Review by marxwillia — APPROVED** [review]

**Pull request merged**
