### PR TITLE
Energy input benchmark

### PR DESCRIPTION
**Pull request by officialasishkumar**
### :pencil: Description

**Type:** :rocket: `feature` 

Benchmark for energy input functions

- [x] Benchmark for run_gamma_ray_loop
- [x] Benchmark for gamma_packet_loop

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by andrewfullard** [comment]
Please provide test results here

**Comment by atharva-2001** [comment]
@officialasishkumar is this done?

**Comment by officialasishkumar** [comment]
I was told to stop working on this since there is some ongoing modification in the energy input files.

**Comment by officialasishkumar** [comment]
Closing for now. Will make changes on this later.

**Pull request closed without merging**
