### PR TITLE
Add init.py to energy input module

### PR DESCRIPTION
**Pull request by andrewfullard**
### :pencil: Description

**Type:** :beetle: `bugfix` 

Hopefully fixes the Conda feedstock, and issue #2370 

### :vertical_traffic_light: Testing

How did you test these changes?

- [x] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [x] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by epassaro** [comment]
Do `montecarlo_/montecarlo_numba` need init files too?  https://github.com/tardis-sn/tardis/pull/2139/files

**Comment by andrewfullard** [comment]
> Do `montecarlo_/montecarlo_numba` need init files too? https://github.com/tardis-sn/tardis/pull/2139/files

They already have them.

**Comment by andrewfullard** [comment]
Unfortunately this does not seem to fix the benchmarks.

**Comment by epassaro** [comment]
> > Do `montecarlo_/montecarlo_numba` need init files too? https://github.com/tardis-sn/tardis/pull/2139/files
> 
> They already have them.

I think init file is missing here: https://github.com/tardis-sn/tardis/tree/master/tardis/montecarlo/montecarlo_numba/tests

**Review by epassaro — APPROVED** [review]

**Review by atharva-2001 — APPROVED** [review]

**Pull request merged**
