### PR TITLE
fixes at least some of the pandas loc errors

### PR DESCRIPTION
**Pull request by wkerzendorf**
This is a fix for #402 - but doesn't deal with all of them. Two of them I do not know how to get rid of.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@ssim @aoifeboyle merge if happy.

**Comment by ssim** [comment]
@aoifeboyle any thoughts on this? I don't understand well enough what it's doing to really judge right now.

**Comment by aoifeboyle** [comment]
I'm out today but if you could just leave it open til later I'll take a look this evening? I'll see if I can work out the other errors too.

**Comment by ssim** [comment]
@aoifeboyle Thanks!

@wkerzendorf If it's fresh in your mind, could you add some comments to the code to explain what these lines you've changed are actually doing? This stuff seems very opaque to me - would be good to explain what's going on

**Pull request merged**
