### PR TITLE
Added tests for plasma level population properties.

### PR DESCRIPTION
**Pull request by aoifeboyle**
New test file test_property_level_population. Also added many more properties to conftest to simplify testing, and tidied up test_property_atomic and test_property_ion_population a little.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
you are quick :wink: ! Let me know if you want this merged. Let me know when you want to start working on `LegacyPlasmaArray`.

**Comment by aoifeboyle** [comment]
I'm trying to stick with small PRs like you suggested :P I'd like this merged if you are happy with it. I think it's fine. I have a few more properties of the LTE plasma that I'd like to test and then I'll start looking at the Legacy Plasma later today. Any particular instructions/suggestions? I'm also planning to create property groups for both plasmas in property_collections.py.

**Comment by wkerzendorf** [comment]
@aoifeboyle I think that sounds good. I have some particular suggestions for the legacy plasma, but I think skype lends itself to this better. So before you start with that - let's do some skyping. 

will merge the current PR.

**Comment by aoifeboyle** [comment]
Ok @wkerzendorf . Not likely to start on it til tomorrow so maybe tomorrow morning sometime?

**Pull request merged**
