### PR TITLE
Separate Continuum Tests

### PR DESCRIPTION
**Pull request by atharva-2001**
### :pencil: Description

**Type:** | :vertical_traffic_light: `testing` | :roller_coaster: `infrastructure`

Made on top of https://github.com/tardis-sn/tardis/pull/2698. 
Will separate regular and continuum tests into two jobs.

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by atharva-2001** [comment]
I will address the `osx-arm64-pip-false Expected — Waiting for status to be reported` once the PR is merged. I wouldn't want the check to go away from other pull requests until this is merged.

**Comment by andrewfullard** [comment]
It's odd that the refdata generation tests are taking longer than the regular tests. The codecov errors are also interesting, I guess we need to fix some minor path-related bugs?

**Comment by atharva-2001** [comment]
> It's odd that the refdata generation tests are taking longer than the regular tests. The codecov errors are also interesting, I guess we need to fix some minor path-related bugs?

I agree, but I don't know why they take so long. The markers are the same in both the tests, when one is disabled it seems to take the same time. When both are disabled it takes longer.
In both the tests it says this-
```
collected 1900 items / 24 deselected / 1876 selected
collected 1900 items / 24 deselected / 1876 selected
```

Perhaps it the nature?
https://github.com/tardis-sn/tardis/actions/runs/9968496268/job/27543877401?pr=2699

They do take slightly longer usually, right?
https://github.com/tardis-sn/tardis/actions/runs/9595970972/job/26522577969 

The codecov is a separate job entirely now so it runs only once. I think the way the report is generated is the same, the way it is sent to the website is different. I thought fixing the codecov issues would be too much for the pull request, is it alright if I address it in a new one?

**Review by andrewfullard — APPROVED** [review]
Thanks for dealing with the sudden changes!

**Comment by atharva-2001** [comment]
No problem!

**Pull request merged**
