### PR TITLE
Add skip condition if QT_API is no set (bug #1101)

### PR DESCRIPTION
**Pull request by jordi5**
`pytest tardis` fails on import of gui interface and widgets if QT_API variable is not set

## Description
 Since I the issue appears on import and I don't understand how skipimport would work when the error is not that the module is not found, but that there is an undefined variable within the module, I changed the call so that the import wouldn't check inside the module until needed for the test by importing the whole module. Following this some of the objects inside the function have to be called more explicitly.

I added the skipif decorator from pytest but **I'm not sure the issue is fixed.** The test now skips when the variable QT_API is not defined, but I'm not sure how the `pytest tardis` should proceed when the variable is defined. When I define QT_API either way on my master branch the test still skips, which I suppose is the expected behaviour because I didn't modify anything there. 

On a different commit I modified the functions interface and widgets to change how the Iphyton library calls specific functions, as can be seen this changes a qt4 to a qt5 and is purely for consistency, given that the functions are the same.

## Motivation and Context
Adresses #1101 

## How Has This Been Tested?
Run `pytest tardis` and the test now skips when QT_API is not declared.
Run again for the Iphyton calls change.
Giving( to save as reference)
263 passed, 1119 skipped, 1 xfailed in 24.38 seconds

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

All input is appreciated.

### CODE REVIEW

**Comment by Chinmay4400** [comment]
@jordi5 We can define QT_API if not declared within the test, that way tests won't have to be skipped. `os.environ['QT_API'] = 'pyqt'`

**Comment by wkerzendorf** [comment]
I think that looks great.

**Comment by jordi5** [comment]
I found how to fix the savefig and subfigs buttons, aparently is an issue of matplotlib backend libraries

**Comment by jordi5** [comment]
This is a mess.

**Pull request closed without merging**
