### PR TITLE
Added File for Colorizing Logs

### PR DESCRIPTION
**Pull request by souravsingh**
Added a Python Script to Colorize Logs.The script makes use of Python Package called colorlogs for colorizing the logs.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@souravsingh so essentially you posted the example here now. this is not colorizing the logs of TARDIS!

**Comment by souravsingh** [comment]
I tested the example with TARDIS.It was working fine.

**Comment by souravsingh** [comment]
I have made changes in the file for colorizing the logs.I have tested the script.Although I do not understand why One test has failed.

**Comment by wkerzendorf** [comment]
no color: 
screenshot 2015-10-26 18 29 22

I think you should have a more indepth look at the python logging structure.

**Comment by souravsingh** [comment]
I ran the script in ``/tardis/simulation.py`` and I found it to be working.

**Comment by orbitfold** [comment]
Can you provide a step-by-step description of what I should do to get this working?

**Comment by souravsingh** [comment]
@orbitfold We need to add a line ```from colorlogs import log``` in place ```import logging``` in scripts which have logging to show colored logs since the colorlogs script makes use of the logging module.

**Comment by souravsingh** [comment]
It should work hopefully

**Comment by wkerzendorf** [comment]
@souravsingh as it stands this PR doesn't work. If you need to add a line in files to make it work - do it.

**Comment by souravsingh** [comment]
Alright,I will start making changes to scripts using logging module.

**Comment by souravsingh** [comment]
Could anyone let me know if colorizing works properly in the files I have committed?

**Comment by unoebauer** [comment]
@souravsingh: Will have a look at it shortly

**Comment by unoebauer** [comment]
@souravsingh Just tried it with the normal tardis_example - no visual change, the log is still completely monochrome. Seems to me that (at least in model.py) you are still using the old logger.

**Pull request closed without merging**
