### PR TITLE
Changed to append `seed` & `index` values only once for a particular `RPacketTracker` instance 

### PR DESCRIPTION
**Pull request by DhruvSondhi**
**Description**

**Motivation and context**

**How has this been tested?**
- [ ] Testing pipeline.
- [ ] Other. 

**Examples**

**Type of change**

- [x] Bug fix. 
- [x] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/contributing/development/documentation_guidelines.html#sharing-the-built-documentation-in-your-pr-documentation-preview).
- [x] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
can you rebase?

**Comment by DhruvSondhi** [comment]
This PR was made to be merged with the `single_seed_index` PR that was opened, #1879

**Comment by DhruvSondhi** [comment]
Changed the base branch to `master` for this PR

**Review by wkerzendorf — APPROVED** [review]
Looks good from my side

**Review by andrewfullard — APPROVED** [review]

**Pull request merged**
