### PR TITLE
Add array_diff tests to functions

### PR DESCRIPTION
**Pull request by KevinCawley**
This adds the arraydiff version of the GPU tests for the formal integral. 

**Description**

Arraydiff tests were written for the formal integral, which will work as a check against previous versions. These will compare the current version of the cuda formal integral with the past version stored in refdata. 

This needs the pip version of arraydiff, as the conda versions are not at or past 0.5, which is required for the tests to work. 
**Motivation and context**

Adding version tests to ensure results don't change. 

**How has this been tested?**
- [x] Testing pipeline.
- [ ] Other. 

**Examples**

**Type of change**

- [ ] Bug fix. 
- [x] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/contributing/development/documentation_guidelines.html#sharing-the-built-documentation-in-your-pr-documentation-preview).
- [x] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Comment by KevinCawley** [comment]
Do not merge this right now! Waiting for an update to the formal_integral to see if any breaking changes are made.

**Comment by Rodot-** [comment]
This PR requires updates to the tardis-refdata and azure testing pipelines to properly use pytest-arraydiff

**Comment by andrewfullard** [comment]
@Rodot- do we expect this PR to be finished?

**Comment by epassaro** [comment]
> @Rodot- do we expect this PR to be finished?

Yes, I think @KevinCawley is busy, and also we did not have enough LFS transfer quota to update the reference data as needed (I don't know if we have now).

**Comment by KevinCawley** [comment]
I can come back and look at this when I have the all clear, I forget what we are waiting for. 

Right now I do have a full-time job, so I don't have as much time to work on tardis.

**Comment by epassaro** [comment]
I want to mention that the newer version of pytest-arraydiff has been merged last week

**Pull request closed without merging**
