### PR TITLE
Plasma restructure

### PR DESCRIPTION
**Pull request by wkerzendorf**
Very extensive restructure of the plasma calculation.

### CODE REVIEW

**Comment by aoifeboyle** [comment]
@wkerzendorf I think I've gotten rid of the t_electrons error, but there's a weird new error. It doesn't say what the error is apart from 'The command "CC=$COMPILER python setup.py $SETUP_CMD" exited with 245.' Do you know what that means?

**Comment by aoifeboyle** [comment]
@wkerzendorf Error 245 has been defeated. Vytas thinks it was just a Travis glitch :)

**Comment by aoifeboyle** [comment]
@wkerzendorf I've finished adding the tests I wanted and I'd be happy to merge now.

**Comment by wkerzendorf** [comment]
@aoifeboyle we need to rebase

**Comment by aoifeboyle** [comment]
Ok @wkerzendorf I can do it I think

**Comment by wkerzendorf** [comment]
@ssim this is a massive merge - can you look at this as well.

**Comment by aoifeboyle** [comment]
@wkerzendorf Did you do the rebase?

**Comment by wkerzendorf** [comment]
I did a merge - but there seem to be problems. Can you check

**Comment by aoifeboyle** [comment]
Yeah sure

**Comment by wkerzendorf** [comment]
@aoifeboyle plasma_array also still exists in this branch.

**Comment by aoifeboyle** [comment]
@wkerzendorf did you just merge this? I removed some tests that still made use of functions in plasma_array and I'm still working through correcting them. But it should function fine if you merged it.

**Comment by wkerzendorf** [comment]
@aoifeboyle yep - more or less accidently. let's see how it goes. There is a revert PR. just make anew PR for your fixes.

**Comment by wkerzendorf** [comment]
you are number 3 behind vytas and myself

**Pull request merged**
