### PR TITLE
Add instructions to enable virtual packet logging

### PR DESCRIPTION
**Pull request by karban8**
## Description

This PR is an attempt to fix issue #1374
The configuration file has been updated and suitable instructions have been added in the jupyter notebook (enable_virtual_generating_widgets.ipynb)

## How Has This Been Tested?
- [ ] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

## Screenshots (if appropriate):
Screenshot from 2021-03-24 00-44-55
Screenshot from 2021-03-24 00-45-49
Screenshot from 2021-03-24 00-44-31

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by karban8** [comment]
@jaladh-singhal Please review my PR. Thanks

**Comment by andrewfullard** [comment]
Note that with the merge of #1498 this documentation needs to be updated to include the second way of enabling virtual packet logging. Furthermore, I am not sure that an explicit new notebook is needed to show how this works. Rather, a new section of text in the visualization notebook that this is based on should be enough.

**Comment by karban8** [comment]
> Note that with the merge of #1498 this documentation needs to be updated to include the second way of enabling virtual packet logging. Furthermore, I am not sure that an explicit new notebook is needed to show how this works. Rather, a new section of text in the visualization notebook that this is based on should be enough.

Alright I will incorporate the new changes. Also at first at I did try in the generating_widgets notebook (present in docs/using/visualization) but run_tardis(tardis_example.yml) gives a 'file not found' error though it is present in /docs/using

**Review by andrewfullard — COMMENTED** [review]
Do you plan to continue with this?

**Comment by jaladh-singhal** [comment]
> run_tardis(tardis_example.yml) gives a 'file not found' error though it is present in /docs/using
Because it needs to be present in `docs/using/visualization` - same directory where notebook lives.

**Review by jaladh-singhal — CHANGES_REQUESTED** [review]
Like @andrewfullard pointed out, there's no need of separate notebook. This should instead be a warning box in "Line Info Widget" section's starting - exact same as in existing sdec_plot notebook.

**Comment by marxwillia** [comment]
Closing due to inactivity.  Happy to reopen if work resumes.

**Pull request closed without merging**
