### PR TITLE
Fix logging

### LINKED ISSUE #1029: Fix logging
Logging is very verbose, can't be configured to log to a file - and does not know when to turn on/off colored logging.

### PR DESCRIPTION
**Pull request by atharva-2001**
This PR introduces a new logger and is an attempt to solve issue #1029, and also provides a few more options. I am using [Loguru](https://github.com/Delgan/loguru) to accomplish this task. 

## Description

**A list of changes made:** 
1. A verbosity option in `run_tardis` function: 
- The verbosity option is by default set to `TARDIS INFO` level. (Levels make it easy to prioritize messages. If the logger is set to a particular level, messages below that level are not logged. For example, if the level of the logger is `WARNING`, `DEBUG` messages won't get logged because they have a [severity](https://loguru.readthedocs.io/en/stable/api/logger.html#levels)  value less than that of `WARNING`.)
- The `TARDIS INFO` level has a [severity](https://loguru.readthedocs.io/en/stable/api/logger.html#levels) value equal to 35 and is, therefore, greater in severity than levels like `DEBUG`, `WARNING` and `INFO`. *I had converted all* `INFO` *messages to* `TARDIS INFO`  *messages to make this work.*
- the verbosity option can be used to set the logger to other levels as well and can show `WARNING` and `DEBUG` messages if desired
- the logging level can be changed even after it is set in the verbosity option
2. A log saving option:
- the log saving option allows the user to save the logs to a file. By default, the log is reset if it's more than 100 MBs. 
- if the level set is `WARNING`, the file saved will be file_WARNING.log, similarly for other levels
- The log files that were generated in my machine can be viewed [here](https://drive.google.com/drive/folders/1Gt3YaIITo5TOMrq6ox0KgSqHFPvay4cz?usp=sharing)

3. A `colorize` option:
- If set to true, the log output will be coloured. This is true by default. 
4. Capturing warnings: 
- Warnings are shown as log output instead of plain text

## Motivation and Context

1. resolves #1029 
2. solves the first objective of _Notebook Logging Framework_ problem mentioned [here](https://tardis-sn.github.io/gsoc/category/ideas-page.html)

## How Has This Been Tested?
- [x] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

This is tested locally and all notebooks are working fine. 
I also ran unit tests using `python setup.py test` and got `156 passed, 1254 skipped, 6 xpassed in 4.84s`

## Screenshots:
1. Default Setup
image

2. `DEBUG` option: 
DEBUG

3. `WARNING` option: 
WARNING

4. Removing colours: 
no colours

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

### CODE REVIEW

**Comment by atharva-2001** [comment]
I would request @marxwillia @MarkMageeAstro @jamesgillanders to please review the PR. 
I would really appreciate any feedback on this.

**Comment by wkerzendorf** [comment]
looks interesting. Can you make another PR that gets rid of all the `WARNINGS`

**Comment by atharva-2001** [comment]
Thanks for looking into it!
I could get rid of  `PerformanceWarning: indexing past lexsort depth may impact performance` but not of `RuntimeWarning: divide by zero encountered in double_scalars`
I guess the latter has something to do with underlying Astropy and NumPy modules.
Do you want me to create a PR for getting rid of `PerformanceWarning: indexing past lexsort depth may impact performance`?

**Comment by atharva-2001** [comment]
I am fixing the commit history, turning this into a draft pull request for now.

**Comment by MarkMageeAstro** [comment]
Looks very useful. Can you add some documentation explaining what each of the different levels are and maybe include a screenshot? i.e. there's TARDIS info and info.

**Comment by atharva-2001** [comment]
I'm glad you liked it! I will surely add the documentation in some time.

**Comment by atharva-2001** [comment]
@MarkMageeAstro I tried making the documentation and it's visible [here](https://atharva-2001.github.io/tardis/using/logging/logging.html). Would you mind telling me how it looks to you? 

If I set the log level to `INFO`, the messages that can be seen are either `WARNING` or `TARDIS INFO`. I had converted most of the `INFO` messages to `TARDIS INFO` messages.  
image

**Comment by jaladh-singhal** [comment]
@atharva-2001 this looks super helpful. The general color convention is to show: info as blue < warning as yellowish < error as red. It'll be great to have that here too - too much red color in "info" messages seems alarming to me. Besides, if you have noticed the info messages in the logger used throughout tardis codebase are in a shade of blue.

**Comment by atharva-2001** [comment]
Thanks for the review! I should have thought of the colour scheme. I changed it now though. The colour I am using now is `#8588ff` which is a little close to light purple, and also looks different from the `DEBUG` colour.  I'm afraid that the `INFO` messages were somewhat grey/silver [here](https://tardis-sn.github.io/tardis/quickstart/quickstart.html). Should I change the colour to that? If possible please let me know the hex value of the colour, and I will change it immediately.

**Pull request closed without merging**
