### PR TITLE
updated installation.rst

### PR DESCRIPTION
**Pull request by nileshpatra**
added an installation problem due to sphinx and its fix .

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@nileshpatra can you rebase to the new master branch

**Comment by nileshpatra** [comment]
You mean , make another branch branch and push changes there?

**Comment by wkerzendorf** [comment]
no - use this branch and rebase it using git.

**Comment by nileshpatra** [comment]
Okay , will do sure , but may I know , why is that required?

**Comment by nileshpatra** [comment]
did a rebase , this is what I got :  
```
 * branch              master     -> FETCH_HEAD
Already up to date.

```

**Comment by wkerzendorf** [comment]
it should have shown you the `rebase` log

**Comment by nileshpatra** [comment]
@wkerzendorf please see , if now it works

**Comment by wkerzendorf** [comment]
@nileshpatra you did not rebase - you merged. we can chat more about git rebase in gitter or here.

**Comment by nileshpatra** [comment]
@wkerzendorf , yes this was a new thing for me . I did
```
 git rebase -i upstream/master
```
is this now rebased ?

**Comment by wkerzendorf** [comment]
you made a merge commit - that means you did not really rebase. It should have also done it without any problem. try again - if it still doesn't work. you can make a new branch of upstream master and then cherry-pick the commits in this PR. good luck 😉

**Comment by nileshpatra** [comment]
@wkerzendorf , after writing the rebase command , I actually had to pick the commits I wanted , is that what you are talking about ? 
And should I now make a new PR , with a new fork ? I'm a little confused .

**Comment by wkerzendorf** [comment]
not quite - let's chat on gitter.

**Pull request closed without merging**
