### PR TITLE
corrected the typos 'balenced out' and 'eatimators'

### PR DESCRIPTION
**Pull request by chirag224**
**Description**

**Motivation and context**

**How has this been tested?**
- [ ] Testing pipeline.
- [ ] Other. 

**Examples**

**Type of change**

- [ ] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [x ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [  ] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Comment by chirag224** [comment]
@andrewfullard  can you review it ?

**Review by smithis7 — APPROVED** [review]
Yeah, those are some of my typos ☹️. Looks good to me, but @andrewfullard is this the kind of PR we want for a first contribution? I'll leave that to you.

**Comment by smithis7** [comment]
To avoid having very small commits on our repo, I've incorporated your changes in #1744 (you are listed as a contributor to that PR now). Thank you very much for catching those typos!

**Comment by chirag422** [comment]
..

**Comment by chirag224** [comment]
@smithis7 my username is chirag224 not chirag422

**Pull request closed without merging**
