### PR TITLE
add mailmap check workflow

### PR DESCRIPTION
**Pull request by epassaro**
**Description**

Checks if all committers in a PR are in the `.mailmap` (name and email).

Sorted `.mailmap` alphabetically.

**Motivation and context**

I'm not sure if this is a good workflow to merge, you decide.

Currently, the TARDIS policy is considering all committers as authors and order them by commit numbers plus other criteria. The new Zenodo metadata pipeline will not fail anymore when an author name is incomplete, or an author committed with different emails. In this case those authors/commits are just dropped and the pipeline keeps working the longest possible without human intervention.

Then, to not lose authors or commit contributions I wrote this pipeline that checks author name and email before merging a PR.

**How has this been tested?**
- [ ] Testing pipeline.
- [x] Other. 
The new pipeline itself!

**Examples**

**Type of change**

- [ ] Bug fix. 
- [x] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [x] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Comment by atharva-2001** [comment]
@epassaro, could you please add my name too?
```
atharva-2001 aryaa_1@rknec.edu
atharva-2001 atharva-2001@users.noreply.github.com
Atharva Arya 55894364+atharva-2001@users.noreply.github.com
Atharva Arya aryaatharva18@gmail.com
```

**Comment by epassaro** [comment]
> @epassaro, could you please add my name too?
> 
> ```
> atharva-2001 aryaa_1@rknec.edu
> atharva-2001 atharva-2001@users.noreply.github.com
> Atharva Arya 55894364+atharva-2001@users.noreply.github.com
> Atharva Arya aryaatharva18@gmail.com
> ```

what's your preferred email?

**Review by wkerzendorf — COMMENTED** [review]
I would then also include the ORCID check as well.

**Comment by epassaro** [comment]
> I would then also include the ORCID check as well.

I don't see any problem to keep ORCiD optional. The only difference should be names in Zenodo will not appear with the green "ID" balloon.

**Comment by epassaro** [comment]
> I'm sorry for the confusion, please add this email:
> 
> ```
> Atharva Arya <55894364+atharva-2001@users.noreply.github.com>
> ```

done

**Review by andrewfullard — APPROVED** [review]

**Review by DhruvSondhi — APPROVED** [review]

**Pull request merged**
