### PR TITLE
Remove lock file creation from pre release workflow

### PR DESCRIPTION
**Pull request by atharva-2001**
### :pencil: Description

**Type:** | :roller_coaster: `infrastructure`

This updates mamba version to avoid conda-lock problems. The `conda-incubator/setup-miniconda@v2` doesn't install mamba to latest versions.

### :pushpin: Resources

Examples, notebooks, and links to useful references.

Edited workflow for demonstration- 
https://github.com/atharva-2001/tardis/actions/runs/6431988476

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Review by andrewfullard — APPROVED** [review]
Looks great! Now we can have releases again. Can you check the post-release to make sure it doesn't do anything that relies on the lock file? Can you check the documentation about installation so that it works with the correct lock file?

**Comment by atharva-2001** [comment]
> Looks great! Now we can have releases again. Can you check the post-release to make sure it doesn't do anything that relies on the lock file? Can you check the documentation about installation so that it works with the correct lock file?

On it! Would let you know once I've checked!

**Comment by atharva-2001** [comment]
I saw nothing related to the lock file in the post-release workflow. These lines/section from the documentation should be removed however-
`conda install tardis-sn --channel conda-forge --no-deps`

and 

https://tardis-sn.github.io/tardis/installation.html#install-from-package

Rest everything works for me.
I was unable to do the conda package installation(`conda install tardis-sn...`) after the new env setup. I am removing those sections in this PR- if this is not the right thing to do, please let me know and I would remove the commit.

**Review by andrewfullard — APPROVED** [review]

**Comment by wkerzendorf** [comment]
can we finish this?

**Comment by andrewfullard** [comment]
Looks good to me. Please change the PR title!

**Review by andrewfullard — APPROVED** [review]

**Comment by atharva-2001** [comment]
> Please change the PR title!

Done!

**Pull request merged**
