### PR TITLE
Quantify-ify Tardis

### PR DESCRIPTION
**Pull request by sourabhyadav999**
## Description
The changes enables the user to get units of a single attribute or a group of attributes by using get_data_unit function. The user can create a copy of the current pandas data object as well as get all the units present iv the dataframe

 

## Motivation and Context
The changes were made to extend pandas library to include metadata (units) for a column.

## Types of changes

[ ] Bug fix (non-breaking change which fixes an issue)
 [ x] New feature (non-breaking change which adds functionality)
[ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

[x ] My code follows the code style of this project.
[ ] My change requires a change to the documentation.
 [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
Please add tests and documentation

**Comment by sourabhyadav999** [comment]
Okay Sir

**Comment by marxwillia** [comment]
And integrate astropy units.

**Comment by sourabhyadav999** [comment]
Sir I have added tests.

**Comment by wkerzendorf** [comment]
please add tests using pytest

**Comment by sourabhyadav999** [comment]
Sir I have added tests with pytest

**Comment by sourabhyadav999** [comment]
> And integrate astropy units.

Sir I am not able to understand what we have to do in this. Can you please clarify sir?

**Comment by wkerzendorf** [comment]
read up on pytest - your current use of this package is not right.

**Pull request closed without merging**
