### PR TITLE
Convert quantities to arrays when plotting in SDEC plot

### PR DESCRIPTION
**Pull request by atharva-2001**
This fixes the docs build that was caused due to the new matplotlib release.

**Description**

Using quantities with `matplotlib`'s `fill_between` method was causing an error. This PR changes quantities to arrays, just when plotting, everywhere in the SDEC plot so that no problems arise later as well. 

**Motivation and context**

**How has this been tested?**
- [X] Testing pipeline.
- [ ] Other. 

**Examples**

[Link](https://github.com/jaladh-singhal/tardis/runs/4301154620?check_suite_focus=true) to a failed documentation build
[working docs build](https://atharva-2001.github.io/tardis/branch/quantity_support/)
**Type of change**

- [X] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [ ] I have assigned and requested two reviewers for this pull request.

### CODE REVIEW

**Review by jamesgillanders — COMMENTED** [review]
this fixes the problem, but do we want to do this, or pin the matplotlib version?

**Comment by smithis7** [comment]
> this fixes the problem, but do we want to do this, or pin the matplotlib version?

We definitely want this. Pinning the matplotlib version was a backup in case this problem was not easy enough to fix.

**Review by smithis7 — COMMENTED** [review]
My only concern here is do we allow users to use different units when plotting? And either way, we should probably have the units printed on the axes, [something like this](https://github.com/tardis-sn/tardis/blob/master/tardis/montecarlo/spectrum.py#L105).

**Review by jaladh-singhal — APPROVED** [review]
Thanks!

**Comment by jaladh-singhal** [comment]
> My only concern here is do we allow users to use different units when plotting? And either way, we should probably have the units printed on the axes, [something like this](https://github.com/tardis-sn/tardis/blob/master/tardis/montecarlo/spectrum.py#L105).

I think that we infer unit to be shown on axes from quantity. If not, then that's case for another issue/PR @smithis7 @atharva-2001 - it's out of scope for this PR.

**Review by smithis7 — APPROVED** [review]
Looks good

**Pull request merged**
