### PR TITLE
Implementing slow tests

### PR DESCRIPTION
**Pull request by Minhmo**
This PR implements running slow test (test_tardis_full.py), only when a command line option '--slow' is specified. Example of a command that runs slow tests: 'py.test --slow -q --atomic-dataset=< your path>'

Changes made to:
-     conftest.py (added a parser option to recognize --slow)
-     test_tardis_full.py (added pytest 'skipif' decorator, which skips the tests if --slow is not specified)

This is a prelim task for testing module. @Orbitfold

### CODE REVIEW

**Comment by Minhmo** [comment]
Anyway, have no idea why tests fail. Didn't change any logic.

**Comment by karandesai-96** [comment]
@Minhmo Please refer to #509 :smile: The fault is not in your code.

**Comment by Minhmo** [comment]
@karandesai-96  Thank you very much :)

**Comment by karandesai-96** [comment]
@Minhmo, my fix has been merged to master, hence this might do the job:
```
git checkout master
git pull upstream master
git checkout implementing-slow-tests
git rebase master
```
The next build you see will bleed green provided you didn't break anything.. Cheers !

**Comment by wkerzendorf** [comment]
no there's no need to pull upstream master. Do `fetch upstream` and then rebase to `upstream/master`

**Comment by wkerzendorf** [comment]
@Minhmo as a next exercise you should look at the examples given in the TEP.

**Comment by Minhmo** [comment]
@wkerzendorf by writing "TEP" you refer to [this](https://github.com/tardis-sn/tep)? Just to be clear..

**Comment by unoebauer** [comment]
I think @wkerzendorf is specifically referring to the setups in the [PR](https://github.com/tardis-sn/tep/pull/13) - this should eventually become slow tests.

**Comment by orbitfold** [comment]
@Minhmo the idea is to make sure that the spectra produced using the configuration files @unoebauer linked to are always the same. Generate spectra using those examples and add slow tests for this. Use test_tardis_full.py for inspiration. Basically you will need to store the spectra in the repository and add code to test that TARDIS output is identical to those spectra. Someone correct me if I'm wrong.

**Comment by wkerzendorf** [comment]
sounds about right - @Minhmo can you rebase to master?

**Comment by Minhmo** [comment]
@wkerzendorf Done.
@orbitfold Just want to make sure, that I am getting this right. So I should write a test method, that generates the spectra from config (.yml) files in @unoebauer PR, and compare them to be exactly the same to outputs (.dat) provided by the same PR?

**Comment by wkerzendorf** [comment]
@Minhmo doesn't look like a rebase. Still can't merge and no new commits.

**Comment by wkerzendorf** [comment]
@Minhmo you will have to run them yourself for the comparison.

**Comment by Minhmo** [comment]
@wkerzendorf  finally got it to go. Sorry for the mess, tried to do everything nicely, but... I should work on my github skills :smile:

**Comment by wkerzendorf** [comment]
There are quite a few merge commits. You should squash those

**Comment by wkerzendorf** [comment]
@hemantkhatri27 I think this issue should also be taking elsewhere than @Minhmo's PR. open an issue separately if you want to discuss that.

**Comment by wkerzendorf** [comment]
@Minhmo look at my last comment.

**Comment by Minhmo** [comment]
@wkerzendorf sorry for taking so long.

**Comment by wkerzendorf** [comment]
@Minhmo can you make a new PR that is based on the current master with your changes. There are quite a few file changes that should not be in there - including the conda-requirements file change.

**Pull request closed without merging**
